package xol.lostinfinity.init;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.world.World;
import xol.lostinfinity.block.activator.BlockAlienSlide;
import xol.lostinfinity.block.activator.BlockAlignmentDialGame;
import xol.lostinfinity.block.activator.BlockAlignmentTile;
import xol.lostinfinity.block.activator.BlockAncientSymbol;
import xol.lostinfinity.block.activator.BlockAncientSymbolInterpreter;
import xol.lostinfinity.block.activator.BlockArenaBoss;
import xol.lostinfinity.block.activator.BlockAugmenticonCreator;
import xol.lostinfinity.block.activator.BlockBlightEyeBattery;
import xol.lostinfinity.block.activator.BlockBlightEyeSocket;
import xol.lostinfinity.block.activator.BlockBombDeployerPowerup;
import xol.lostinfinity.block.activator.BlockBossGate;
import xol.lostinfinity.block.activator.BlockCellCharger;
import xol.lostinfinity.block.activator.BlockCellContainer;
import xol.lostinfinity.block.activator.BlockCellGame;
import xol.lostinfinity.block.activator.BlockChargeCore;
import xol.lostinfinity.block.activator.BlockChipFormatter;
import xol.lostinfinity.block.activator.BlockChipFormatterPower;
import xol.lostinfinity.block.activator.BlockChromaGame;
import xol.lostinfinity.block.activator.BlockChromaTile;
import xol.lostinfinity.block.activator.BlockCircuitCalibrator;
import xol.lostinfinity.block.activator.BlockCircuitMonitor;
import xol.lostinfinity.block.activator.BlockConnectButton;
import xol.lostinfinity.block.activator.BlockConnectGame;
import xol.lostinfinity.block.activator.BlockContainmentGate;
import xol.lostinfinity.block.activator.BlockContestGame;
import xol.lostinfinity.block.activator.BlockCrusherButton;
import xol.lostinfinity.block.activator.BlockDeviationField;
import xol.lostinfinity.block.activator.BlockDimensionalizer;
import xol.lostinfinity.block.activator.BlockDrillConsole;
import xol.lostinfinity.block.activator.BlockDrillControl;
import xol.lostinfinity.block.activator.BlockDungeonSelector;
import xol.lostinfinity.block.activator.BlockEssenceIdol;
import xol.lostinfinity.block.activator.BlockFishChow;
import xol.lostinfinity.block.activator.BlockGalaxyChallenge;
import xol.lostinfinity.block.activator.BlockGalaxyRewardSelector;
import xol.lostinfinity.block.activator.BlockGeolocator;
import xol.lostinfinity.block.activator.BlockGloomIdol;
import xol.lostinfinity.block.activator.BlockGuideBlock;
import xol.lostinfinity.block.activator.BlockGuideButton;
import xol.lostinfinity.block.activator.BlockItemChallenge;
import xol.lostinfinity.block.activator.BlockItemGame;
import xol.lostinfinity.block.activator.BlockItemGameCollector;
import xol.lostinfinity.block.activator.BlockLabGameType1;
import xol.lostinfinity.block.activator.BlockLabGameType2;
import xol.lostinfinity.block.activator.BlockLabGameType3;
import xol.lostinfinity.block.activator.BlockLabGate;
import xol.lostinfinity.block.activator.BlockLabTeleporter;
import xol.lostinfinity.block.activator.BlockLaunchCore;
import xol.lostinfinity.block.activator.BlockLightEmitter;
import xol.lostinfinity.block.activator.BlockLightReflector;
import xol.lostinfinity.block.activator.BlockLightSwitch;
import xol.lostinfinity.block.activator.BlockLightSwitchGame;
import xol.lostinfinity.block.activator.BlockLightTile;
import xol.lostinfinity.block.activator.BlockLightTileGame;
import xol.lostinfinity.block.activator.BlockMainPowerTerminal;
import xol.lostinfinity.block.activator.BlockMazeCreator;
import xol.lostinfinity.block.activator.BlockMelodicSequencer;
import xol.lostinfinity.block.activator.BlockMelodyButton;
import xol.lostinfinity.block.activator.BlockMetaMaterializer;
import xol.lostinfinity.block.activator.BlockMonomerCube;
import xol.lostinfinity.block.activator.BlockMonomerDeposit;
import xol.lostinfinity.block.activator.BlockNavigationDevice;
import xol.lostinfinity.block.activator.BlockNavigationNodule;
import xol.lostinfinity.block.activator.BlockNeocraft;
import xol.lostinfinity.block.activator.BlockNeocraftingStation;
import xol.lostinfinity.block.activator.BlockPipe;
import xol.lostinfinity.block.activator.BlockPipeGame;
import xol.lostinfinity.block.activator.BlockPolymerizationDevice;
import xol.lostinfinity.block.activator.BlockPortalNode;
import xol.lostinfinity.block.activator.BlockPowerCollider;
import xol.lostinfinity.block.activator.BlockPowerColliderTrack;
import xol.lostinfinity.block.activator.BlockPowerConduit;
import xol.lostinfinity.block.activator.BlockPowerGenerator;
import xol.lostinfinity.block.activator.BlockPowerNodule;
import xol.lostinfinity.block.activator.BlockPresent;
import xol.lostinfinity.block.activator.BlockPuzzleKey;
import xol.lostinfinity.block.activator.BlockRadionPillar;
import xol.lostinfinity.block.activator.BlockRainfallGenerator;
import xol.lostinfinity.block.activator.BlockRhythmButton;
import xol.lostinfinity.block.activator.BlockRhythmGame;
import xol.lostinfinity.block.activator.BlockRhythmTile;
import xol.lostinfinity.block.activator.BlockRingGame;
import xol.lostinfinity.block.activator.BlockRingSlideButton;
import xol.lostinfinity.block.activator.BlockRingTile;
import xol.lostinfinity.block.activator.BlockRotatableTile;
import xol.lostinfinity.block.activator.BlockRotatableTileGame;
import xol.lostinfinity.block.activator.BlockRowIncrementButton;
import xol.lostinfinity.block.activator.BlockRowIncrementGame;
import xol.lostinfinity.block.activator.BlockRowIncrementTile;
import xol.lostinfinity.block.activator.BlockRowSlideButton;
import xol.lostinfinity.block.activator.BlockRowSlideGame;
import xol.lostinfinity.block.activator.BlockRowSlideTile;
import xol.lostinfinity.block.activator.BlockRowToggleButton;
import xol.lostinfinity.block.activator.BlockRowToggleGame;
import xol.lostinfinity.block.activator.BlockSecurityGate;
import xol.lostinfinity.block.activator.BlockSnakeGuide;
import xol.lostinfinity.block.activator.BlockStarforgeDeclogger;
import xol.lostinfinity.block.activator.BlockStarforgeInput;
import xol.lostinfinity.block.activator.BlockTerrorGlow;
import xol.lostinfinity.block.activator.BlockTimelineStabilizerArrow;
import xol.lostinfinity.block.activator.BlockTimelineStabilizerConsole;
import xol.lostinfinity.block.activator.BlockTrialGate;
import xol.lostinfinity.block.activator.BlockUnpoweredCharger;
import xol.lostinfinity.block.activator.BlockUnpoweredFabBattery;
import xol.lostinfinity.block.activator.BlockUnpoweredHyperGenerator;
import xol.lostinfinity.block.activator.BlockUnpoweredModulationBattery;
import xol.lostinfinity.block.activator.BlockVoidFlower;
import xol.lostinfinity.block.activator.BlockWhack;
import xol.lostinfinity.block.activator.BlockWhackGame;
import xol.lostinfinity.block.basic.BlockBasic;
import xol.lostinfinity.block.basic.BlockBasicBoolState;
import xol.lostinfinity.block.basic.BlockBasicCrop;
import xol.lostinfinity.block.basic.BlockBasicGlass;
import xol.lostinfinity.block.basic.BlockBasicGui;
import xol.lostinfinity.block.basic.BlockBasicLight;
import xol.lostinfinity.block.basic.BlockBasicMoistured;
import xol.lostinfinity.block.basic.BlockBasicNoCollide;
import xol.lostinfinity.block.basic.BlockBasicNoDrop;
import xol.lostinfinity.block.basic.BlockBasicPillar;
import xol.lostinfinity.block.basic.BlockBasicPlant;
import xol.lostinfinity.block.basic.BlockBasicRotational;
import xol.lostinfinity.block.basic.BlockBasicSlab;
import xol.lostinfinity.block.basic.BlockBasicSpawner;
import xol.lostinfinity.block.basic.BlockBasicStairs;
import xol.lostinfinity.block.basic.BlockBasicTransparencyPlant;
import xol.lostinfinity.block.basic.BlockCappedPlant;
import xol.lostinfinity.block.basic.BlockStarforgeOre;
import xol.lostinfinity.block.crafting.BlockChemistryTable;
import xol.lostinfinity.block.crafting.BlockCompressionTable;
import xol.lostinfinity.block.crafting.BlockDeconstructor;
import xol.lostinfinity.block.crafting.BlockFabricationTable;
import xol.lostinfinity.block.crafting.BlockFusionTable;
import xol.lostinfinity.block.crafting.BlockGrinder;
import xol.lostinfinity.block.crafting.BlockModulator;
import xol.lostinfinity.block.crafting.BlockNicroniumInfuser;
import xol.lostinfinity.block.crafting.BlockSapEvaporator;
import xol.lostinfinity.block.crafting.BlockShipmentFiller;
import xol.lostinfinity.block.crafting.BlockWeldingChamber;
import xol.lostinfinity.block.generator.BlockEternalBeacon;
import xol.lostinfinity.block.generator.BlockItemRipper;
import xol.lostinfinity.block.generator.BlockShockwaveGenerator;
import xol.lostinfinity.block.generator.BlockSkyStriker;
import xol.lostinfinity.block.generator.BlockTetherCreator;
import xol.lostinfinity.block.harvest.BlockAtomiteOre;
import xol.lostinfinity.block.harvest.BlockAuradineOre;
import xol.lostinfinity.block.harvest.BlockAzureLeaf;
import xol.lostinfinity.block.harvest.BlockCatatoniteOre;
import xol.lostinfinity.block.harvest.BlockCelestialLogsBlue;
import xol.lostinfinity.block.harvest.BlockCelestialLogsPurple;
import xol.lostinfinity.block.harvest.BlockCelestialLogsRed;
import xol.lostinfinity.block.harvest.BlockCellularOre;
import xol.lostinfinity.block.harvest.BlockCloviniteOre;
import xol.lostinfinity.block.harvest.BlockDarksteelOre;
import xol.lostinfinity.block.harvest.BlockEmberslag;
import xol.lostinfinity.block.harvest.BlockExothermiteOre;
import xol.lostinfinity.block.harvest.BlockGloominessenceOre;
import xol.lostinfinity.block.harvest.BlockHiveniteOre;
import xol.lostinfinity.block.harvest.BlockIgneousPearlOre;
import xol.lostinfinity.block.harvest.BlockIncandesciteOre;
import xol.lostinfinity.block.harvest.BlockIoniteOre;
import xol.lostinfinity.block.harvest.BlockLuminescentOre;
import xol.lostinfinity.block.harvest.BlockMetalloidLogs;
import xol.lostinfinity.block.harvest.BlockMultiversiteMurk;
import xol.lostinfinity.block.harvest.BlockMurkLogs;
import xol.lostinfinity.block.harvest.BlockMyriteOre;
import xol.lostinfinity.block.harvest.BlockPhototenzyteOre;
import xol.lostinfinity.block.harvest.BlockPrismosisOre;
import xol.lostinfinity.block.harvest.BlockRadionOre;
import xol.lostinfinity.block.harvest.BlockSeaClay;
import xol.lostinfinity.block.harvest.BlockSeparatedMatter;
import xol.lostinfinity.block.harvest.BlockSerpentineOre;
import xol.lostinfinity.block.harvest.BlockSunderLogs;
import xol.lostinfinity.block.harvest.BlockSunderwoodSap;
import xol.lostinfinity.block.harvest.BlockSunstoneOre;
import xol.lostinfinity.block.harvest.BlockSynchroniteOre;
import xol.lostinfinity.block.misc.BlockAcidPocket;
import xol.lostinfinity.block.misc.BlockAcidicConcoctionGel;
import xol.lostinfinity.block.misc.BlockAcidicGel;
import xol.lostinfinity.block.misc.BlockArchlumioGate;
import xol.lostinfinity.block.misc.BlockArchlumioGatePass;
import xol.lostinfinity.block.misc.BlockAstroBarrier;
import xol.lostinfinity.block.misc.BlockBattleSnake;
import xol.lostinfinity.block.misc.BlockBattleSnakeHead;
import xol.lostinfinity.block.misc.BlockBattleSnakePowerup;
import xol.lostinfinity.block.misc.BlockBlightedCore;
import xol.lostinfinity.block.misc.BlockCelestialBody;
import xol.lostinfinity.block.misc.BlockCombustionEngine;
import xol.lostinfinity.block.misc.BlockConcentratedAcid;
import xol.lostinfinity.block.misc.BlockContestEliminator;
import xol.lostinfinity.block.misc.BlockCoral;
import xol.lostinfinity.block.misc.BlockCosmicFracture;
import xol.lostinfinity.block.misc.BlockCthulhuSpawner;
import xol.lostinfinity.block.misc.BlockEmberslagDeposit;
import xol.lostinfinity.block.misc.BlockEmptyHiveniteOre;
import xol.lostinfinity.block.misc.BlockEmptyHoneyGel;
import xol.lostinfinity.block.misc.BlockEtherstock;
import xol.lostinfinity.block.misc.BlockFallBridge;
import xol.lostinfinity.block.misc.BlockFossilTrack;
import xol.lostinfinity.block.misc.BlockFungalBlockage;
import xol.lostinfinity.block.misc.BlockGalaxyGate;
import xol.lostinfinity.block.misc.BlockGalaxyPortal;
import xol.lostinfinity.block.misc.BlockGearbox;
import xol.lostinfinity.block.misc.BlockGlowingTile;
import xol.lostinfinity.block.misc.BlockInkable;
import xol.lostinfinity.block.misc.BlockKillerVine;
import xol.lostinfinity.block.misc.BlockLabPortal;
import xol.lostinfinity.block.misc.BlockLaserField;
import xol.lostinfinity.block.misc.BlockLaunchCoordinator;
import xol.lostinfinity.block.misc.BlockLeavesArchlum;
import xol.lostinfinity.block.misc.BlockLeavesNitro;
import xol.lostinfinity.block.misc.BlockLightBridge;
import xol.lostinfinity.block.misc.BlockLightReceiver;
import xol.lostinfinity.block.misc.BlockLogsArchlum;
import xol.lostinfinity.block.misc.BlockLogsNitro;
import xol.lostinfinity.block.misc.BlockLucientOre;
import xol.lostinfinity.block.misc.BlockMoldedSeaClay;
import xol.lostinfinity.block.misc.BlockMultiversiteOverworld;
import xol.lostinfinity.block.misc.BlockNebulousBeacon;
import xol.lostinfinity.block.misc.BlockNeoshocker;
import xol.lostinfinity.block.misc.BlockParkourPlatform;
import xol.lostinfinity.block.misc.BlockParkourPlatformSlippery;
import xol.lostinfinity.block.misc.BlockPortalNexus;
import xol.lostinfinity.block.misc.BlockPowerCrystal;
import xol.lostinfinity.block.misc.BlockPoweredHyperGenerator;
import xol.lostinfinity.block.misc.BlockPoweredHyperMelder;
import xol.lostinfinity.block.misc.BlockPuzzleArenaFloor;
import xol.lostinfinity.block.misc.BlockPuzzleLava;
import xol.lostinfinity.block.misc.BlockRemoteControl;
import xol.lostinfinity.block.misc.BlockRiftEntangledTile;
import xol.lostinfinity.block.misc.BlockStarblock;
import xol.lostinfinity.block.misc.BlockSunderwoodSapEmpty;
import xol.lostinfinity.block.misc.BlockSynchroniteSignal;
import xol.lostinfinity.block.misc.BlockTarget;
import xol.lostinfinity.block.misc.BlockTentacleEyeBlueEmpty;
import xol.lostinfinity.block.misc.BlockTentacleEyePinkEmpty;
import xol.lostinfinity.block.misc.BlockTentacleEyePurpleEmpty;
import xol.lostinfinity.block.misc.BlockTeslaTower;
import xol.lostinfinity.block.misc.BlockTimelineStabilizerPortal;
import xol.lostinfinity.block.misc.BlockTrackTrigger;
import xol.lostinfinity.block.misc.BlockTreadmillTrack;
import xol.lostinfinity.block.misc.BlockUnpoweredHyperMelder;
import xol.lostinfinity.block.misc.BlockViralGrowth;
import xol.lostinfinity.block.misc.BlockVoidVacuum;
import xol.lostinfinity.block.misc.BlockWeaverWeb;
import xol.lostinfinity.gui.GuiHandler;
public class BlockInit {
    public static final List<Block> BLOCKS = new ArrayList();
    public static final Block arenaBrickBlue = new BlockBasic("arena_brick_blue");
    public static final Block arenaBrickRed = new BlockBasic("arena_brick_red");
    public static final Block arenaBrickYellow = new BlockBasic("arena_brick_yellow");
    public static final Block arenaBrickBlack = new BlockBasic("arena_brick_black");
    public static final Block arenaStairBrickBlue = new BlockBasicStairs("arena_brick_blue_stairs", 3.0f, arenaBrickBlue.func_176223_P());
    public static final Block arenaStairBrickRed = new BlockBasicStairs("arena_brick_red_stairs", 3.0f, arenaBrickRed.func_176223_P());
    public static final Block arenaStairBrickYellow = new BlockBasicStairs("arena_brick_yellow_stairs", 3.0f, arenaBrickYellow.func_176223_P());
    public static final Block arenaStairBrickBlack = new BlockBasicStairs("arena_brick_black_stairs", 3.0f, arenaBrickBlack.func_176223_P());
    public static final Block arenaPillarBlue = new BlockBasic("arena_pillar_blue");
    public static final Block arenaPillarSea = new BlockBasic("arena_pillar_sea");
    public static final Block arenaPillarYellow = new BlockBasic("arena_pillar_yellow");
    public static final Block arenaSlabsBlue = new BlockBasic("arena_slabs_blue");
    public static final Block arenaSlabsSea = new BlockBasic("arena_slabs_sea");
    public static final Block arenaAniSlabsBlue = new BlockBasic("arena_ani_slabs_blue");
    public static final Block arenaAniSlabsSea = new BlockBasicLight("arena_ani_slabs_sea");
    public static final Block arenaGlassOrange = new BlockBasicGlass("arena_glass_orange");
    public static final Block arenaGlassYellow = new BlockBasicGlass("arena_glass_yellow");
    public static final Block arenaGlassSea = new BlockBasicGlass("arena_glass_sea");
    public static final Block arenaLampBlue = new BlockBasicLight("arena_lamp_blue");
    public static final Block arenaLampSea = new BlockBasicLight("arena_lamp_sea");
    public static final Block arenaLamprazorBlue = new BlockBasicLight("arena_lamprazor_blue");
    public static final Block arenaLamprazorRed = new BlockBasicLight("arena_lamprazor_red");
    public static final Block arenaLamprazorYellow = new BlockBasicLight("arena_lamprazor_yellow");
    public static final Block arenaGlassBlue = new BlockBasicGlass("arena_glass_blue");
    public static final Block celestialBarrier = new BlockBasicGlass("celestial_barrier");
    public static final Block celestialOuterMaroon = new BlockBasicGlass("celestial_outer_maroon");
    public static final Block celestialOuterPurple = new BlockBasicGlass("celestial_outer_purple");
    public static final Block celestialOuterBlue = new BlockBasicGlass("celestial_outer_blue");
    public static final Block celestialOuterNavy = new BlockBasicGlass("celestial_outer_navy");
    public static final Block celestialBodyRed = new BlockCelestialBody("celestial_body_red");
    public static final Block celestialBodyViolet = new BlockCelestialBody("celestial_body_violet");
    public static final Block celestialBodyYellow = new BlockCelestialBody("celestial_body_yellow");
    public static final Block celestialBodyBlue = new BlockCelestialBody("celestial_body_blue");
    public static final Block celestialCoreOrange = new BlockCelestialBody("celestial_core_orange");
    public static final Block celestialCoreGreen = new BlockCelestialBody("celestial_core_green");
    public static final Block celestialCoreYellow = new BlockCelestialBody("celestial_core_yellow");
    public static final Block celestialCoreBlue = new BlockCelestialBody("celestial_core_blue");
    public static final Block celestialEyeYellow = new BlockBasicLight("celestial_eye_yellow");
    public static final Block celestialEyeLime = new BlockBasicLight("celestial_eye_lime");
    public static final Block celestialEyeBlue = new BlockBasicLight("celestial_eye_blue");
    public static final Block celestialEyePink = new BlockBasicLight("celestial_eye_pink");
    public static final Block celestialArmorNavy = new BlockBasic("celestial_armor_navy");
    public static final Block celestialTrimNavy = new BlockBasic("celestial_trim_navy");
    public static final Block celestialArmorPurple = new BlockBasic("celestial_armor_purple");
    public static final Block celestialTrimPurple = new BlockBasic("celestial_trim_purple");
    public static final Block celestialArmorTeal = new BlockBasic("celestial_armor_teal");
    public static final Block celestialTrimTeal = new BlockBasic("celestial_trim_teal");
    public static final Block celestialArmorPink = new BlockBasic("celestial_armor_pink");
    public static final Block celestialTrimPink = new BlockBasic("celestial_trim_pink");
    public static final Block deviationField = new BlockDeviationField("deviation_field");
    public static final Block arenaBarrier = new BlockBasicGlass("arena_barrier");
    public static final Block arenaSummoner = new BlockArenaBoss("arena_summoner");
    public static final Block arenaSteelBlack = new BlockBasic("arena_steel_black");
    public static final Block arenaSteelBlue = new BlockBasic("arena_steel_blue");
    public static final Block arenaLampDark = new BlockBasicLight("arena_lamp_dark");
    public static final Block labWizardSpawner = new BlockBasicSpawner("spawner_lab_wizard", "labwizard");
    public static final Block labWarriorSpawner = new BlockBasicSpawner("spawner_lab_warrior", "labwarrior");
    public static final Block arenaLampRed = new BlockBasicLight("arena_lamp_red");
    public static final Block labGameBlue = new BlockLabGameType1("lab_game_blue");
    public static final Block labGameYellow = new BlockLabGameType2("lab_game_yellow");
    public static final Block labGamePurple = new BlockLabGameType3("lab_game_purple");
    public static final Block labGate = new BlockLabGate("lab_gate");
    public static final Block labRelocator = new BlockLabTeleporter("lab_relocator");
    public static final Block logsCelestial = new BlockCelestialLogsBlue("logs_celestial");
    public static final Block leavesCelestialBlue = new BlockBasicLight("leaves_celestial_blue");
    public static final Block leavesCelestialSea = new BlockBasicLight("leaves_celestial_sea");
    public static final Block logsCelestialRed = new BlockCelestialLogsRed("logs_celestial_red");
    public static final Block leavesCelestialRed = new BlockBasicLight("leaves_celestial_red");
    public static final Block astroRock = new BlockBasic("astrorock");
    public static final Block astroSteel = new BlockBasic("astrosteel");
    public static final Block powerBlockBlue = new BlockPowerCrystal("power_block_blue");
    public static final Block powerBlockGreen = new BlockPowerCrystal("power_block_green");
    public static final Block powerBlockYellow = new BlockPowerCrystal("power_block_yellow");
    public static final Block powerBlockPurple = new BlockPowerCrystal("power_block_purple");
    public static final Block omniPowerBlock = new BlockPowerCrystal("omni_power_block");
    public static final Block astroRockBlue = new BlockBasic("astrorock_blue");
    public static final Block astroRockGreen = new BlockBasic("astrorock_green");
    public static final Block astroRockYellow = new BlockBasic("astrorock_yellow");
    public static final Block astroRockPurple = new BlockBasic("astrorock_purple");
    public static final Block astroBarrierBlue = new BlockAstroBarrier("astrobarrier_blue");
    public static final Block astroBarrierGreen = new BlockAstroBarrier("astrobarrier_green");
    public static final Block astroBarrierYellow = new BlockAstroBarrier("astrobarrier_yellow");
    public static final Block astroBarrierPurple = new BlockAstroBarrier("astrobarrier_purple");
    public static final Block astroRockLampBlue = new BlockBasicLight("astrorock_lamp_blue");
    public static final Block astroRockLampGreen = new BlockBasicLight("astrorock_lamp_green");
    public static final Block astroRockLampYellow = new BlockBasicLight("astrorock_lamp_yellow");
    public static final Block astroRockLampPurple = new BlockBasicLight("astrorock_lamp_purple");
    public static final Block shockwaveGenerator = new BlockShockwaveGenerator("shockwave_generator");
    public static final Block skyStriker = new BlockSkyStriker("sky_striker");
    public static final Block tetherCreator = new BlockTetherCreator("tether_creator");
    public static final Block itemRipper = new BlockItemRipper("item_ripper");
    public static final Block rangeModule = new BlockBasic("range_module");
    public static final Block efficiencyModule = new BlockBasic("efficiency_module");
    public static final Block powerModule = new BlockBasic("power_module");
    public static final Block depthModule = new BlockBasic("depth_module");
    public static final Block galDungeonReward1 = new BlockGalaxyRewardSelector("galdungeonreward1", 3.0f, 1.0f);
    public static final Block galDungeonReward2 = new BlockGalaxyRewardSelector("galdungeonreward2", 3.0f, 0.4f);
    public static final Block galDungeonReward3 = new BlockGalaxyRewardSelector("galdungeonreward3", 3.0f, 0.8f);
    public static final Block galDungeonReward4 = new BlockGalaxyRewardSelector("galdungeonreward4", 3.0f, 0.6f);
    public static final Block galDungeonTarget = new BlockBasicLight("galdungeontarget");
    public static final Block galaxyBeastSpawner = new BlockBasicSpawner("spawner_galaxy_beast", "galaxybeast");
    public static final Block galaxySorcererSpawner = new BlockBasicSpawner("spawner_galaxy_sorcerer", "galaxysorcerer");
    public static final Block galaxyGladiatorSpawner = new BlockBasicSpawner("spawner_galaxy_gladiator", "galaxygladiator");
    public static final Block powerKeyBlock = new BlockBasicGlass("power_key_block");
    public static final Block astroRockGlass = new BlockBasicGlass("astrorock_glass");
    public static final Block championCarpetHolodeck = new BlockBasic("champion_carpet_holodeck").func_149715_a(1.0f);
    public static final Block championCarpetWaitingZone = new BlockBasic("champion_carpet_waitingzone").func_149715_a(1.0f);
    public static final Block championSteel = new BlockBasic("champion_steel").func_149715_a(0.5f);
    public static final Block championSteelBeam = new BlockBasicRotational("champion_steel_beam").func_149715_a(0.5f);
    public static final Block championSteelWiring = new BlockBasicLight("champion_steel_wiring");
    public static final Block championGlass = new BlockBasicGlass("champion_glass");
    public static final Block championLight = new BlockBasicLight("champion_light");
    public static final Block championBay = new BlockBasic("champion_bay");
    public static final Block championReinforcement = new BlockBasic("champion_reinforcement");
    public static final Block championGate = new BlockBasicGlass("champion_gate").func_149715_a(0.5f);
    public static final Block championSteelFloor = new BlockBasicLight("champion_steel_floor");
    public static final Block championCarpetCut = new BlockBasicRotational("champion_carpet_cut").func_149715_a(1.0f);
    public static final Block championPlatform = new BlockBasic("champion_platform");
    public static final Block championTemperedGlass = new BlockCelestialBody("champion_temperedglass");
    public static final Block championPlatformHighlighted = new BlockBasicLight("champion_platform_highlighted");
    public static final Block championTemperedGlassHighlighted = new BlockCelestialBody("champion_temperedglass_highlighted");
    public static final Block championSteelStairs = new BlockBasicStairs("champion_steel_stairs", 3.0f, championSteel.func_176223_P()).func_149715_a(1.0f);
    public static final Block starblock = new BlockStarblock("starblock");
    public static final Block screenHunterKiller = new BlockContestGame("screen_hunterkiller", 2);
    public static final Block screenHolodeck = new BlockContestGame("screen_holodeck", 1);
    public static final Block screenBlackMarket = new BlockContestGame("screen_blackmarket", -1);
    public static final Block oreDepleted = new BlockStarforgeOre("depleted_ore", true);
    public static final Block oreEmberium = new BlockStarforgeOre("emberium_ore").setCorrespondingItem(ItemInit.emberium);
    public static final Block oreHextorium = new BlockStarforgeOre("hextorium_ore").setCorrespondingItem(ItemInit.hextorium);
    public static final Block oreCrystonium = new BlockStarforgeOre("crystonium_ore").setCorrespondingItem(ItemInit.crystonium);
    public static final Block oreAstrallium = new BlockStarforgeOre("astrallium_ore").setCorrespondingItem(ItemInit.astrallium);
    public static final Block oreKylaxium = new BlockStarforgeOre("kylaxium_ore").setCorrespondingItem(ItemInit.kylaxium);
    public static final Block oreVellorium = new BlockStarforgeOre("vellorium_ore").setCorrespondingItem(ItemInit.vellorium);
    public static final Block oreIncadium = new BlockStarforgeOre("incadium_ore").setCorrespondingItem(ItemInit.incadium);
    public static final Block oreNoxerium = new BlockStarforgeOre("noxerium_ore").setCorrespondingItem(ItemInit.noxerium);
    public static final Block oreolysium = new BlockStarforgeOre("olysium_ore").setCorrespondingItem(ItemInit.olysium);
    public static final Block oreDetherium = new BlockStarforgeOre("detherium_ore").setCorrespondingItem(ItemInit.detherium);
    public static final Block oreXerovium = new BlockStarforgeOre("xerovium_ore").setCorrespondingItem(ItemInit.xerovium);
    public static final Block orePhytrosium = new BlockStarforgeOre("phytrosium_ore").setCorrespondingItem(ItemInit.phytrosium);
    public static final BlockConcentratedAcid concentratedAcid = new BlockConcentratedAcid("concentrated_acid", FluidInit.concentratedAcid, Material.field_151586_h);
    public static final Block acidBulbs = new BlockBasicPlant("acidbulbs", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block acidBulbsStem = new BlockBasicPlant("acidbulbs_stem", Material.field_151585_k);
    public static final Block fireLilly = new BlockBasicPlant("firelilly", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block caveVine = new BlockBasicPlant("cavevine", Material.field_151585_k);
    public static final Block deviantWeeds = new BlockBasicPlant("deviant_weeds", Material.field_151585_k);
    public static final Block glowingWeeds = new BlockBasicPlant("glowingweeds", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block crystalBlossoms = new BlockBasicPlant("crystalblossoms", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block crystalBlossomsStem = new BlockBasicPlant("crystalblossoms_stem", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block rockweeds = new BlockBasicPlant("rockweeds", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block slagDeposit = new BlockBasic("slagdeposit");
    public static final Block enghouledAstrorock = new BlockBasic("enghouled_astrorock").func_149715_a(0.5f);
    public static final Block neosteel = new BlockBasic("neosteel");
    public static final Block neosteelBeam = new BlockBasicPillar("neosteel_beam", Material.field_151573_f);
    public static final Block sunderwood = new BlockSunderLogs("sunderwood");
    public static final Block sunderwoodPlanks = new BlockBasicRotational("sunderwood_planks");
    public static final Block sunderleaves = new BlockBasicLight("sunderleaves");
    public static final Block plasterglass = new BlockBasicGlass("plasterglass");
    public static final Block forgefireLantern = new BlockBasicLight("forgefire_lantern");
    public static final Block acidLantern = new BlockBasicLight("acid_lantern");
    public static final Block astroRockStairs = new BlockBasicStairs("astrorock_stairs", 3.0f, astroRock.func_176223_P());
    public static final Block neosteelStairs = new BlockBasicStairs("neosteel_stairs", 3.0f, neosteel.func_176223_P());
    public static final Block acidicGel = new BlockAcidicGel("acidicgel", 3.0f, Material.field_151593_r);
    public static final Block fabricationBattery = new BlockBasicLight("fabrication_battery");
    public static final Block modulationBattery = new BlockBasicLight("modulation_battery");
    public static final Block unpoweredFabricationBattery = new BlockUnpoweredFabBattery("unpowered_fabrication_battery");
    public static final Block unpoweredModulationBattery = new BlockUnpoweredModulationBattery("unpowered_modulation_battery");
    public static final Block caveCrystalBlue = new BlockBasicGlass("cavecrystal_blue").func_149715_a(1.0f);
    public static final Block caveCrystalPink = new BlockBasicGlass("cavecrystal_pink").func_149715_a(1.0f);
    public static final Block pyrevines = new BlockBasicNoCollide("pyrevines", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block starforgeMineralInput = new BlockStarforgeInput("starforge_mineralinput");
    public static final Block starforgeDeclogger = new BlockStarforgeDeclogger("starforge_declogger");
    public static final Block fabricationTable = new BlockFabricationTable("fabrication_table");
    public static final Block modulationStation = new BlockModulator("modulator");
    public static final Block compressionTable = new BlockCompressionTable("compressiontable");
    public static final Block pickaxeChargingTable = new BlockBasicGui("pickchargingtable", GuiHandler.RegisteredGuis.PICKAXE_CHARGETABLE.getId());
    public static final Block trialGate = new BlockTrialGate("trialgate");
    public static final Block forgebloom = new BlockBasicPlant("forgebloom", Material.field_151585_k).func_149715_a(0.5f);
    public static final Block withergrass = new BlockBasicPlant("withergrass", Material.field_151585_k);
    public static final Block mossyAstrorock = new BlockBasic("mossy_astrorock");
    public static final Block astromud = new BlockBasic("astromud");
    public static final Block forgerock = new BlockBasicPlant("forgerock", Material.field_151576_e);
    public static final Block forgeStalactite = new BlockBasicPlant("forge_stalactite", Material.field_151576_e);
    public static final Block rockwormSpawner = new BlockBasicSpawner("spawner_rockworm", "rockworm");
    public static final Block chomperSpawner = new BlockBasicSpawner("spawner_chomper", "chomper");
    public static final Block eyeSlugSpawner = new BlockBasicSpawner("spawner_eye_slug", "eyeslug");
    public static final Block flutterfyreSpawner = new BlockBasicSpawner("spawner_flutterfyre", "flutterfyre");
    public static final Block gnawerSpawner = new BlockBasicSpawner("spawner_gnawer", "gnawer");
    public static final Block gravheadSpawner = new BlockBasicSpawner("spawner_gravhead", "gravhead");
    public static final Block hangerSpawner = new BlockBasicSpawner("spawner_hanger", "hanger");
    public static final Block hypnosaurSpawner = new BlockBasicSpawner("spawner_hypnosaur", "hypnosaur");
    public static final Block reflectalSpawner = new BlockBasicSpawner("spawner_reflectal", "reflectal");
    public static final Block ribrexSpawner = new BlockBasicSpawner("spawner_ribrex", "ribrex");
    public static final Block rockpestSpawner = new BlockBasicSpawner("spawner_rockpest", "rockpest");
    public static final Block screacherSpawner = new BlockBasicSpawner("spawner_screacher", "screacher");
    public static final Block spinovernSpawner = new BlockBasicSpawner("spawner_spinovern", "spinovern");
    public static final Block shimmerSpawner = new BlockBasicSpawner("spawner_shimmer", "shimmer");
    public static final Block spykerSpawner = new BlockBasicSpawner("spawner_spyker", "spyker");
    public static final Block clysterSpawner = new BlockBasicSpawner("spawner_clyster", "clyster");
    public static final Block hurlerSpawner = new BlockBasicSpawner("spawner_hurler", "hurler");
    public static final Block fyreweedSpawner = new BlockBasicSpawner("spawner_fyreweed", "fyreweed");
    public static final Block explosectSpawner = new BlockBasicSpawner("spawner_explosect", "explosect");
    public static final Block flurkySpawner = new BlockBasicSpawner("spawner_flurky", "flurky");
    public static final Block phaserSpawner = new BlockBasicSpawner("spawner_phaser", "phaser");
    public static final Block grapplerSpawner = new BlockBasicSpawner("spawner_grappler", "grappler");
    public static final Block crawkerSpawner = new BlockBasicSpawner("spawner_crawker", "crawker");
    public static final Block flapperSpawner = new BlockBasicSpawner("spawner_flapper", "flapper");
    public static final Block acidbackSpawner = new BlockBasicSpawner("spawner_acidback", "acidback");
    public static final Block labyrinthFloor = new BlockBasic("labyrinth_floor");
    public static final Block labyrinthGlassBlue = new BlockBasicGlass("labyrinth_glass_blue");
    public static final Block labyrinthGlassRed = new BlockBasicGlass("labyrinth_glass_red");
    public static final Block labyrinthLamp = new BlockBasicLight("labyrinth_lamp");
    public static final Block labyrinthMetalBlack = new BlockBasic("labyrinth_metal_black");
    public static final Block labyrinthMetalBlue = new BlockBasic("labyrinth_metal_blue");
    public static final Block crystallizedAstrorockBlue = new BlockBasic("astrorock_crystal_blue");
    public static final Block crystallizedAstrorockPink = new BlockBasic("astrorock_crystal_pink");
    public static final Block blueTentacle = new BlockBasicPillar("tentacle_blue");
    public static final Block purpleTentacle = new BlockBasicPillar("tentacle_purple");
    public static final Block pinkTentacle = new BlockBasicPillar("tentacle_pink");
    public static final Block blueTentacleEye = new BlockBasicPillar("tentacle_blue_eye");
    public static final Block purpleTentacleEye = new BlockBasicPillar("tentacle_purple_eye");
    public static final Block pinkTentacleEye = new BlockBasicPillar("tentacle_pink_eye");
    public static final Block watcherweeds = new BlockBasicPlant("watcherweeds", Material.field_151585_k);
    public static final Block watcherweedsTop = new BlockBasicPlant("watcherweeds_top", Material.field_151585_k);
    public static final Block blisterbulb = new BlockBasicPlant("blisterbulb", Material.field_151585_k);
    public static final Block doomglow = new BlockBasicPlant("doomglow", Material.field_151585_k).func_149715_a(0.75f);
    public static final Block crystalLily = new BlockBasicPlant("crystal_lily", Material.field_151585_k);
    public static final Block blazingDahilaStem = new BlockBasicPlant("blazing_dahila_stem", Material.field_151585_k);
    public static final Block blazingDahilaTop = new BlockBasicPlant("blazing_dahila_top", Material.field_151585_k);
    public static final Block astromolt = new BlockBasic("astromolt");
    public static final Block astromoltBubble = new BlockBasic("astromolt_bubble");
    public static final Block neosteelBlack = new BlockBasic("neosteel_black");
    public static final Block neocraftUnpowered = new BlockNeocraft("neocraft_unpowered");
    public static final Block neocraftGreen = new BlockNeocraft("neocraft_green");
    public static final Block neocraftPink = new BlockNeocraft("neocraft_pink");
    public static final Block neocraftYellow = new BlockNeocraft("neocraft_yellow");
    public static final Block neocraftBlue = new BlockNeocraft("neocraft_blue");
    public static final Block neocraftOrange = new BlockNeocraft("neocraft_orange");
    public static final Block neocraftGoalGreen = new BlockBasic("neocraft_goal_green");
    public static final Block neocraftGoalPink = new BlockBasic("neocraft_goal_pink");
    public static final Block neocraftGoalYellow = new BlockBasic("neocraft_goal_yellow");
    public static final Block neocraftGoalBlue = new BlockBasic("neocraft_goal_blue");
    public static final Block neocraftGoalOrange = new BlockBasic("neocraft_goal_orange");
    public static final Block gloopmotherSpawner = new BlockBasicSpawner("spawner_gloopmother", "gloopmother");
    public static final Block cyclosSpawner = new BlockBasicSpawner("spawner_cyclos", "cyclos");
    public static final Block clingerSpawner = new BlockBasicSpawner("spawner_clinger", "clinger");
    public static final Block labyrinthGeolocatorCore = new BlockGeolocator("labyrinth_geolocator_core", 4);
    public static final Block labyrinthGeolocatorBlue = new BlockGeolocator("labyrinth_geolocator_blue", 0);
    public static final Block labyrinthGeolocatorGreen = new BlockGeolocator("labyrinth_geolocator_green", 1);
    public static final Block labyrinthGeolocatorRed = new BlockGeolocator("labyrinth_geolocator_red", 2);
    public static final Block labyrinthGeolocatorYellow = new BlockGeolocator("labyrinth_geolocator_yellow", 3);
    public static final Block labyrinthChargerCore = new BlockChargeCore("labyrinth_charger_core", false);
    public static final Block labyrinthEternalCore = new BlockChargeCore("labyrinth_eternal_core", true);
    public static final Block labyrinthChargerLit = new BlockBasic("labyrinth_charger_lit");
    public static final Block labyrinthChargerUnpowered = new BlockUnpoweredCharger("labyrinth_charger_unpowered");
    public static final Block launchPad = new BlockBasic("launch_pad");
    public static final Block launchPadUnpowered = new BlockBasic("launch_pad_unpowered");
    public static final Block launchCore = new BlockLaunchCore("launch_core");
    public static final Block launchCoordinatorEmpty = new BlockLaunchCoordinator("launch_coordinator_empty", -1, -1);
    public static final Block launchCoordinatorBlue1 = new BlockLaunchCoordinator("launch_coordinator_blue_1", 1, 1);
    public static final Block launchCoordinatorBlue3 = new BlockLaunchCoordinator("launch_coordinator_blue_3", 1, 3);
    public static final Block launchCoordinatorBlue4 = new BlockLaunchCoordinator("launch_coordinator_blue_4", 1, 4);
    public static final Block launchCoordinatorBlue5 = new BlockLaunchCoordinator("launch_coordinator_blue_5", 1, 5);
    public static final Block launchCoordinatorPurple1 = new BlockLaunchCoordinator("launch_coordinator_purple_1", 2, 1);
    public static final Block launchCoordinatorPurple3 = new BlockLaunchCoordinator("launch_coordinator_purple_3", 2, 3);
    public static final Block launchCoordinatorPurple4 = new BlockLaunchCoordinator("launch_coordinator_purple_4", 2, 4);
    public static final Block launchCoordinatorPurple5 = new BlockLaunchCoordinator("launch_coordinator_purple_5", 2, 5);
    public static final Block launchCoordinatorGreen1 = new BlockLaunchCoordinator("launch_coordinator_green_1", 3, 1);
    public static final Block launchCoordinatorGreen3 = new BlockLaunchCoordinator("launch_coordinator_green_3", 3, 3);
    public static final Block launchCoordinatorGreen4 = new BlockLaunchCoordinator("launch_coordinator_green_4", 3, 4);
    public static final Block launchCoordinatorGreen5 = new BlockLaunchCoordinator("launch_coordinator_green_5", 3, 5);
    public static final Block launchCoordinatorRed1 = new BlockLaunchCoordinator("launch_coordinator_red_1", 4, 1);
    public static final Block launchCoordinatorRed3 = new BlockLaunchCoordinator("launch_coordinator_red_3", 4, 3);
    public static final Block launchCoordinatorRed4 = new BlockLaunchCoordinator("launch_coordinator_red_4", 4, 4);
    public static final Block launchCoordinatorRed5 = new BlockLaunchCoordinator("launch_coordinator_red_5", 4, 5);
    public static final Block championDungeonBrick = new BlockBasic("champion_dungeon_brick");
    public static final Block championDungeonPlating = new BlockBasic("champion_dungeon_plating");
    public static final Block championDungeonWindow = new BlockBasicGlass("champion_dungeon_window");
    public static final Block championDungeonSelector = new BlockDungeonSelector("champion_dungeon_selector");
    public static final Block championCarpetHunters = new BlockBasic("champion_carpet_hunters").func_149715_a(1.0f);
    public static final Block championSignalGreen = new BlockBasicLight("champion_signal_green");
    public static final Block championSignalRed = new BlockBasicLight("champion_signal_red");
    public static final Block championDoorClosed = new BlockBasic("champion_door_closed").func_149715_a(0.5f);
    public static final Block championDoorAjar = new BlockBasicGlass("champion_door_ajar").func_149715_a(0.25f);
    public static final Block championDoorOpen = new BlockBasicNoCollide("champion_door_open");
    public static final Block championLogoGold = new BlockBasic("champion_logo_gold");
    public static final Block championLogoPurple = new BlockBasic("champion_logo_purple");
    public static final Block championLogoCore = new BlockBasicGlass("champion_logo_core").func_149715_a(0.75f);
    public static final Block championEliminator = new BlockContestEliminator("champion_eliminator");
    public static final Block screenRedlight = new BlockContestGame("screen_redlight", 3);
    public static final Block screenLobbychanger = new BlockContestGame("screen_lobbychanger", -2);
    public static final Block screenBombers = new BlockContestGame("screen_bombers", 4);
    public static final Block championBayLight = new BlockBasicLight("champion_bay_light");
    public static final Block championCarpetHolodeckCut = new BlockBasicRotational("champion_carpet_holodeck_cut").func_149715_a(1.0f);
    public static final Block championCarpetHuntersCut = new BlockBasicRotational("champion_carpet_hunters_cut").func_149715_a(1.0f);
    public static final Block championCarpetRedlightCut = new BlockBasicRotational("champion_carpet_redlight_cut").func_149715_a(1.0f);
    public static final Block championCarpetBombersCut = new BlockBasicRotational("champion_carpet_bombers_cut").func_149715_a(1.0f);
    public static final Block championCarpetRedlight = new BlockBasic("champion_carpet_redlight").func_149715_a(1.0f);
    public static final Block championCarpetBombers = new BlockBasic("champion_carpet_bombers").func_149715_a(1.0f);
    public static final Block championDungeonBox = new BlockBasic("champion_dungeon_box");
    public static final Block augmentor = new BlockBasicGui("augmentor", GuiHandler.RegisteredGuis.AUGMENTOR.getId());
    public static final Block lumioRock = new BlockBasic("lumio_rock");
    public static final Block lumiolight = new BlockBasicGlass("lumilight").func_149715_a(1.0f);
    public static final Block lumglow = new BlockBasicPlant("lumglow", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block skyloom = new BlockBasicPlant("skyloom", Material.field_151585_k).func_149715_a(1.0f);
    public static final Block embergrass = new BlockBasicPlant("embergrass", Material.field_151585_k);
    public static final Block archlumioRock = new BlockBasicLight("archlumio_rock");
    public static final Block archlumiolight = new BlockBasicGlass("archlumilight").func_149715_a(1.0f);
    public static final Block archlumioGate = new BlockArchlumioGate("archlumio_gate").func_149715_a(1.0f);
    public static final Block blightlumioRock = new BlockBasic("blightlumio_rock");
    public static final Block blightcubes = new BlockBasicPlant("blightcubes", Material.field_151585_k);
    public static final Block lumcubes = new BlockBasicPlant("lumcubes", Material.field_151585_k);
    public static final Block logsArchblighted = new BlockBasicPillar("logs_archblighted");
    public static final Block lumioOreEmpty = new BlockBasic("lumio_ore_empty");
    public static final Block lumioOre = new BlockLuminescentOre("lumio_ore");
    public static final Block archgrass = new BlockBasicPlant("archgrass", Material.field_151585_k).func_149715_a(0.7f);
    public static final Block archvine = new BlockBasicTransparencyPlant("archvine", Material.field_151585_k).func_149715_a(0.7f);
    public static final Block leavesArchlum = new BlockLeavesArchlum("leaves_archlum").func_149715_a(1.0f);
    public static final Block logsArchlum = new BlockLogsArchlum("logs_archlum");
    public static final Block lumioIdolSummoner = new BlockEssenceIdol("lumio_idol_summoner");
    public static final Block augmenticonCreator = new BlockAugmenticonCreator("augmenticon_creator");
    public static final Block lumgrass = new BlockBasic("lumgrass");
    public static final Block archlumgrass = new BlockBasicLight("archlumgrass");
    public static final Block globroSpawner = new BlockBasicSpawner("spawner_globro", "globro");
    public static final Block globoonSpawner = new BlockBasicSpawner("spawner_globoon", "globoon");
    public static final Block glanglerSpawner = new BlockBasicSpawner("spawner_glangler", "glangler");
    public static final Block glochipperSpawner = new BlockBasicSpawner("spawner_glochipper", "glochipper");
    public static final Block galaxySporeBlue = new BlockBasicPlant("galaxy_spore_blue", Material.field_151585_k);
    public static final Block galaxyVineBlue = new BlockBasicPlant("galaxy_vine_blue", Material.field_151585_k);
    public static final Block galaxySporePink = new BlockBasicPlant("galaxy_spore_pink", Material.field_151585_k);
    public static final Block galaxyVinePink = new BlockBasicPlant("galaxy_vine_pink", Material.field_151585_k);
    public static final Block galaxySporeYellow = new BlockBasicPlant("galaxy_spore_yellow", Material.field_151585_k);
    public static final Block galaxyVineYellow = new BlockBasicPlant("galaxy_vine_yellow", Material.field_151585_k);
    public static final Block galaxySporeGreen = new BlockBasicPlant("galaxy_spore_green", Material.field_151585_k);
    public static final Block galaxyVineGreen = new BlockBasicPlant("galaxy_vine_green", Material.field_151585_k);
    public static final Block securityGateLevel1 = new BlockSecurityGate("security_gate_1", 0);
    public static final Block securityGateLevel2 = new BlockSecurityGate("security_gate_2", 1);
    public static final Block securityGateLevel3 = new BlockSecurityGate("security_gate_3", 2);
    public static final Block securityGateLevel4 = new BlockSecurityGate("security_gate_4", 3);
    public static final Block securityGateLevel5 = new BlockSecurityGate("security_gate_5", 4);
    public static final Block securityGateLevel6 = new BlockSecurityGate("security_gate_6", 5);
    public static final Block galaxyPortalHome = new BlockGalaxyPortal("galaxy_portal_home", 0);
    public static final Block galaxyPortalManu = new BlockGalaxyPortal("galaxy_portal_manu", 1);
    public static final Block galaxyPortalLumin = new BlockGalaxyPortal("galaxy_portal_lumin", 2);
    public static final Block galaxyPortalBlight = new BlockGalaxyPortal("galaxy_portal_blight", 4);
    public static final Block galaxyPortalMolten = new BlockGalaxyPortal("galaxy_portal_molten", 5);
    public static final Block galaxyPortalArch = new BlockGalaxyPortal("galaxy_portal_arc", 3);
    public static final Block neoLaserFieldLev1 = new BlockLaserField("neo_laserfield_1", 1);
    public static final Block neoLaserFieldLev2 = new BlockLaserField("neo_laserfield_2", 2);
    public static final Block neoLaserFieldLev3 = new BlockLaserField("neo_laserfield_3", 3);
    public static final Block neoLaserFieldLev4 = new BlockLaserField("neo_laserfield_4", 4);
    public static final Block neoLaserFieldLev5 = new BlockLaserField("neo_laserfield_5", 5);
    public static final Block blightedLeaves = new BlockBasicLight("leaves_blight");
    public static final Block radiantLeaves = new BlockBasicLight("leaves_radiant");
    public static final Block blightstocks = new BlockBasicPlant("blightstocks", Material.field_151585_k);
    public static final Block blightstocksTop = new BlockBasicPlant("blightstocks_top", Material.field_151585_k);
    public static final Block galaxyGulperSpawner = new BlockBasicSpawner("spawner_galaxy_gulper", "galaxygulper");
    public static final Block leavesMetalloid = new BlockBasic("leaves_metalloid");
    public static final Block logsMetalloid = new BlockMetalloidLogs("logs_metalloid");
    public static final Block hardenedAstrorock = new BlockBasic("astrorock_hardened");
    public static final Block caveCrystalRed = new BlockBasicGlass("cavecrystal_red").func_149715_a(0.5f);
    public static final Block ionBomb = new BlockBasicNoDrop("ion_bomb");
    public static final Block gloglobes = new BlockBasicCrop("gloglobes");
    public static final Block poweredCrystallizedSoil = new BlockBasicMoistured("crystallized_soil_powered", true);
    public static final Block unpoweredCrystallizedSoil = new BlockBasicMoistured("crystallized_soil_unpowered", false);
    public static final Block giantFlapperSpawaner = new BlockBasicSpawner("spawner_giantflapper", "giantflapper");
    public static final Block cloviniteOre = new BlockCloviniteOre("clovinite_ore");
    public static final Block labyrinthMetalRed = new BlockBasic("labyrinth_metal_red");
    public static final Block labyrinthLampBlue = new BlockBasicLight("labyrinth_lamp_blue");
    public static final Block labyrinthFloorRed = new BlockBasic("labyrinth_floor_red");
    public static final Block hyperMelderPowered = new BlockPoweredHyperMelder("hyper_melder_powered");
    public static final Block hyperGeneratorPowered = new BlockPoweredHyperGenerator("hyper_generator_powered");
    public static final Block hyperMelderUnpowered = new BlockUnpoweredHyperMelder("hyper_melder_unpowered");
    public static final Block hyperGeneratorUnpowered = new BlockUnpoweredHyperGenerator("hyper_generator_unpowered");
    public static final Block vectosectSpawaner = new BlockBasicSpawner("spawner_vectosect", "vectosect");
    public static final Block sticklerSpawaner = new BlockBasicSpawner("spawner_stickler", "stickler");
    public static final Block ravagerSpawner = new BlockBasicSpawner("spawner_ravager", "ravager");
    public static final Block myriteOre = new BlockMyriteOre("myrite_ore");
    public static final Block myriteOreDark = new BlockBasic("myrite_ore_dark");
    public static final List<Block> TRIGGER_BLOCKS = new ArrayList();
    public static final Block blockTrack = new BlockBasic("block_track").func_149715_a(0.5f);
    public static final Block blockTriggerCreeper = new BlockTrackTrigger("block_trigger_creeper", 0);
    public static final Block blockTriggerSkeleton = new BlockTrackTrigger("block_trigger_skeleton", 1);
    public static final Block blockTriggerStray = new BlockTrackTrigger("block_trigger_stray", 2);
    public static final Block blockTriggerPiglin = new BlockTrackTrigger("block_trigger_piglin", 3);
    public static final Block blockTriggerEnderman = new BlockTrackTrigger("block_trigger_enderman", 4);
    public static final Block blockTriggerSpider = new BlockTrackTrigger("block_trigger_spider", 5);
    public static final Block blockTriggerBlaze = new BlockTrackTrigger("block_trigger_blaze", 6);
    public static final Block blockTriggerDimtrader = new BlockTrackTrigger("block_trigger_dimtrader", 7);
    public static final Block blockTriggerMystery = new BlockTrackTrigger("block_trigger_mystery", 8);
    public static final Block blockTriggerIngot = new BlockTrackTrigger("block_trigger_ingot", 9);
    public static final Block blockTrackUsed = new BlockBasic("block_track_used").func_149715_a(0.5f);
    public static final Block blockTrackWin = new BlockBasicLight("block_track_win");
    public static final Block guideBlock = new BlockGuideBlock("guide_block");
    public static final Block guideStart = new BlockMazeCreator("guide_start");
    public static final Block guideButton = new BlockGuideButton("guide_button");
    public static final Block trackWall = new BlockBasic("track_wall");
    public static final Block labGameOrange = new BlockItemGame("lab_game_starter_orange");
    public static final Block nightvines = new BlockBasicPlant("nightvines", Material.field_151585_k);
    public static final Block nightvinesFlower = new BlockBasicPlant("nightvines_flower", Material.field_151585_k).func_149715_a(0.7f);
    public static final Block archbloomStem = new BlockBasicPlant("archbloom_stem", Material.field_151585_k);
    public static final Block blightbloomStem = new BlockBasicPlant("blightbloom_stem", Material.field_151585_k);
    public static final Block archbloom = new BlockBasicPlant("archbloom", Material.field_151585_k);
    public static final Block blightbloom = new BlockBasicPlant("blightbloom", Material.field_151585_k);
    public static final Block logsArchlumWrapped = new BlockBasicPillar("logs_archlum_wrapped");
    public static final List<Block> ITEM_CHALLENGE_BLOCKS = new ArrayList();
    public static final Block itemChallengeBlank = new BlockItemChallenge("item_challenge_blank", 0);
    public static final Block itemChallengeCollector = new BlockItemGameCollector("item_challenge_collector");
    public static final Block itemChallengeCrate = new BlockBasic("item_challenge_crate");
    public static final Block itemChallengeTongue = new BlockItemChallenge("item_challenge_tongue", 1);
    public static final Block itemChallengeFeather = new BlockItemChallenge("item_challenge_feather", 2);
    public static final Block itemChallengeEye = new BlockItemChallenge("item_challenge_eye", 3);
    public static final Block itemChallengeNightmare = new BlockItemChallenge("item_challenge_nightmare", 4);
    public static final Block itemChallengeSticky = new BlockItemChallenge("item_challenge_sticky", 5);
    public static final Block itemChallengeGloop = new BlockItemChallenge("item_challenge_gloop", 6);
    public static final Block itemChallengeBulb = new BlockItemChallenge("item_challenge_bulb", 7);
    public static final Block itemChallengeBranch = new BlockItemChallenge("item_challenge_branch", 8);
    public static final Block itemChallengeShadhide = new BlockItemChallenge("item_challenge_shadhide", 9);
    public static final Block itemChallengeHeavycrys = new BlockItemChallenge("item_challenge_heavycrys", 10);
    public static final Block itemChallengeDusker = new BlockItemChallenge("item_challenge_dusker", 11);
    public static final Block itemChallengeExplosac = new BlockItemChallenge("item_challenge_explosac", 12);
    public static final Block itemChallengeBone = new BlockItemChallenge("item_challenge_bone", 13);
    public static final Block itemChallengeMagstone = new BlockItemChallenge("item_challenge_magstone", 14);
    public static final Block itemChallengeSlime = new BlockItemChallenge("item_challenge_slime", 15);
    public static final Block itemChallengeReflective = new BlockItemChallenge("item_challenge_reflective", 16);
    public static final Block itemChallengeSpine = new BlockItemChallenge("item_challenge_spine", 17);
    public static final Block itemChallengeFangs = new BlockItemChallenge("item_challenge_fangs", 18);
    public static final Block itemChallengePolar = new BlockItemChallenge("item_challenge_polar", 19);
    public static final Block itemChallengeFuse = new BlockItemChallenge("item_challenge_fuse", 20);
    public static final Block dimensionalizer = new BlockDimensionalizer("dimensionalizer");
    public static final Block powerConnector = new BlockBasic("power_connector");
    public static final Block nightshyreSpawner = new BlockBasicSpawner("spawner_nightshyre", "nightshyre");
    public static final Block emberleaf = new BlockBasicCrop("emberleaf");
    public static final Block sunderwoodSap = new BlockSunderwoodSap("sunderwood_sap");
    public static final Block sunderwoodSapEmpty = new BlockSunderwoodSapEmpty("sunderwood_sap_empty");
    public static final Block giantFyreweedSpawner = new BlockBasicSpawner("spawner_giantfyreweed", "giantfyreweed");
    public static final Block bomberWallHard = new BlockBasic("bomber_wall_hard");
    public static final Block bomberWallSoft = new BlockBasic("bomber_wall_soft");
    public static final Block bomberWallFloor = new BlockBasicLight("bomber_wall_floor");
    public static final Block prismosisOre = new BlockPrismosisOre("prismosis_ore");
    public static final Block lightTileDark = new BlockLightTile("light_tile_dark");
    public static final Block lightTileLit = new BlockLightTile("light_tile_lit");
    public static final Block highPoweredCharger = new BlockLightTileGame("high_powered_charger");
    public static final Block lightTileRandomizer = new BlockLightTileGame("light_tile_randomizer");
    public static final Block glomiteSpawner = new BlockBasicSpawner("spawner_glomite", "glomite");
    public static final Block bombersPowerupSpeed = new BlockBombDeployerPowerup("bombers_powerup_speed", 0);
    public static final Block bombersPowerupSize = new BlockBombDeployerPowerup("bombers_powerup_size", 1);
    public static final Block bombersPowerupCooldown = new BlockBombDeployerPowerup("bombers_powerup_cooldown", 2);
    public static final Block bombersPowerupShield = new BlockBombDeployerPowerup("bombers_powerup_shield", 3);
    public static final Block bombersPowerupClosed = new BlockBasic("bombers_powerup_closed");
    public static final Block viralGrowth = new BlockViralGrowth("viral_growth");
    public static final Block blightgrass = new BlockBasicPlant("blightgrass", Material.field_151585_k);
    public static final Block blightvine = new BlockBasicTransparencyPlant("blightvine", Material.field_151585_k);
    public static final Block blightlumgrass = new BlockBasic("blightlumgrass");
    public static final Block blightvineRoot = new BlockBasicPlant("blightvine_root", Material.field_151585_k);
    public static final Block archvineRoot = new BlockBasicPlant("archvine_root", Material.field_151585_k);
    public static final Block chipFormatter = new BlockChipFormatter("chip_formatter");
    public static final Block chipFormatterPower = new BlockChipFormatterPower("chip_formatter_power");
    public static final Block factoryLantern = new BlockBasicLight("factory_lantern");
    public static final Block factory_chain = new BlockBasicPlant("factory_chain", Material.field_151573_f);
    public static final Block stripedSteelYellow = new BlockBasicPillar("striped_steel_yellow");
    public static final Block neosteelPowerBeam = new BlockBasicPillar("neosteel_power_beam").func_149715_a(1.0f);
    public static final Block cellularOre = new BlockCellularOre("cellular_ore");
    public static final Block alienSlide0 = new BlockAlienSlide("slide_puzzle_alien_0");
    public static final Block alienSlide1 = new BlockAlienSlide("slide_puzzle_alien_1");
    public static final Block alienSlide2 = new BlockAlienSlide("slide_puzzle_alien_2");
    public static final Block alienSlide3 = new BlockAlienSlide("slide_puzzle_alien_3");
    public static final Block alienSlide4 = new BlockAlienSlide("slide_puzzle_alien_4");
    public static final Block alienSlide5 = new BlockAlienSlide("slide_puzzle_alien_5");
    public static final Block alienSlide6 = new BlockAlienSlide("slide_puzzle_alien_6");
    public static final Block alienSlide7 = new BlockAlienSlide("slide_puzzle_alien_7");
    public static final Block alienSlide8 = new BlockAlienSlide("slide_puzzle_alien_8");
    public static final Block alienSlide9 = new BlockAlienSlide("slide_puzzle_alien_9");
    public static final Block alienSlide10 = new BlockAlienSlide("slide_puzzle_alien_10");
    public static final Block alienSlide11 = new BlockAlienSlide("slide_puzzle_alien_11");
    public static final Block alienSlide12 = new BlockAlienSlide("slide_puzzle_alien_12");
    public static final Block alienSlide13 = new BlockAlienSlide("slide_puzzle_alien_13");
    public static final Block alienSlide14 = new BlockAlienSlide("slide_puzzle_alien_14");
    public static final Block alienSlide15 = new BlockAlienSlide("slide_puzzle_alien_15");
    public static final Block alienSlide16 = new BlockAlienSlide("slide_puzzle_alien_16");
    public static final Block alienSlide17 = new BlockAlienSlide("slide_puzzle_alien_17");
    public static final Block alienSlide18 = new BlockAlienSlide("slide_puzzle_alien_18");
    public static final Block alienSlide19 = new BlockAlienSlide("slide_puzzle_alien_19");
    public static final Block alienSlide20 = new BlockAlienSlide("slide_puzzle_alien_20");
    public static final Block alienSlide21 = new BlockAlienSlide("slide_puzzle_alien_21");
    public static final Block alienSlide22 = new BlockAlienSlide("slide_puzzle_alien_22");
    public static final Block alienSlide23 = new BlockAlienSlide("slide_puzzle_alien_23");
    public static final Block alienSlide24 = new BlockAlienSlide("slide_puzzle_alien_24");
    public static final Block factoryFloor = new BlockBasic("factory_floor");
    public static final Block factoryScaffold = new BlockBasicPlant("factory_scaffold", Material.field_151573_f);
    public static final Block factoryPlatformHalf = new BlockBasicSlab.Half("factory_platform_half", Material.field_151573_f);
    public static final Block factoryCrate = new BlockBasic("factory_crate");
    public static final Block rockslugSpawner = new BlockBasicSpawner("spawner_rockslug", "rockslug");
    public static final Block giantRockslugSpawner = new BlockBasicSpawner("spawner_giant_rockslug", "giant_rockslug");
    public static final Block fluterbeeSpawner = new BlockBasicSpawner("spawner_flutterbee", "flutterbee");
    public static final Block lightSwitchOn = new BlockLightSwitch("light_switch_on");
    public static final Block lightSwitchOff = new BlockLightSwitch("light_switch_off");
    public static final Block lightSwitchGame = new BlockLightSwitchGame("light_switch_game");
    public static final Block switchableLightOn = new BlockBasicLight("switchable_light_on");
    public static final Block switchableLightOff = new BlockBasic("switchable_light_off");
    public static final Block pinkTentacleEyeEmpty = new BlockTentacleEyePinkEmpty("tentacle_eye_empty_pink");
    public static final Block blueTentacleEyeEmpty = new BlockTentacleEyeBlueEmpty("tentacle_eye_empty_blue");
    public static final Block purpleTentacleEyeEmpty = new BlockTentacleEyePurpleEmpty("tentacle_eye_empty_purple");
    public static final Block whackBlockUnpowered = new BlockWhack("whack_block_unpowered");
    public static final Block whackBlockLit = new BlockWhack("whack_block_lit");
    public static final Block whackGame = new BlockWhackGame("whack_game", false);
    public static final Block hivenite = new BlockHiveniteOre("hivenite_ore");
    public static final Block hiveniteEmpty = new BlockEmptyHiveniteOre("hivenite_empty");
    public static final Block beeHive = new BlockBasic("bee_hive").func_149715_a(0.5f);
    public static final Block honeyGel = new BlockBasicGlass("honey_gel").func_149715_a(0.5f);
    public static final Block honeyGelEmpty = new BlockEmptyHoneyGel("honey_gel_empty");
    public static final Block sapEvaporator = new BlockSapEvaporator("sap_evaporator", false);
    public static final Block connectBlock = new BlockBasic("connect_block");
    public static final Block connectButton = new BlockConnectButton("connect_button");
    public static final Block connectBlockYellow = new BlockBasic("connect_block_yellow");
    public static final Block connectBlockRed = new BlockBasic("connect_block_red");
    public static final Block connectGame = new BlockConnectGame("connect_game", false);
    public static final Block screenDuel = new BlockContestGame("screen_duel", 5);
    public static final Block championLauncher = new BlockBasic("champion_launcher");
    public static final Block championFountainTrap = new BlockBasic("champion_fountain_trap");
    public static final Block championHeatTrap = new BlockBasicBoolState("champion_heat_trap");
    public static final Block championCarpetDuel = new BlockBasicLight("champion_carpet_duel");
    public static final Block championCarpetDuelCut = new BlockBasicRotational("champion_carpet_duel_cut").func_149715_a(1.0f);
    public static final Block mutantBloom = new BlockBasicPlant("mutant_bloom", Material.field_151585_k).func_149715_a(0.5f);
    public static final Block championStrobeSync1 = new BlockBasicLight("champion_strobe_sync1");
    public static final Block championStrobeSync2 = new BlockBasicLight("champion_strobe_sync2");
    public static final Block championStrobeSync3 = new BlockBasicLight("champion_strobe_sync3");
    public static final Block championStrobeSync4 = new BlockBasicLight("champion_strobe_sync4");
    public static final Block championStrobeSync5 = new BlockBasicLight("champion_strobe_sync5");
    public static final Block serpentineOre = new BlockSerpentineOre("serpentine_ore");
    public static final Block pipeCross = new BlockPipe("pipe_cross");
    public static final Block pipeElbow = new BlockPipe("pipe_elbow");
    public static final Block pipeT = new BlockPipe("pipe_t");
    public static final Block pipeL = new BlockPipe("pipe_l");
    public static final Block pipeCrossLit = new BlockPipe("pipe_cross_lit");
    public static final Block pipeElbowLit = new BlockPipe("pipe_elbow_lit");
    public static final Block pipeTLit = new BlockPipe("pipe_t_lit");
    public static final Block pipeLLit = new BlockPipe("pipe_l_lit");
    public static final Block pipeGame = new BlockPipeGame("pipe_game", false);
    public static final Block pipeNone = new BlockPipe("pipe_none");
    public static final Block leavesDarkborn = new BlockBasic("leaves_darkborn");
    public static final Block gorgerSpawner = new BlockBasicSpawner("spawner_gorger", "gorger");
    public static final Block doublejawSpawner = new BlockBasicSpawner("spawner_doublejaw", "doublejaw");
    public static final Block minimiteSpawner = new BlockBasicSpawner("spawner_minimite", "minimite");
    public static final Block dripplerSpawner = new BlockBasicSpawner("spawner_drippler", "drippler");
    public static final Block clusterweedSpawner = new BlockBasicSpawner("spawner_clusterweed", "clusterweed");
    public static final Block wispSpawner = new BlockBasicSpawner("spawner_wisp", "wisp");
    public static final Block crusherSpawner = new BlockBasicSpawner("spawner_crusher", "crusher");
    public static final Block tetherbugSpawner = new BlockBasicSpawner("spawner_tetherbug", "tetherbug");
    public static final Block logsNitro = new BlockLogsNitro("logs_nitro");
    public static final Block leavesNitro = new BlockLeavesNitro("leaves_nitro").func_149715_a(1.0f);
    public static final Block containmentGate = new BlockContainmentGate("containment_gate");
    public static final Block archlumioGatePass = new BlockArchlumioGatePass("archlumio_gate_pass").func_149715_a(1.0f);
    public static final Block gloominessenceOre = new BlockGloominessenceOre("gloominessence_ore");
    public static final Block gloominessenceOreEmpty = new BlockBasic("gloominessence_ore_empty");
    public static final Block blightEye = new BlockBlightEyeBattery("blight_eye");
    public static final Block blightEyeEmpty = new BlockBlightEyeSocket("blight_eye_empty");
    public static final Block blightMouth = new BlockBasic("blight_mouth");
    public static final Block blightIdolSummoner = new BlockGloomIdol("blight_idol_summoner");
    public static final Block mainPowerTerminal = new BlockMainPowerTerminal("main_power_terminal");
    public static final Block powerGenerator = new BlockPowerGenerator("power_generator");
    public static final Block cellContainer3 = new BlockCellContainer("cell_container_3", 3);
    public static final Block cellContainer5 = new BlockCellContainer("cell_container_5", 5);
    public static final Block cellContainer7 = new BlockCellContainer("cell_container_7", 7);
    public static final Block cellContainer9 = new BlockCellContainer("cell_container_9", 9);
    public static final Block cellGame = new BlockCellGame("cell_game");
    public static final Block weaverWeb = new BlockWeaverWeb("weaver_web");
    public static final Block weaverSpawner = new BlockBasicSpawner("spawner_weaver", "weaver");
    public static final Block vilebulbSpawner = new BlockBasicSpawner("spawner_vilebulb", "vilebulb");
    public static final Block sightwalkerSpawner = new BlockBasicSpawner("spawner_sightwalker", "sightwalker");
    public static final Block grubberSpawner = new BlockBasicSpawner("spawner_grubber", "grubber");
    public static final Block blisterweedSpawner = new BlockBasicSpawner("spawner_blisterweed", "blisterweed");
    public static final Block doomdogSpawner = new BlockBasicSpawner("spawner_doomdog", "doomdog");
    public static final Block auradineOre = new BlockAuradineOre("auradine_ore");
    public static final Block phototenzyteOre = new BlockPhototenzyteOre("phototenzyte_ore");
    public static final Block target = new BlockTarget("target");
    public static final Block rhythmGame = new BlockRhythmGame("rhythm_game", false);
    public static final Block rhythmButton = new BlockRhythmButton("rhythm_button");
    public static final Block rhythmTile = new BlockRhythmTile("rhythm_tile");
    public static final Block rotatableTile = new BlockRotatableTile("rotatable_tile");
    public static final Block rotatableTileGame = new BlockRotatableTileGame("rotatable_tile_game", false);
    public static final Block nicroniumInfuser = new BlockNicroniumInfuser("nicronium_infuser", false);
    public static final Block incandesciteOre = new BlockIncandesciteOre("incandescite_ore");
    public static final Block equivine = new BlockCappedPlant("equivine");
    public static final Block strangleweed = new BlockCappedPlant("strangleweed");
    public static final Block shiverglow = new BlockCappedPlant("shiverglow");
    public static final Block acidPocket = new BlockAcidPocket("acid_pocket");
    public static final Block titanopodSpawner = new BlockBasicSpawner("spawner_titanopod", "titanopod");
    public static final Block flashflySpawner = new BlockBasicSpawner("spawner_flashfly", "flashfly");
    public static final Block snapperSpawner = new BlockBasicSpawner("spawner_snapper", "snapper");
    public static final Block leerSpawner = new BlockBasicSpawner("spawner_leer", "leer");
    public static final Block terrorflySpawner = new BlockBasicSpawner("spawner_terrorfly", "terrorfly");
    public static final Block championCarpetTargets = new BlockBasicLight("champion_carpet_targets");
    public static final Block championCarpetTargetsCut = new BlockBasicRotational("champion_carpet_targets_cut").func_149715_a(1.0f);
    public static final Block screenTargets = new BlockContestGame("screen_targets", 7);
    public static final Block lightBridge = new BlockLightBridge("light_bridge");
    public static final Block crystalDeposit = new BlockBasicTransparencyPlant("crystal_deposit", Material.field_151592_s).func_149715_a(0.5f);
    public static final Block rowSlideGame = new BlockRowSlideGame("row_slide_game");
    public static final Block rowSlideButton = new BlockRowSlideButton("row_slide_button");
    public static final Block rowSlideTile = new BlockRowSlideTile("row_slide_tile");
    public static final Block rowToggleTile = new BlockBasicBoolState("row_toggle_tile");
    public static final Block rowToggleButton = new BlockRowToggleButton("row_toggle_button");
    public static final Block rowToggleGame = new BlockRowToggleGame("row_toggle_game");
    public static final Block rowIncrementTile = new BlockRowIncrementTile("row_increment_tile");
    public static final Block rowIncrementButton = new BlockRowIncrementButton("row_increment_button");
    public static final Block rowIncrementGame = new BlockRowIncrementGame("row_increment_game");
    public static final Block championCarpetLightbridge = new BlockBasicLight("champion_carpet_lightbridge");
    public static final Block screenLightbridge = new BlockContestGame("screen_lightbridge", 6);
    public static final Block championCarpetLightbridgeCut = new BlockBasicRotational("champion_carpet_lightbridge_cut").func_149715_a(1.0f);
    public static final Block puffSpore = new BlockBasicPlant("puff_spore", Material.field_151585_k).func_149715_a(0.5f);
    public static final Block mushweed = new BlockCappedPlant("mushweed");
    public static final Block fungalAstromud = new BlockBasic("fungal_astromud");
    public static final Block fungalAstrorock = new BlockBasic("fungal_astrorock");
    public static final Block lightEmitter = new BlockLightEmitter("light_emitter");
    public static final Block lightReflector = new BlockLightReflector("light_reflector");
    public static final Block galaxyGate = new BlockGalaxyGate("galaxy_gate");
    public static final Block lightReceiver = new BlockLightReceiver("light_receiver");
    public static final Block neoshocker = new BlockNeoshocker("neoshocker");
    public static final Block galacticChallenge = new BlockGalaxyChallenge("galactic_challenge");
    public static final Block fungalBlockage = new BlockFungalBlockage("fungal_blockage");
    public static final Block forgeshroomPurple = new BlockBasicLight("forgeshroom_purple");
    public static final Block forgeshroomGreen = new BlockBasicLight("forgeshroom_green");
    public static final Block forgeshroomRed = new BlockBasicLight("forgeshroom_red");
    public static final Block forgeshroomBlue = new BlockBasicLight("forgeshroom_blue");
    public static final Block forgeshroomYellow = new BlockBasicLight("forgeshroom_yellow");
    public static final Block forgeshroomStem = new BlockBasicPillar("forgeshroom_stem");
    public static final Block terrorGlow = new BlockTerrorGlow("terror_glow");
    public static final Block crusherButton = new BlockCrusherButton("crusher_button");
    public static final Block spacePickle = new BlockBasicCrop("space_pickle");
    public static final Block duskerSpawner = new BlockBasicSpawner("spawner_dusker", "dusker");
    public static final Block tentaclonSpawner = new BlockBasicSpawner("spawner_tentaclon", "tentaclon");
    public static final Block portalNode = new BlockPortalNode("portal_node");
    public static final Block portalNexus = new BlockPortalNexus("portal_nexus");
    public static final Block chromaTile = new BlockChromaTile("chroma_tile");
    public static final Block chromaGame = new BlockChromaGame("chroma_game");
    public static final Block alignmentTile = new BlockAlignmentTile("alignment_tile");
    public static final Block alignmentDialGame = new BlockAlignmentDialGame("alignment_dial_game");
    public static final Block murksoil = new BlockBasic("murksoil");
    public static final Block murkdirt = new BlockBasic("murkdirt");
    public static final Block murkstone = new BlockBasic("murkstone");
    public static final Block logsMurk = new BlockMurkLogs("logs_murk");
    public static final Block leavesMurk = new BlockBasic("leaves_murk");
    public static final Block murkglass = new BlockBasicGlass("murkglass");
    public static final Block metaMaterializer = new BlockMetaMaterializer("meta_materializer");
    public static final Block leavesRebirth = new BlockBasicGlass("leaves_rebirth");
    public static final Block emberslagDeposit = new BlockEmberslagDeposit("emberslag_deposit");
    public static final Block emberslag = new BlockEmberslag("emberslag");
    public static final Block darksteelOre = new BlockDarksteelOre("darksteel_ore");
    public static final Block fabricReformulator = new BlockBasic("fabric_reformulator");
    public static final Block exothermiteOre = new BlockExothermiteOre("exothermite_ore");
    public static final Block ringGame = new BlockRingGame("ring_game");
    public static final Block ringTile = new BlockRingTile("ring_tile");
    public static final Block ringSlideButton = new BlockRingSlideButton("ring_slide_button");
    public static final Block synchroniteSignal = new BlockSynchroniteSignal("synchronite_signal");
    public static final Block synchroniteOre = new BlockSynchroniteOre("synchronite_ore");
    public static final Block lurcherSpawner = new BlockBasicSpawner("spawner_lurcher", "lurcher");
    public static final Block murkice = new BlockBasicGlass("murkice");
    public static final Block murkcore = new BlockBasic("murkcore");
    public static final Block murkplanks = new BlockBasic("murkplanks");
    public static final Block murkbricks = new BlockBasic("murkbricks");
    public static final Block igneousMurkstone = new BlockBasic("igneous_murkstone");
    public static final Block murkplankStairs = new BlockBasicStairs("murkplank_stairs", 3.0f, murkplanks.func_176223_P());
    public static final Block murkbrickStairs = new BlockBasicStairs("murkbrick_stairs", 3.0f, murkbricks.func_176223_P());
    public static final Block murkplankHalf = new BlockBasicSlab.Half("murkplank_half", Material.field_151575_d);
    public static final Block murkbrickHalf = new BlockBasicSlab.Half("murkbrick_half", Material.field_151576_e);
    public static final Block battleSnake = new BlockBattleSnake("battle_snake");
    public static final Block snakeGuideRight = new BlockSnakeGuide("snake_guide_right");
    public static final Block snakeGuideLeft = new BlockSnakeGuide("snake_guide_left");
    public static final Block battleSnakePowerup = new BlockBattleSnakePowerup("battle_snake_powerup");
    public static final Block battleSnakeHead = new BlockBattleSnakeHead("battle_snake_head");
    public static final Block screenBattlesnakes = new BlockContestGame("screen_battlesnakes", 8);
    public static final Block championCarpetBattlesnakes = new BlockBasicLight("champion_carpet_battlesnakes");
    public static final Block championCarpetBattlesnakesCut = new BlockBasicRotational("champion_carpet_battlesnakes_cut").func_149715_a(1.0f);
    public static final Block championGlassDark = new BlockBasicGlass("champion_glass_dark");
    public static final Block championWall = new BlockBasic("champion_wall");
    public static final Block voidVacuum = new BlockVoidVacuum("void_vacuum");
    public static final Block labyrinthPortalGreen = new BlockLabPortal("labyrinth_portal_green", 1);
    public static final Block labyrinthPortalRed = new BlockLabPortal("labyrinth_portal_red", 0);
    public static final Block labyrinthLampGreen = new BlockBasicLight("labyrinth_lamp_green");
    public static final Block labyrinthGlassGreen = new BlockBasicGlass("labyrinth_glass_green");
    public static final Block labyrinthFloorPurple = new BlockBasic("labyrinth_floor_purple");
    public static final Block labyrinthMetalPurple = new BlockBasic("labyrinth_metal_purple");
    public static final Block timelineStabilizerConsole = new BlockTimelineStabilizerConsole("timeline_stabilizer_console");
    public static final Block timelineStabilizerArrow = new BlockTimelineStabilizerArrow("timeline_stabilizer_arrow");
    public static final Block timelineStabilizerPortal = new BlockTimelineStabilizerPortal("timeline_stabilizer_portal");
    public static final Block timelineStabilizerGoal = new BlockBasic("timeline_stabilizer_goal");
    public static final Block timelineStabilizerCapsule = new BlockBasic("timeline_stabilizer_capsule");
    public static final Block voidFlower = new BlockVoidFlower("void_flower");
    public static final Block leavesCelestialPurple = new BlockCelestialLogsPurple("leaves_celestial_purple");
    public static final Block logsCelestialPurple = new BlockBasicLight("logs_celestial_purple");
    public static final Block natSpawner = new BlockBasicSpawner("spawner_nat", "nat");
    public static final Block sentrySpawner = new BlockBasicSpawner("spawner_sentry", "sentry");
    public static final Block moonFlower = new BlockBasicCrop("moon_flower");
    public static final Block riftEntangledTile = new BlockRiftEntangledTile("rift_entangled_tile");
    public static final Block tentacleSynthesizer = new BlockRemoteControl("tentacle_synthesizer");
    public static final Block snarlvine = new BlockBasicPlant("snarlvine", Material.field_151585_k);
    public static final Block leavesSnarl = new BlockBasic("leaves_snarl");
    public static final Block championCarpetLaserwarz = new BlockBasicLight("champion_carpet_laserwarz");
    public static final Block championCarpetLaserwarzCut = new BlockBasicRotational("champion_carpet_laserwarz_cut").func_149715_a(1.0f);
    public static final Block screenLaserwarz = new BlockContestGame("screen_laserwarz", 9);
    public static final Block catatoniteOre = new BlockCatatoniteOre("catatonite_ore");
    public static final Block neonBricksRed = new BlockBasic("neon_bricks_red").func_149715_a(0.3f);
    public static final Block neonBricksPurple = new BlockBasic("neon_bricks_purple").func_149715_a(0.3f);
    public static final Block neonBricksPink = new BlockBasic("neon_bricks_pink").func_149715_a(0.3f);
    public static final Block neonBricksBlue = new BlockBasic("neon_bricks_blue").func_149715_a(0.3f);
    public static final Block neonBricksAqua = new BlockBasic("neon_bricks_aqua").func_149715_a(0.3f);
    public static final Block neonBricksOrange = new BlockBasic("neon_bricks_orange").func_149715_a(0.3f);
    public static final Block neonBricksGreen = new BlockBasic("neon_bricks_green").func_149715_a(0.3f);
    public static final Block neonBricksYellow = new BlockBasic("neon_bricks_yellow").func_149715_a(0.3f);
    public static final Block leavesLumio = new BlockBasicGlass("leaves_lumio").func_149715_a(1.0f);
    public static final Block spawnerOrbiter = new BlockBasicSpawner("spawner_orbiter", "orbiter");
    public static final Block bumblefruit = new BlockBasicPlant("bumblefruit", Material.field_151585_k).func_149715_a(0.5f);
    public static final Block ancientSymbol = new BlockAncientSymbol("ancient_symbol");
    public static final Block ancientSymbolInterpreter = new BlockAncientSymbolInterpreter("ancient_symbol_interpreter");
    public static final Block darkworldConverter = new BlockRemoteControl("darkworld_converter");
    public static final Block glowingIgneousMurkstone = new BlockBasicLight("glowing_igneous_murkstone");
    public static final Block multiversiteOverworld = new BlockMultiversiteOverworld("multiversite_overworld");
    public static final Block multiversiteMurk = new BlockMultiversiteMurk("multiversite_murk");
    public static final Block powerNodule = new BlockPowerNodule("power_nodule");
    public static final Block powerConduit = new BlockPowerConduit("power_conduit");
    public static final Block powerCollider = new BlockPowerCollider("power_collider");
    public static final Block powerColliderTrack = new BlockPowerColliderTrack("power_collider_track");
    public static final Block ioniteOre = new BlockIoniteOre("ionite_ore");
    public static final Block moduleCreator = new BlockBasicGui("module_creator", GuiHandler.RegisteredGuis.MODULE_CREATOR.getId());
    public static final Block smoothCoral = new BlockCoral("smooth_coral");
    public static final Block roughCoral = new BlockCoral("rough_coral");
    public static final Block seastone = new BlockBasic("seastone");
    public static final Block seasand = new BlockBasic("seasand");
    public static final Block sandySeastone = new BlockBasic("sandy_seastone");
    public static final Block rainfallGenerator = new BlockRainfallGenerator("rainfall_generator");
    public static final Block darkRoughCoral = new BlockCoral("dark_rough_coral");
    public static final Block lightSmoothCoral = new BlockCoral("light_smooth_coral");
    public static final Block patternedSmoothCoral = new BlockCoral("patterned_smooth_coral");
    public static final Block superRoughCoral = new BlockCoral("super_rough_coral");
    public static final Block kelp = new BlockBasicPlant("kelp", Material.field_151585_k);
    public static final Block denseKelp = new BlockBasicPlant("dense_kelp", Material.field_151585_k);
    public static final Block seabush = new BlockBasicPlant("seabush", Material.field_151585_k);
    public static final Block searock = new BlockBasicPlant("searock", Material.field_151576_e);
    public static final Block wiggleweed = new BlockCappedPlant("wiggleweed");
    public static final Block fishChow = new BlockFishChow("fish_chow");
    public static final Block atomiteOre = new BlockAtomiteOre("atomite_ore");
    public static final Block acidicConcoctionGel = new BlockAcidicConcoctionGel("acidic_concoction_gel", 3.0f, Material.field_151593_r);
    public static final Block weldingChamber = new BlockWeldingChamber("welding_chamber");
    public static final Block separatedMatter = new BlockSeparatedMatter("separated_matter");
    public static final Block championCarpetParkour = new BlockBasicLight("champion_carpet_parkour");
    public static final Block championCarpetDodgeball = new BlockBasicLight("champion_carpet_dodgeball");
    public static final Block championCarpetDodgeballCut = new BlockBasicRotational("champion_carpet_dodgeball_cut").func_149715_a(1.0f);
    public static final Block championCarpetParkourCut = new BlockBasicRotational("champion_carpet_parkour_cut").func_149715_a(1.0f);
    public static final Block screenParkour = new BlockContestGame("screen_parkour", 10);
    public static final Block screenDodgeball = new BlockContestGame("screen_dodgeball", 11);
    public static final Block championGlowingTile = new BlockGlowingTile("champion_glowing_tile");
    public static final Block parkourPlatform = new BlockParkourPlatform("parkour_platform");
    public static final Block parkourPlatformSlippery = new BlockParkourPlatformSlippery("parkour_platform_slippery");
    public static final Block fusionTable = new BlockFusionTable("fusion_table");
    public static final Block cosmicFracture = new BlockCosmicFracture("cosmic_fracture", 3.0f, Material.field_151593_r);
    public static final Block monomerDeposit = new BlockMonomerDeposit("monomer_deposit");
    public static final Block polymerizationDevice = new BlockPolymerizationDevice("polymerization_device");
    public static final Block monomerCube = new BlockMonomerCube("monomer_cube");
    public static final Block fossilCombiner = new BlockBasicGui("fossil_combiner", GuiHandler.RegisteredGuis.FOSSIL_COMBINER.getId());
    public static final Block microRocket = new BlockRemoteControl("micro_rocket");
    public static final Block radionOre = new BlockRadionOre("radion_ore");
    public static final Block radionPillar = new BlockRadionPillar("radion_pillar");
    public static final Block fossilTrack = new BlockFossilTrack("fossil_track", 3.0f, Material.field_151593_r);
    public static final Block screenArcheologist = new BlockContestGame("screen_archeologist", -3);
    public static final Block nebulousBeacon = new BlockNebulousBeacon("nebulous_beacon");
    public static final Block melodyButton = new BlockMelodyButton("melody_button");
    public static final Block melodicSequencer = new BlockMelodicSequencer("melodic_sequencer");
    public static final Block circuitCalibrator = new BlockCircuitCalibrator("circuit_calibrator");
    public static final Block circuitMonitor = new BlockCircuitMonitor("circuit_monitor");
    public static final Block igneousPearlOre = new BlockIgneousPearlOre("igneous_pearl_ore");
    public static final Block heatsand = new BlockBasic("heatsand");
    public static final Block moltenSeastone = new BlockBasic("molten_seastone");
    public static final Block igneousSeastone = new BlockBasic("igneous_seastone");
    public static final Block moltrock = new BlockBasicPlant("moltrock", Material.field_151576_e);
    public static final Block heatweed = new BlockCappedPlant("heatweed");
    public static final Block smokeweed = new BlockCappedPlant("smokeweed");
    public static final Block emberkelp = new BlockCappedPlant("emberkelp");
    public static final Block seaClay = new BlockSeaClay("sea_clay");
    public static final Block moldedSeaClay = new BlockMoldedSeaClay("molded_sea_clay");
    public static final Block selectionPreview = new BlockBasicNoCollide("selection_preview");
    public static final Block navigationNodule = new BlockNavigationNodule("navigation_nodule");
    public static final Block navigationDevice = new BlockNavigationDevice("navigation_device");
    public static final Block neocraftingStation = new BlockNeocraftingStation("neocrafting_station");
    public static final Block puzzleMasterTurret = new BlockBasicBoolState("puzzle_master_turret");
    public static final Block puzzleArenaFloor = new BlockPuzzleArenaFloor("puzzle_arena_floor");
    public static final Block puzzleKeyBlock = new BlockPuzzleKey("puzzle_key_block");
    public static final Block puzzleLava = new BlockPuzzleLava("puzzle_lava");
    public static final Block chemistryTable = new BlockChemistryTable("chemistry_table");
    public static final Block nuclearBomb = new BlockBasicNoDrop("nuclear_bomb");
    public static final Block present = new BlockPresent("present");
    public static final Block inkableFloor = new BlockInkable("inkable_floor");
    public static final Block championCarpetInkwars = new BlockBasicLight("champion_carpet_inkwars");
    public static final Block championCarpetInkwarsCut = new BlockBasicRotational("champion_carpet_inkwars_cut").func_149715_a(1.0f);
    public static final Block screenInkwars = new BlockContestGame("screen_inkwars", 12);
    public static final Block screenChemist = new BlockContestGame("screen_chemist", -4);
    public static final Block neocraftGoalEmpty = new BlockBasic("neocraft_goal_empty");
    public static final Block teslaTower = new BlockTeslaTower("tesla_tower");
    public static final Block eternalBeacon = new BlockEternalBeacon("eternal_beacon");
    public static final Block shipmentFiller = new BlockShipmentFiller("shipment_filler", Material.field_151576_e, TabsInit.TAB_AUXMATS);
    public static final Block drillControl = new BlockDrillControl("drill_control");
    public static final Block drillConsole = new BlockDrillConsole("drill_console");
    public static final Block drillBeam = new BlockBasic("drill_beam");
    public static final Block drillShaft = new BlockBasic("drill_shaft");
    public static final Block drillHead = new BlockBasic("drill_head");
    public static final Block lucientOre = new BlockLucientOre("lucient_ore");
    public static final Block deconstructor = new BlockDeconstructor("deconstructor", Material.field_151573_f, TabsInit.TAB_AUXMATS);
    public static final Block treadmillTrack = new BlockTreadmillTrack("treadmill_track");
    public static final Block fungalAstromudBlue = new BlockBasic("fungal_astromud_blue");
    public static final Block fungalAstromudTeal = new BlockBasic("fungal_astromud_teal");
    public static final Block azureRoot = new BlockAzureLeaf("azure_root");
    public static final Block glowvine = new BlockBasicPlant("glowvine", Material.field_151585_k).func_149715_a(0.5f);
    public static final Block darkvine = new BlockBasicPlant("darkvine", Material.field_151585_k);
    public static final Block strangelash = new BlockCappedPlant("strangelash");
    public static final Block fungflySpawner = new BlockBasicSpawner("spawner_fungfly", "fungfly");
    public static final Block mushmerraSpawner = new BlockBasicSpawner("spawner_mushmerra", "mushmerra");
    public static final Block shroomiteSpawner = new BlockBasicSpawner("spawner_shroomite", "shroomite");
    public static final Block etherstock = new BlockEtherstock("etherstock");
    public static final Block screenObstaclealley = new BlockContestGame("screen_obstaclealley", 13);
    public static final Block championCarpetObstaclealley = new BlockBasicLight("champion_carpet_obstaclealley");
    public static final Block championCarpetObstaclealleyCut = new BlockBasicRotational("champion_carpet_obstaclealley_cut").func_149715_a(1.0f);
    public static final Block fallBridge = new BlockFallBridge("fall_bridge");
    public static final Block cthulhuSpawner = new BlockCthulhuSpawner("cthulhu_spawner");
    public static final Block combustionEngine = new BlockCombustionEngine("combustion_engine");
    public static final Block gearbox = new BlockGearbox("gearbox");
    public static final Block grinder = new BlockGrinder("grinder", false);
    public static final Block killerVine = new BlockKillerVine("killer_vine");
    public static final Block bossGate = new BlockBossGate("boss_gate");
    public static final Block cellCharger = new BlockCellCharger("cell_charger");
    public static final Block sunstoneOre = new BlockSunstoneOre("sunstone_ore");
    public static final Block blightedCore = new BlockBlightedCore("blighted_core");
    public static Block getRandomOre(World world) {
        Block[] ores = {oreEmberium, oreHextorium, oreCrystonium, oreAstrallium, oreKylaxium, oreVellorium, oreIncadium, oreNoxerium, oreolysium, oreDetherium, oreXerovium, orePhytrosium};
        int block = world.field_73012_v.nextInt(ores.length);
        return ores[block];
    }
    public static void objectPassing() {
        factoryPlatformHalf.setMySlab((BlockBasicSlab) factoryPlatformHalf);
        gloglobes.setSeedCropSoil(ItemInit.glowingSeeds, ItemInit.glowingGlobes, poweredCrystallizedSoil);
        emberleaf.setSeedCropSoil(ItemInit.emberleafSeeds, ItemInit.emberPods, poweredCrystallizedSoil);
        spacePickle.setSeedCropSoil(ItemInit.pickleSeeds, ItemInit.pickle, poweredCrystallizedSoil);
        moonFlower.setSeedCropSoil(ItemInit.moonflowerSeeds, ItemInit.glowingGlobes, poweredCrystallizedSoil);
        ((BlockBasicMoistured) poweredCrystallizedSoil).setReplacementAndLiquid(unpoweredCrystallizedSoil, concentratedAcid);
        ((BlockBasicMoistured) unpoweredCrystallizedSoil).setReplacementAndLiquid(poweredCrystallizedSoil, concentratedAcid);
    }
}
