package xol.lostinfinity.init;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.registry.EntityEntryBuilder;
import net.minecraftforge.fml.common.registry.GameRegistry;
import xol.lostinfinity.block.tileentity.TileEntityAlignmentDialGame;
import xol.lostinfinity.block.tileentity.TileEntityAncientSymbolInterpreter;
import xol.lostinfinity.block.tileentity.TileEntityChemistryTable;
import xol.lostinfinity.block.tileentity.TileEntityChromaGame;
import xol.lostinfinity.block.tileentity.TileEntityCircuitCalibrator;
import xol.lostinfinity.block.tileentity.TileEntityCombustionEngine;
import xol.lostinfinity.block.tileentity.TileEntityCompressionTable;
import xol.lostinfinity.block.tileentity.TileEntityCthulhuSpawner;
import xol.lostinfinity.block.tileentity.TileEntityDrillConsole;
import xol.lostinfinity.block.tileentity.TileEntityEternalBeacon;
import xol.lostinfinity.block.tileentity.TileEntityFusionTable;
import xol.lostinfinity.block.tileentity.TileEntityGearbox;
import xol.lostinfinity.block.tileentity.TileEntityGenerator;
import xol.lostinfinity.block.tileentity.TileEntityGrinder;
import xol.lostinfinity.block.tileentity.TileEntityKillerVine;
import xol.lostinfinity.block.tileentity.TileEntityLightEmitter;
import xol.lostinfinity.block.tileentity.TileEntityMelodicSequencer;
import xol.lostinfinity.block.tileentity.TileEntityNavigationDevice;
import xol.lostinfinity.block.tileentity.TileEntityNebulousBeacon;
import xol.lostinfinity.block.tileentity.TileEntityNicroniumInfuser;
import xol.lostinfinity.block.tileentity.TileEntityPolymerizationDevice;
import xol.lostinfinity.block.tileentity.TileEntityPortalNexus;
import xol.lostinfinity.block.tileentity.TileEntityPortalNode;
import xol.lostinfinity.block.tileentity.TileEntityPowerCollider;
import xol.lostinfinity.block.tileentity.TileEntityPowerConduit;
import xol.lostinfinity.block.tileentity.TileEntityRainfallGenerator;
import xol.lostinfinity.block.tileentity.TileEntityRemoteControl;
import xol.lostinfinity.block.tileentity.TileEntitySapEvaporator;
import xol.lostinfinity.block.tileentity.TileEntityShipmentFiller;
import xol.lostinfinity.block.tileentity.TileEntityTeslaTower;
import xol.lostinfinity.block.tileentity.TileEntityVoidVacuum;
import xol.lostinfinity.block.tileentity.TileEntityWeldingChamber;
import xol.lostinfinity.mob.entity.base.EntityParticleTrojan;
import xol.lostinfinity.mob.entity.boss.EntityAlestria;
import xol.lostinfinity.mob.entity.boss.EntityArash;
import xol.lostinfinity.mob.entity.boss.EntityArenaEvent;
import xol.lostinfinity.mob.entity.boss.EntityAtlasCrystal;
import xol.lostinfinity.mob.entity.boss.EntityAtlasSpire;
import xol.lostinfinity.mob.entity.boss.EntityBarul;
import xol.lostinfinity.mob.entity.boss.EntityCryonus;
import xol.lostinfinity.mob.entity.boss.EntityDarrio;
import xol.lostinfinity.mob.entity.boss.EntityDeviantCrystal;
import xol.lostinfinity.mob.entity.boss.EntityDeviantWither;
import xol.lostinfinity.mob.entity.boss.EntityDroidBoss;
import xol.lostinfinity.mob.entity.boss.EntityDuskerQueen;
import xol.lostinfinity.mob.entity.boss.EntityElara;
import xol.lostinfinity.mob.entity.boss.EntityNuxuro;
import xol.lostinfinity.mob.entity.boss.EntityOzor;
import xol.lostinfinity.mob.entity.boss.EntityOzorDecoy;
import xol.lostinfinity.mob.entity.boss.EntityPuzzleMaster;
import xol.lostinfinity.mob.entity.boss.EntityRestorationCrystal;
import xol.lostinfinity.mob.entity.boss.EntityRikarus;
import xol.lostinfinity.mob.entity.boss.EntitySentryCrystal;
import xol.lostinfinity.mob.entity.boss.EntityThundyron;
import xol.lostinfinity.mob.entity.boss.EntityUrogo;
import xol.lostinfinity.mob.entity.boss.EntityVelo;
import xol.lostinfinity.mob.entity.boss.EntityVycellia;
import xol.lostinfinity.mob.entity.boss.EntityWitherSkullling;
import xol.lostinfinity.mob.entity.contest.EntityBloodhunter;
import xol.lostinfinity.mob.entity.contest.EntityContestHologram;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerBattleSnakes;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerBombers;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerDuelArena;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerHolodeck;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerHunters;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerInkBattle;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerLaserTag;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerLightBridge;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerParkour;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerRedlight;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerTargets;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerTrampolineDodgeball;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerTreadmill;
import xol.lostinfinity.mob.entity.contest.misc.EntityTreadmillObstacle;
import xol.lostinfinity.mob.entity.contest.misc.EntityTreadmillObstacleJumpable;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorBattleSnakes;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorBombers;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorDuelArena;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorHolodeck;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorHunters;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorInkBattle;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorLaserTag;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorLightBridge;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorParkour;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorRedlight;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorTargets;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorTrampolineDodgeball;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorTreadmill;
import xol.lostinfinity.mob.entity.contest.trader.EntityArcheologist;
import xol.lostinfinity.mob.entity.contest.trader.EntityChemist;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderBattleSnakes;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderBombers;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderHolodeck;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderHunters;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderInkBattle;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderLaserTag;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderLightbridge;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderMarket;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderParkour;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderRedlight;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderTargets;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderTrampolineDodgeball;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderTreadmill;
import xol.lostinfinity.mob.entity.cthulhu.EntityCelestialStatue;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhu;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuBlackHole;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuCloud;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuDeathFX;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuHealingOrb;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuRift;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuSpear;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuTentacle;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuTentaclePersist;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuTurret;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantAmalgam;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBat;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBear;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBlaze;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCaveSpider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantChicken;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCow;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCreeper;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantDimTrader;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEnderman;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEvoker;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEvokerVex;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGhast;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGolem;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGuardian;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantHorse;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantHusk;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantLlama;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantMagmacube;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantMooshroom;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantOcelote;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantPig;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantPiglin;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSheep;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantShulker;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSkeleton;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSkyworm;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSlime;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSlimeStrider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSnowman;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSpider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSquid;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantStray;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantVex;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWitch;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWitherSkeleton;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWolf;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantZombie;
import xol.lostinfinity.mob.entity.deviant.EntityLostDeviant;
import xol.lostinfinity.mob.entity.deviant.prime.EntityAzross;
import xol.lostinfinity.mob.entity.deviant.prime.EntityKalikos;
import xol.lostinfinity.mob.entity.deviant.prime.EntityLivorax;
import xol.lostinfinity.mob.entity.deviant.prime.EntityZenon;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanBlaze;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanCreeper;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanEnderman;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanLlama;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanMagmacube;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanPiglin;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanShulker;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanSkeleton;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanSpider;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanStray;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanVex;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanZombie;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTrialObserver;
import xol.lostinfinity.mob.entity.fungal.EntityFungfly;
import xol.lostinfinity.mob.entity.fungal.EntityMushmerra;
import xol.lostinfinity.mob.entity.fungal.EntityMushmerraClone;
import xol.lostinfinity.mob.entity.fungal.EntityShroomite;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyBeast;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyDragon;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyGladiator;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyGulper;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxySorcerer;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxySpire;
import xol.lostinfinity.mob.entity.galaxy.EntityLaserSpire;
import xol.lostinfinity.mob.entity.labyrinth.EntityAspect;
import xol.lostinfinity.mob.entity.labyrinth.EntityClinger;
import xol.lostinfinity.mob.entity.labyrinth.EntityCyclos;
import xol.lostinfinity.mob.entity.labyrinth.EntityGloop;
import xol.lostinfinity.mob.entity.labyrinth.EntityGloopMother;
import xol.lostinfinity.mob.entity.labyrinth.EntityLabWarrior;
import xol.lostinfinity.mob.entity.labyrinth.EntityLabWizard;
import xol.lostinfinity.mob.entity.labyrinth.EntityNat;
import xol.lostinfinity.mob.entity.labyrinth.EntitySentry;
import xol.lostinfinity.mob.entity.labyrinth.EntityStickler;
import xol.lostinfinity.mob.entity.labyrinth.EntityVectosect;
import xol.lostinfinity.mob.entity.minion.EntityAbyssalCrabulon;
import xol.lostinfinity.mob.entity.minion.EntityAuraOfAllegiance;
import xol.lostinfinity.mob.entity.minion.EntityBombDrone;
import xol.lostinfinity.mob.entity.minion.EntityLostBlade;
import xol.lostinfinity.mob.entity.minion.EntityLuminousGuardian;
import xol.lostinfinity.mob.entity.minion.andromeda.EntityAndromedaChaser;
import xol.lostinfinity.mob.entity.minion.andromeda.EntityAndromedaController;
import xol.lostinfinity.mob.entity.misc.EntityBomberBomb;
import xol.lostinfinity.mob.entity.misc.EntityCellGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityClusterCannon;
import xol.lostinfinity.mob.entity.misc.EntityConnectGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityCourseRing;
import xol.lostinfinity.mob.entity.misc.EntityDimensionalMerchant;
import xol.lostinfinity.mob.entity.misc.EntityDroid;
import xol.lostinfinity.mob.entity.misc.EntityEffigyEffect;
import xol.lostinfinity.mob.entity.misc.EntityEidolonMist;
import xol.lostinfinity.mob.entity.misc.EntityFeralMerchant;
import xol.lostinfinity.mob.entity.misc.EntityGhostCopy;
import xol.lostinfinity.mob.entity.misc.EntityIonExplosion;
import xol.lostinfinity.mob.entity.misc.EntityLightGame;
import xol.lostinfinity.mob.entity.misc.EntityMarkOfInfiniteDespair;
import xol.lostinfinity.mob.entity.misc.EntityMemPuzzleMerchant;
import xol.lostinfinity.mob.entity.misc.EntityMirrorZombie;
import xol.lostinfinity.mob.entity.misc.EntityMortarCannon;
import xol.lostinfinity.mob.entity.misc.EntityMultiverseGhost;
import xol.lostinfinity.mob.entity.misc.EntityNitroExplosion;
import xol.lostinfinity.mob.entity.misc.EntityNuclearExplosion;
import xol.lostinfinity.mob.entity.misc.EntityPickleMan;
import xol.lostinfinity.mob.entity.misc.EntityPipeGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityPlasmaBomb;
import xol.lostinfinity.mob.entity.misc.EntityPlasmaExplosion;
import xol.lostinfinity.mob.entity.misc.EntityPlasmaSlicer;
import xol.lostinfinity.mob.entity.misc.EntityPlayerLimb;
import xol.lostinfinity.mob.entity.misc.EntityRhythmGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityRift;
import xol.lostinfinity.mob.entity.misc.EntityRisingPhantom;
import xol.lostinfinity.mob.entity.misc.EntityRocketStrappedExplosive;
import xol.lostinfinity.mob.entity.misc.EntitySandAttack;
import xol.lostinfinity.mob.entity.misc.EntitySkybooster;
import xol.lostinfinity.mob.entity.misc.EntitySkycrab;
import xol.lostinfinity.mob.entity.misc.EntitySlimeStrider;
import xol.lostinfinity.mob.entity.misc.EntitySpectre;
import xol.lostinfinity.mob.entity.misc.EntityStarfiend;
import xol.lostinfinity.mob.entity.misc.EntityStickyBomb;
import xol.lostinfinity.mob.entity.misc.EntityStormBomb;
import xol.lostinfinity.mob.entity.misc.EntitySupplyTrader;
import xol.lostinfinity.mob.entity.misc.EntityTNTZombie;
import xol.lostinfinity.mob.entity.misc.EntityTentacleTrap;
import xol.lostinfinity.mob.entity.misc.EntityThunderBomb;
import xol.lostinfinity.mob.entity.misc.EntityTornIndividual;
import xol.lostinfinity.mob.entity.misc.EntityTotemMoon;
import xol.lostinfinity.mob.entity.misc.EntityTotemPylon;
import xol.lostinfinity.mob.entity.misc.EntityTotemSplitter;
import xol.lostinfinity.mob.entity.misc.EntityUnstableMerchant;
import xol.lostinfinity.mob.entity.misc.EntityUnstableRift;
import xol.lostinfinity.mob.entity.misc.EntityWhackGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityWormholePortal;
import xol.lostinfinity.mob.entity.mount.EntityJetMount;
import xol.lostinfinity.mob.entity.mount.EntityXScreacher;
import xol.lostinfinity.mob.entity.murk.EntityCaveTerror;
import xol.lostinfinity.mob.entity.murk.EntityDoomsday;
import xol.lostinfinity.mob.entity.murk.EntityScorpwing;
import xol.lostinfinity.mob.entity.murk.EntityScreamer;
import xol.lostinfinity.mob.entity.murk.EntitySkyre;
import xol.lostinfinity.mob.entity.murk.EntityTorpedon;
import xol.lostinfinity.mob.entity.murk.EntityWhisper;
import xol.lostinfinity.mob.entity.nebula.EntityNebulaGiant;
import xol.lostinfinity.mob.entity.nebula.EntityNebulaGrunt;
import xol.lostinfinity.mob.entity.nebula.EntityNebulaWizard;
import xol.lostinfinity.mob.entity.sea.EntityCrabulon;
import xol.lostinfinity.mob.entity.sea.EntityDoublerang;
import xol.lostinfinity.mob.entity.sea.EntityEelShark;
import xol.lostinfinity.mob.entity.sea.EntityGlowfish;
import xol.lostinfinity.mob.entity.sea.EntityLongfin;
import xol.lostinfinity.mob.entity.sea.EntityOctobrella;
import xol.lostinfinity.mob.entity.sea.EntityPearlCollector;
import xol.lostinfinity.mob.entity.sea.EntityRayfish;
import xol.lostinfinity.mob.entity.sea.EntityRibshark;
import xol.lostinfinity.mob.entity.sea.EntityUnderfin;
import xol.lostinfinity.mob.entity.sea.leviathan.EntityLeviathanController;
import xol.lostinfinity.mob.entity.sea.seaserpent.EntitySeaSerpentController;
import xol.lostinfinity.mob.entity.starforge.EntityAcidback;
import xol.lostinfinity.mob.entity.starforge.EntityAugmenticon;
import xol.lostinfinity.mob.entity.starforge.EntityBlisterweed;
import xol.lostinfinity.mob.entity.starforge.EntityChomper;
import xol.lostinfinity.mob.entity.starforge.EntityClusterweed;
import xol.lostinfinity.mob.entity.starforge.EntityClyster;
import xol.lostinfinity.mob.entity.starforge.EntityCrawker;
import xol.lostinfinity.mob.entity.starforge.EntityCrusher;
import xol.lostinfinity.mob.entity.starforge.EntityDoomDog;
import xol.lostinfinity.mob.entity.starforge.EntityDoublejaw;
import xol.lostinfinity.mob.entity.starforge.EntityDrippler;
import xol.lostinfinity.mob.entity.starforge.EntityDusker;
import xol.lostinfinity.mob.entity.starforge.EntityEssenceDweller;
import xol.lostinfinity.mob.entity.starforge.EntityEssenceIdol;
import xol.lostinfinity.mob.entity.starforge.EntityExplosect;
import xol.lostinfinity.mob.entity.starforge.EntityEyeSlug;
import xol.lostinfinity.mob.entity.starforge.EntityFlapper;
import xol.lostinfinity.mob.entity.starforge.EntityFlashfly;
import xol.lostinfinity.mob.entity.starforge.EntityFlurky;
import xol.lostinfinity.mob.entity.starforge.EntityFlutterbee;
import xol.lostinfinity.mob.entity.starforge.EntityFlutterfyre;
import xol.lostinfinity.mob.entity.starforge.EntityFyreweed;
import xol.lostinfinity.mob.entity.starforge.EntityGalacticTerror;
import xol.lostinfinity.mob.entity.starforge.EntityGiantFlapper;
import xol.lostinfinity.mob.entity.starforge.EntityGiantFyreweed;
import xol.lostinfinity.mob.entity.starforge.EntityGiantRockslug;
import xol.lostinfinity.mob.entity.starforge.EntityGlangler;
import xol.lostinfinity.mob.entity.starforge.EntityGloboon;
import xol.lostinfinity.mob.entity.starforge.EntityGlobro;
import xol.lostinfinity.mob.entity.starforge.EntityGlochipper;
import xol.lostinfinity.mob.entity.starforge.EntityGlomite;
import xol.lostinfinity.mob.entity.starforge.EntityGnawer;
import xol.lostinfinity.mob.entity.starforge.EntityGorger;
import xol.lostinfinity.mob.entity.starforge.EntityGrappler;
import xol.lostinfinity.mob.entity.starforge.EntityGravhead;
import xol.lostinfinity.mob.entity.starforge.EntityGrubber;
import xol.lostinfinity.mob.entity.starforge.EntityHanger;
import xol.lostinfinity.mob.entity.starforge.EntityHurler;
import xol.lostinfinity.mob.entity.starforge.EntityHypnosaur;
import xol.lostinfinity.mob.entity.starforge.EntityLeer;
import xol.lostinfinity.mob.entity.starforge.EntityLurcher;
import xol.lostinfinity.mob.entity.starforge.EntityMinimite;
import xol.lostinfinity.mob.entity.starforge.EntityNightshyre;
import xol.lostinfinity.mob.entity.starforge.EntityOrbiter;
import xol.lostinfinity.mob.entity.starforge.EntityPhaser;
import xol.lostinfinity.mob.entity.starforge.EntityRavager;
import xol.lostinfinity.mob.entity.starforge.EntityReflectal;
import xol.lostinfinity.mob.entity.starforge.EntityRibrex;
import xol.lostinfinity.mob.entity.starforge.EntityRockpest;
import xol.lostinfinity.mob.entity.starforge.EntityRockslug;
import xol.lostinfinity.mob.entity.starforge.EntityRockworm;
import xol.lostinfinity.mob.entity.starforge.EntityScreacher;
import xol.lostinfinity.mob.entity.starforge.EntityShimmer;
import xol.lostinfinity.mob.entity.starforge.EntitySightwalker;
import xol.lostinfinity.mob.entity.starforge.EntitySnapper;
import xol.lostinfinity.mob.entity.starforge.EntitySpinovern;
import xol.lostinfinity.mob.entity.starforge.EntitySpyker;
import xol.lostinfinity.mob.entity.starforge.EntityTentaclon;
import xol.lostinfinity.mob.entity.starforge.EntityTerrorFly;
import xol.lostinfinity.mob.entity.starforge.EntityTetherbug;
import xol.lostinfinity.mob.entity.starforge.EntityTitanopod;
import xol.lostinfinity.mob.entity.starforge.EntityVilebulb;
import xol.lostinfinity.mob.entity.starforge.EntityWeaver;
import xol.lostinfinity.mob.entity.starforge.EntityWisp;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuBeam;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuMeteor;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuMissile;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuTurretBullet;
import xol.lostinfinity.projectile.entity.EntityAcidRainDrop;
import xol.lostinfinity.projectile.entity.EntityAcidicConcoction;
import xol.lostinfinity.projectile.entity.EntityArcBlast;
import xol.lostinfinity.projectile.entity.EntityAsteroid;
import xol.lostinfinity.projectile.entity.EntityAstralShot;
import xol.lostinfinity.projectile.entity.EntityAtlasAttack;
import xol.lostinfinity.projectile.entity.EntityAvenger;
import xol.lostinfinity.projectile.entity.EntityAvengerLightning;
import xol.lostinfinity.projectile.entity.EntityBallOfContainedGluons;
import xol.lostinfinity.projectile.entity.EntityBallOfContainedQuarks;
import xol.lostinfinity.projectile.entity.EntityBarulChain;
import xol.lostinfinity.projectile.entity.EntityBeeAttack;
import xol.lostinfinity.projectile.entity.EntityBlightBomb;
import xol.lostinfinity.projectile.entity.EntityBlightPellet;
import xol.lostinfinity.projectile.entity.EntityBlightedComet;
import xol.lostinfinity.projectile.entity.EntityBloodhunterBlast;
import xol.lostinfinity.projectile.entity.EntityBossPortalEffect;
import xol.lostinfinity.projectile.entity.EntityCarrierProjectile;
import xol.lostinfinity.projectile.entity.EntityCelestialFire;
import xol.lostinfinity.projectile.entity.EntityCellularRock;
import xol.lostinfinity.projectile.entity.EntityChainOfVenomsAttack;
import xol.lostinfinity.projectile.entity.EntityChampionDodgeball;
import xol.lostinfinity.projectile.entity.EntityClusterBlast;
import xol.lostinfinity.projectile.entity.EntityComet;
import xol.lostinfinity.projectile.entity.EntityCrabulonProjectile;
import xol.lostinfinity.projectile.entity.EntityCreepingVineArrow;
import xol.lostinfinity.projectile.entity.EntityCreepingVinePod;
import xol.lostinfinity.projectile.entity.EntityCryoBeamEffect;
import xol.lostinfinity.projectile.entity.EntityCryoBolt;
import xol.lostinfinity.projectile.entity.EntityCrystalGellball;
import xol.lostinfinity.projectile.entity.EntityCrystalShard;
import xol.lostinfinity.projectile.entity.EntityDarkSpell;
import xol.lostinfinity.projectile.entity.EntityDeathShot;
import xol.lostinfinity.projectile.entity.EntityDebtCollectorEffect;
import xol.lostinfinity.projectile.entity.EntityDestabilizer;
import xol.lostinfinity.projectile.entity.EntityDeviantDeployer;
import xol.lostinfinity.projectile.entity.EntityDeviantEvokerBomb;
import xol.lostinfinity.projectile.entity.EntityDeviantEvokerFangs;
import xol.lostinfinity.projectile.entity.EntityDeviantEvokerShot;
import xol.lostinfinity.projectile.entity.EntityDeviantShulkerBullet;
import xol.lostinfinity.projectile.entity.EntityDeviantSnowball;
import xol.lostinfinity.projectile.entity.EntityDeviantSpit;
import xol.lostinfinity.projectile.entity.EntityDeviantSucker;
import xol.lostinfinity.projectile.entity.EntityDoomBlast;
import xol.lostinfinity.projectile.entity.EntityDoomShot;
import xol.lostinfinity.projectile.entity.EntityDroidBall;
import xol.lostinfinity.projectile.entity.EntityDroidLaser;
import xol.lostinfinity.projectile.entity.EntityDroidSucker;
import xol.lostinfinity.projectile.entity.EntityDroidZapper;
import xol.lostinfinity.projectile.entity.EntityDryadsGripAttack;
import xol.lostinfinity.projectile.entity.EntityDuskerQueenWeb;
import xol.lostinfinity.projectile.entity.EntityEchoBlast;
import xol.lostinfinity.projectile.entity.EntityEchoOfGravity;
import xol.lostinfinity.projectile.entity.EntityEffigyShot;
import xol.lostinfinity.projectile.entity.EntityElaraShot;
import xol.lostinfinity.projectile.entity.EntityElementiumAir;
import xol.lostinfinity.projectile.entity.EntityElementiumBlight;
import xol.lostinfinity.projectile.entity.EntityElementiumEarth;
import xol.lostinfinity.projectile.entity.EntityElementiumFire;
import xol.lostinfinity.projectile.entity.EntityElementiumPlague;
import xol.lostinfinity.projectile.entity.EntityElementiumPrime;
import xol.lostinfinity.projectile.entity.EntityElementiumShadow;
import xol.lostinfinity.projectile.entity.EntityElementiumWater;
import xol.lostinfinity.projectile.entity.EntityEmberShot;
import xol.lostinfinity.projectile.entity.EntityEnergyBurst;
import xol.lostinfinity.projectile.entity.EntityExothermite;
import xol.lostinfinity.projectile.entity.EntityExplosiveGoo;
import xol.lostinfinity.projectile.entity.EntityFallingStar;
import xol.lostinfinity.projectile.entity.EntityFearBomb;
import xol.lostinfinity.projectile.entity.EntityFirePellet;
import xol.lostinfinity.projectile.entity.EntityFluxBall;
import xol.lostinfinity.projectile.entity.EntityForbiddenBrand;
import xol.lostinfinity.projectile.entity.EntityFountainPellet;
import xol.lostinfinity.projectile.entity.EntityFractureBomb;
import xol.lostinfinity.projectile.entity.EntityGalaxyBlast;
import xol.lostinfinity.projectile.entity.EntityGalaxyBomb;
import xol.lostinfinity.projectile.entity.EntityGalaxyDragonFireball;
import xol.lostinfinity.projectile.entity.EntityGalaxyKnife;
import xol.lostinfinity.projectile.entity.EntityGalaxyLaser;
import xol.lostinfinity.projectile.entity.EntityGalaxySpell;
import xol.lostinfinity.projectile.entity.EntityGenericBomb;
import xol.lostinfinity.projectile.entity.EntityGloomSpell;
import xol.lostinfinity.projectile.entity.EntityGravityWarper;
import xol.lostinfinity.projectile.entity.EntityHomingBlight;
import xol.lostinfinity.projectile.entity.EntityInfinityTrident;
import xol.lostinfinity.projectile.entity.EntityInfinityTridentMK2;
import xol.lostinfinity.projectile.entity.EntityInkBomb;
import xol.lostinfinity.projectile.entity.EntityInkShot;
import xol.lostinfinity.projectile.entity.EntityIonicChakram;
import xol.lostinfinity.projectile.entity.EntityLaserBlast;
import xol.lostinfinity.projectile.entity.EntityLaserGunBeam;
import xol.lostinfinity.projectile.entity.EntityLaunchedKnife;
import xol.lostinfinity.projectile.entity.EntityLeviathanBreath;
import xol.lostinfinity.projectile.entity.EntityLeviathanTeslaOrb;
import xol.lostinfinity.projectile.entity.EntityLeviathanTracer;
import xol.lostinfinity.projectile.entity.EntityLivoraxBullet;
import xol.lostinfinity.projectile.entity.EntityLuminousGuardianLaser;
import xol.lostinfinity.projectile.entity.EntityMeteor;
import xol.lostinfinity.projectile.entity.EntityMicroRocket;
import xol.lostinfinity.projectile.entity.EntityMiniChakram;
import xol.lostinfinity.projectile.entity.EntityMobComet;
import xol.lostinfinity.projectile.entity.EntityMortarShot;
import xol.lostinfinity.projectile.entity.EntityNebulaSpell;
import xol.lostinfinity.projectile.entity.EntityPicklePortal;
import xol.lostinfinity.projectile.entity.EntityPiercingShot;
import xol.lostinfinity.projectile.entity.EntityPlagueBlast;
import xol.lostinfinity.projectile.entity.EntityPoisonousBubble;
import xol.lostinfinity.projectile.entity.EntityPortalEffect;
import xol.lostinfinity.projectile.entity.EntityPowerPulse;
import xol.lostinfinity.projectile.entity.EntityProjectileKiller;
import xol.lostinfinity.projectile.entity.EntityPuzzleMasterArrow;
import xol.lostinfinity.projectile.entity.EntityRainDrop;
import xol.lostinfinity.projectile.entity.EntityRecursor;
import xol.lostinfinity.projectile.entity.EntityRockshot;
import xol.lostinfinity.projectile.entity.EntityScreamerBlast;
import xol.lostinfinity.projectile.entity.EntityScreamerPortalEffect;
import xol.lostinfinity.projectile.entity.EntitySelectionLaser;
import xol.lostinfinity.projectile.entity.EntitySelectorAttack;
import xol.lostinfinity.projectile.entity.EntitySkullShot;
import xol.lostinfinity.projectile.entity.EntitySkyStrike;
import xol.lostinfinity.projectile.entity.EntitySkycrabAttack;
import xol.lostinfinity.projectile.entity.EntitySonicAttack;
import xol.lostinfinity.projectile.entity.EntitySoundwaveBullet;
import xol.lostinfinity.projectile.entity.EntitySpiderBlast;
import xol.lostinfinity.projectile.entity.EntitySpikeBall;
import xol.lostinfinity.projectile.entity.EntityStarBlast;
import xol.lostinfinity.projectile.entity.EntityStickyProjectile;
import xol.lostinfinity.projectile.entity.EntityStrappedFirework;
import xol.lostinfinity.projectile.entity.EntityStunAttack;
import xol.lostinfinity.projectile.entity.EntitySunstoneRock;
import xol.lostinfinity.projectile.entity.EntityTNTStrapper;
import xol.lostinfinity.projectile.entity.EntityTekBullet;
import xol.lostinfinity.projectile.entity.EntityTentacleSeed;
import xol.lostinfinity.projectile.entity.EntityTetherBall;
import xol.lostinfinity.projectile.entity.EntityTitanRing;
import xol.lostinfinity.projectile.entity.EntityTormentorChain;
import xol.lostinfinity.projectile.entity.EntityUltraCrystalGel;
import xol.lostinfinity.projectile.entity.EntityUnstableBalloon;
import xol.lostinfinity.projectile.entity.EntityVeloMagic;
import xol.lostinfinity.projectile.entity.EntityVenomBlast;
import xol.lostinfinity.projectile.entity.EntityVoidLaser;
import xol.lostinfinity.projectile.entity.EntityVoltaicIonizerAttack;
import xol.lostinfinity.projectile.entity.EntityWandAttack;
import xol.lostinfinity.projectile.entity.EntityWhirlpool;
import xol.lostinfinity.projectile.entity.EntityWitchMagic;
import xol.lostinfinity.projectile.entity.EntityWitherBomb;
import xol.lostinfinity.projectile.entity.EntityWizardBlast;
import xol.lostinfinity.projectile.entity.EntityWormholeShot;
import xol.lostinfinity.projectile.entity.EntityXSonicAttack;
import xol.lostinfinity.projectile.entity.EntityZenonShot;
import xol.lostinfinity.stone.EntityInfinityStone;
import xol.lostinfinity.util.Reference;
@Mod.EventBusSubscriber(modid = Reference.MODID)
public class EntityInit {
    private static int entityId = 0;
    @SubscribeEvent
    public static void registerEnities(RegistryEvent.Register<EntityEntry> event) {
        event.getRegistry().registerAll(mobEntries());
        event.getRegistry().registerAll(projectileEntries());
    }
    public static <E extends Entity> EntityEntry customEntityEntry(Class entityClass, String name, int primary, int secondary) {
        return doEntityEntry(entityClass, name, primary, secondary, true, 120);
    }
    public static <E extends Entity> EntityEntry egglessEntry(Class entityClass, String name, int primary, int secondary) {
        return doEntityEntry(entityClass, name, primary, secondary, false, 120);
    }
    public static <E extends Entity> EntityEntry doEntityEntry(Class entityClass, String name, int primary, int secondary, boolean egg, int track) {
        entityId++;
        EntityEntryBuilder<E> builder = EntityEntryBuilder.create();
        builder.entity(entityClass);
        builder.tracker(track, 1, true);
        if (egg) {
            builder.egg(primary, secondary);
        }
        EntityEntryBuilder.BuiltEntityEntry entry = builder.id(new ResourceLocation(Reference.MODID, name), entityId).name("lostinfinity." + name).build();
        entry.addedToRegistry();
        return entry;
    }
    public static EntityEntry customProjectileEntry(Class entityClass, String entityID) {
        entityId++;
        return EntityEntryBuilder.create().entity(entityClass).id(new ResourceLocation(Reference.MODID, entityID), entityId).name("lostinfinity." + entityID).tracker(120, 20, true).build();
    }
    public static EntityEntry customProjectileEntry(Class entityClass, String entityID, int interval) {
        entityId++;
        return EntityEntryBuilder.create().entity(entityClass).id(new ResourceLocation(Reference.MODID, entityID), entityId).name("lostinfinity." + entityID).tracker(120, interval, true).build();
    }
    public static EntityEntry[] mobEntries() {
        return new EntityEntry[]{customEntityEntry(EntityDimensionalMerchant.class, "dimensionalmerchant", 7614683, 443842), customEntityEntry(EntityDeviantBear.class, "deviantbear", 8424104, 3104159), customEntityEntry(EntityTreadmillObstacle.class, "treadmillobstacle", 8424104, 3104159), customEntityEntry(EntityTreadmillObstacleJumpable.class, "treadmillobstaclejumpable", 8424104, 3104159), customEntityEntry(EntityDeviantGhast.class, "deviantghast", 4473924, 11536640), customEntityEntry(EntityDeviantCow.class, "deviantcow", 2766650, 43263), customEntityEntry(EntityDeviantSheep.class, "deviantsheep", 2766650, 43263), customEntityEntry(EntityDeviantHorse.class, "devianthorse", 2766650, 43263), customEntityEntry(EntityDeviantPig.class, "deviantpig", 2766650, 43263), customEntityEntry(EntityDeviantEvoker.class, "deviantevoker", 2766650, 43263), customEntityEntry(EntityDeviantEvokerVex.class, "deviantevokervex", 2766650, 43263), customEntityEntry(EntityDeviantEnderman.class, "deviantenderman", 0, 9579469), customEntityEntry(EntityDeviantChicken.class, "deviantchicken", 8947848, 5964804), customEntityEntry(EntityDeviantShulker.class, "deviantshulker", 4216413, 12247777), customEntityEntry(EntityDeviantSkyworm.class, "deviantskyworm", 1585203, 7783599), customEntityEntry(EntityElara.class, "elara", 11072475, 1780577), customEntityEntry(EntityInfinityStone.class, "infinitystone", 0, 0), customEntityEntry(EntityDeviantCreeper.class, "deviantcreeper", 4874085, 25830), customEntityEntry(EntityDeviantSkeleton.class, "deviantskeleton", 3623000, 15921907), customEntityEntry(EntityUrogo.class, "urogo", 6488834, 12538624), customEntityEntry(EntityDroid.class, "droid", 7566195, 12779777), customEntityEntry(EntityDroidBoss.class, "droidboss", 3624277, 12779777), customEntityEntry(EntityLostDeviant.class, "lostdeviant", 2571854, 474615), customEntityEntry(EntityArenaEvent.class, "arenaevent", 7857, 13303812), customEntityEntry(EntityLabWarrior.class, "labwarrior", 5139306, 9448480), customEntityEntry(EntityLabWizard.class, "labwizard", 419797, 9448480), customEntityEntry(EntityDeviantSpider.class, "deviantspider", 2306367, 46518), customEntityEntry(EntityAspect.class, "aspect", 10486016, 14471093), customEntityEntry(EntitySlimeStrider.class, "slimestrider", 6072961, 6983758), customEntityEntry(EntityVelo.class, "velo", 1192507, 1055801), customEntityEntry(EntityGalaxyBeast.class, "galaxybeast", 921102, 4934475), customEntityEntry(EntityGalaxySorcerer.class, "galaxysorcerer", 921102, 4934475), customEntityEntry(EntityGalaxyGladiator.class, "galaxygladiator", 921102, 4934475), customEntityEntry(EntityGalaxySpire.class, "galaxyspire", 921102, 4934475), customEntityEntry(EntityDeviantAmalgam.class, "deviantamalgam", 921102, 4934475), customEntityEntry(EntityStarfiend.class, "starfiend", 91102, 4934475), customEntityEntry(EntityBloodhunter.class, "bloodhunter", 91102, 4934475), customEntityEntry(EntityFungfly.class, "fungfly", 91102, 4934475), customEntityEntry(EntityRikarus.class, "rikarus", 91102, 4934475), customEntityEntry(EntityRestorationCrystal.class, "restorationcrystal", 91102, 4934475), customEntityEntry(EntityDeviantWitch.class, "deviantwitch", 91102, 4934475), customEntityEntry(EntityMirrorZombie.class, "mirrorzombie", 91102, 4934475), customEntityEntry(EntityDeviantSlimeStrider.class, "deviantslimestrider", 6072961, 6983758), customEntityEntry(EntityChemist.class, "chemist", 91102, 4934475), customEntityEntry(EntitySandAttack.class, "sandattack", 91102, 4934475), customEntityEntry(EntityDeviantBlaze.class, "deviantblaze", 91102, 4934475), customEntityEntry(EntityTitanBlaze.class, "titanblaze", 91102, 4934475), customEntityEntry(EntityTitanShulker.class, "titanshulker", 91102, 4934475), customEntityEntry(EntityTitanSpider.class, "titanspider", 91102, 4934475), customEntityEntry(EntityTitanSkeleton.class, "titanskeleton", 91102, 4934475), customEntityEntry(EntityTrialObserver.class, "trialobserver", 91102, 4934475), customEntityEntry(EntityReflectal.class, "reflectal", 91102, 4934475), customEntityEntry(EntityLuminousGuardian.class, "luminousguardian", 91102, 4934475), customEntityEntry(EntityHanger.class, "hanger", 91102, 4934475), customEntityEntry(EntityAcidback.class, "acidback", 91102, 4934475), customEntityEntry(EntityGravhead.class, "gravhead", 91102, 4934475), customEntityEntry(EntityRockpest.class, "rockpest", 91102, 4934475), customEntityEntry(EntitySpinovern.class, "spinovern", 91102, 4934475), customEntityEntry(EntityHypnosaur.class, "hypnosaur", 91102, 4934475), customEntityEntry(EntityChomper.class, "chomper", 91102, 4934475), customEntityEntry(EntityRibrex.class, "ribrex", 91102, 4934475), customEntityEntry(EntityGnawer.class, "gnawer", 91102, 4934475), customEntityEntry(EntityScreacher.class, "screacher", 91102, 4934475), customEntityEntry(EntityEyeSlug.class, "eyeslug", 91102, 4934475), customEntityEntry(EntityFlutterfyre.class, "flutterfyre", 91102, 4934475), customEntityEntry(EntityDeviantSnowman.class, "deviantsnowman", 91102, 4934475), customEntityEntry(EntityNuxuro.class, "nuxuro", 91102, 4934475), customEntityEntry(EntityClyster.class, "clyster", 91102, 4934475), customEntityEntry(EntityCrawker.class, "crawker", 91102, 4934475), customEntityEntry(EntityDusker.class, "dusker", 91102, 4934475), customEntityEntry(EntityExplosect.class, "explosect", 91102, 4934475), customEntityEntry(EntityFlapper.class, "flapper", 91102, 4934475), customEntityEntry(EntityFlurky.class, "flurky", 91102, 4934475), customEntityEntry(EntityFyreweed.class, "fyreweed", 91102, 4934475), customEntityEntry(EntityGrappler.class, "grappler", 91102, 4934475), customEntityEntry(EntityHurler.class, "hurler", 91102, 4934475), customEntityEntry(EntityPhaser.class, "phaser", 91102, 4934475), customEntityEntry(EntityShimmer.class, "shimmer", 91102, 4934475), customEntityEntry(EntitySpyker.class, "spyker", 91102, 4934475), customEntityEntry(EntityDeviantMooshroom.class, "deviantmooshroom", 91102, 4934475), customEntityEntry(EntityDeviantZombie.class, "deviantzombie", 91102, 4934475), customEntityEntry(EntityDeviantSlime.class, "deviantslime", 91102, 4934475), customEntityEntry(EntityArash.class, "arash", 91102, 4934475), customEntityEntry(EntityAlestria.class, "alestria", 91102, 4934475), customEntityEntry(EntityAtlasSpire.class, "atlasspire", 91102, 4934475), customEntityEntry(EntityDarrio.class, "darrio", 91102, 4934475), customEntityEntry(EntityBarul.class, "barul", 91102, 4934475), customEntityEntry(EntitySentryCrystal.class, "sentrycrystal", 91102, 4934475), customEntityEntry(EntityAtlasCrystal.class, "atlascrystal", 91102, 4934475), customEntityEntry(EntityDeviantCrystal.class, "deviantcrystal", 91102, 4934475), customEntityEntry(EntityDeviantLlama.class, "deviantllama", 91102, 4934475), customEntityEntry(EntityDeviantMagmacube.class, "deviantmagmacube", 91102, 4934475), customEntityEntry(EntityDeviantVex.class, "deviantvex", 91102, 4934475), customEntityEntry(EntityDeviantStray.class, "deviantstray", 91102, 4934475), customEntityEntry(EntityDeviantPiglin.class, "deviantpiglin", 91102, 4934475), customEntityEntry(EntityTitanCreeper.class, "titancreeper", 91102, 4934475), customEntityEntry(EntityTitanEnderman.class, "titanenderman", 91102, 4934475), customEntityEntry(EntityTitanLlama.class, "titanllama", 91102, 4934475), customEntityEntry(EntityTitanMagmacube.class, "titanmagmacube", 91102, 4934475), customEntityEntry(EntityTitanPiglin.class, "titanpiglin", 91102, 4934475), customEntityEntry(EntityTitanStray.class, "titanstray", 91102, 4934475), customEntityEntry(EntityCourseRing.class, "coursering", 91102, 4934475), customEntityEntry(EntityTitanVex.class, "titanvex", 91102, 4934475), customEntityEntry(EntityTitanZombie.class, "titanzombie", 91102, 4934475), customEntityEntry(EntityGloop.class, "gloop", 91102, 4934475), customEntityEntry(EntityGloopMother.class, "gloopmother", 91102, 4934475), customEntityEntry(EntityCyclos.class, "cyclos", 91102, 4934475), customEntityEntry(EntityClinger.class, "clinger", 91102, 4934475), customEntityEntry(EntityDeviantDimTrader.class, "deviantdimtrader", 91102, 4934475), customEntityEntry(EntityMemPuzzleMerchant.class, "mempuzzlemerchant", 91102, 4934475), customEntityEntry(EntitySkybooster.class, "skybooster", 91102, 4934475), customEntityEntry(EntityRocketStrappedExplosive.class, "rocket_strapped_explosive", 91102, 4934475), customEntityEntry(EntityMarkOfInfiniteDespair.class, "mark_of_despair", 91102, 4934475), customEntityEntry(EntitySpectre.class, "spectre", 91102, 4934475), customEntityEntry(EntityContestHologram.class, "contest_hologram", 91102, 4934475), customEntityEntry(EntityContraderMarket.class, "contrader_market", 91102, 4934475), customEntityEntry(EntityContraderHolodeck.class, "contrader_holodeck", 91102, 4934475), customEntityEntry(EntityContraderHunters.class, "contrader_hunters", 91102, 4934475), customEntityEntry(EntityContraderLightbridge.class, "contrader_lightbridge", 91102, 4934475), customEntityEntry(EntityContraderTargets.class, "contrader_targets", 91102, 4934475), customEntityEntry(EntityContraderParkour.class, "contrader_parkour", 91102, 4934475), customEntityEntry(EntityContraderTrampolineDodgeball.class, "contrader_trampoline_dodgeball", 91102, 4934475), customEntityEntry(EntityOperatorHolodeck.class, "operator_holodeck", 91102, 4934475), customEntityEntry(EntityOperatorHunters.class, "operator_hunters", 91102, 4934475), customEntityEntry(EntityOperatorLightBridge.class, "operator_lightbridge", 91102, 4934475), customEntityEntry(EntityOperatorDuelArena.class, "operator_duelarena", 91102, 4934475), customEntityEntry(EntityOperatorTargets.class, "operator_targets", 91102, 4934475), customEntityEntry(EntityOperatorParkour.class, "operator_parkour", 91102, 4934475), customEntityEntry(EntityOperatorTrampolineDodgeball.class, "operator_trampoline_dodgeball", 91102, 4934475), customEntityEntry(EntityControllerHolodeck.class, "controller_holodeck", 91102, 4934475), customEntityEntry(EntityControllerHunters.class, "controller_hunters", 91102, 4934475), customEntityEntry(EntityControllerTargets.class, "controller_targets", 91102, 4934475), customEntityEntry(EntityControllerLightBridge.class, "controller_lightbridge", 91102, 4934475), customEntityEntry(EntityControllerDuelArena.class, "controller_duel_arena", 91102, 4934475), customEntityEntry(EntityControllerParkour.class, "controller_parkour", 91102, 4934475), customEntityEntry(EntityControllerTrampolineDodgeball.class, "controller_trampoline_dodgeball", 91102, 4934475), customEntityEntry(EntityParticleTrojan.class, "particletrojan", 91102, 4934475), customEntityEntry(EntityPlasmaExplosion.class, "plasmaexplosion", 91102, 4934475), customEntityEntry(EntityAzross.class, "azross", 91102, 4934475), customEntityEntry(EntityDuskerQueen.class, "duskerqueen", 91102, 4934475), customEntityEntry(EntityContraderRedlight.class, "contrader_redlight", 91102, 4934475), customEntityEntry(EntityOperatorRedlight.class, "operator_redlight", 91102, 4934475), customEntityEntry(EntityControllerRedlight.class, "controller_redlight", 91102, 4934475), customEntityEntry(EntityDeviantWither.class, "deviant_wither", 91102, 4934475), customEntityEntry(EntityWitherSkullling.class, "wither_skullling", 91102, 4934475), customEntityEntry(EntityGlangler.class, "glangler", 91102, 4934475), customEntityEntry(EntityGlochipper.class, "glochipper", 91102, 4934475), customEntityEntry(EntityGloboon.class, "globoon", 91102, 4934475), customEntityEntry(EntityEssenceDweller.class, "essencedweller", 91102, 4934475), customEntityEntry(EntityEssenceIdol.class, "essenceidol", 91102, 4934475), customEntityEntry(EntityGlobro.class, "globro", 91102, 4934475), customEntityEntry(EntityAugmenticon.class, "augmenticon", 91102, 4934475), customEntityEntry(EntityGalaxyGulper.class, "galaxygulper", 91102, 4934475), customEntityEntry(EntityLaserSpire.class, "laserspire", 91102, 4934475), customEntityEntry(EntityGiantFlapper.class, "giantflapper", 91102, 4934475), customEntityEntry(EntityIonExplosion.class, "ionexplosion", 91102, 4934475), customEntityEntry(EntityNitroExplosion.class, "nitroexplosion", 91102, 4934475), customEntityEntry(EntityDeviantGolem.class, "deviantgolem", 91102, 4934475), customEntityEntry(EntityStickyBomb.class, "stickybomb", 91102, 4934475), customEntityEntry(EntityVectosect.class, "vectosect", 91102, 4934475), customEntityEntry(EntityStickler.class, "stickler", 91102, 4934475), customEntityEntry(EntityUnstableMerchant.class, "unstablemerchant", 91102, 4934475), customEntityEntry(EntityFeralMerchant.class, "feralmerchant", 91102, 4934475), customEntityEntry(EntityDeviantCaveSpider.class, "deviantcavespider", 91102, 4934475), customEntityEntry(EntityTornIndividual.class, "tornindividual", 91102, 4934475), customEntityEntry(EntityRavager.class, "ravager", 91102, 4934475), customEntityEntry(EntityVycellia.class, "vycellia", 91102, 4934475), customEntityEntry(EntityPuzzleMaster.class, "puzzlemaster", 91102, 4934475), customEntityEntry(EntityNightshyre.class, "nightshyre", 91102, 4934475), customEntityEntry(EntityGiantFyreweed.class, "giantfyreweed", 91102, 4934475), customEntityEntry(EntityBomberBomb.class, "bomberbomb", 91102, 4934475), customEntityEntry(EntitySkycrab.class, "skycrab", 91102, 4934475), customEntityEntry(EntityGlomite.class, "glomite", 91102, 4934475), customEntityEntry(EntityTNTZombie.class, "tntzombie", 91102, 4934475), customEntityEntry(EntityDeviantBat.class, "deviantbat", 91102, 4934475), customEntityEntry(EntityOperatorBombers.class, "operator_bombers", 91102, 4934475), customEntityEntry(EntityControllerBombers.class, "controller_bombers", 91102, 4934475), customEntityEntry(EntityContraderBombers.class, "contrader_bombers", 91102, 4934475), customEntityEntry(EntityOperatorBattleSnakes.class, "operator_battle_snakes", 91102, 4934475), customEntityEntry(EntityControllerBattleSnakes.class, "controller_battle_snakes", 91102, 4934475), customEntityEntry(EntityContraderBattleSnakes.class, "contrader_battle_snakes", 91102, 4934475), customEntityEntry(EntityOperatorLaserTag.class, "operator_laser_tag", 91102, 4934475), customEntityEntry(EntityControllerLaserTag.class, "controller_laser_tag", 91102, 4934475), customEntityEntry(EntityContraderLaserTag.class, "contrader_laser_tag", 91102, 4934475), customEntityEntry(EntityOperatorInkBattle.class, "operator_ink_battle", 91102, 4934475), customEntityEntry(EntityControllerInkBattle.class, "controller_ink_battle", 91102, 4934475), customEntityEntry(EntityContraderInkBattle.class, "contrader_ink_battle", 91102, 4934475), customEntityEntry(EntityOperatorTreadmill.class, "operator_treadmill", 91102, 4934475), customEntityEntry(EntityControllerTreadmill.class, "controller_treadmill", 91102, 4934475), customEntityEntry(EntityContraderTreadmill.class, "contrader_treadmill", 91102, 4934475), customEntityEntry(EntityLightGame.class, "lightpuzzlemerchant", 91102, 4934475), customEntityEntry(EntityRockslug.class, "rockslug", 91102, 4934475), customEntityEntry(EntityGiantRockslug.class, "giant_rockslug", 91102, 4934475), customEntityEntry(EntityWhackGameMerchant.class, "whackgamemerchant", 91102, 4934475), customEntityEntry(EntityFlutterbee.class, "flutterbee", 91102, 4934475), customEntityEntry(EntityConnectGameMerchant.class, "connectgamemerchant", 91102, 4934475), customEntityEntry(EntityRhythmGameMerchant.class, "rhythmgamemerchant", 91102, 4934475), customEntityEntry(EntityPearlCollector.class, "pearlcollector", 91102, 4934475), customEntityEntry(EntityOzor.class, "ozor", 91102, 4934475), customEntityEntry(EntityOzorDecoy.class, "ozordecoy", 91102, 4934475), customEntityEntry(EntityTotemMoon.class, "totemmoon", 91102, 4934475), customEntityEntry(EntityTotemPylon.class, "totempylon", 91102, 4934475), customEntityEntry(EntityThundyron.class, "thundyron", 91102, 4934475), customEntityEntry(EntityCryonus.class, "cryonus", 91102, 4934475), customEntityEntry(EntityThunderBomb.class, "thunderbomb", 91102, 4934475), customEntityEntry(EntityStormBomb.class, "stormbomb", 91102, 4934475), customEntityEntry(EntityPipeGameMerchant.class, "pipegamemerchant", 91102, 4934475), customEntityEntry(EntityZenon.class, "zenon", 91102, 4934475), customEntityEntry(EntityCrusher.class, "crusher", 91102, 4934475), customEntityEntry(EntityDrippler.class, "drippler", 91102, 4934475), customEntityEntry(EntityGorger.class, "gorger", 91102, 4934475), customEntityEntry(EntityDoublejaw.class, "doublejaw", 91102, 4934475), customEntityEntry(EntityMinimite.class, "minimite", 91102, 4934475), customEntityEntry(EntityClusterweed.class, "clusterweed", 91102, 4934475), customEntityEntry(EntityWisp.class, "wisp", 91102, 4934475), customEntityEntry(EntityTetherbug.class, "tetherbug", 91102, 4934475), customEntityEntry(EntityCellGameMerchant.class, "cellgamemerchant", 91102, 4934475), customEntityEntry(EntityVilebulb.class, "vilebulb", 91102, 4934475), customEntityEntry(EntitySightwalker.class, "sightwalker", 91102, 4934475), customEntityEntry(EntityWeaver.class, "weaver", 91102, 4934475), customEntityEntry(EntityDoomDog.class, "doomdog", 91102, 4934475), customEntityEntry(EntityBlisterweed.class, "blisterweed", 91102, 4934475), customEntityEntry(EntityGrubber.class, "grubber", 91102, 4934475), customEntityEntry(EntityTitanopod.class, "titanopod", 91102, 4934475), customEntityEntry(EntitySnapper.class, "snapper", 91102, 4934475), customEntityEntry(EntityFlashfly.class, "flashfly", 91102, 4934475), customEntityEntry(EntityDeviantWitherSkeleton.class, "deviantwitherskeleton", 91102, 4934475), customEntityEntry(EntityTerrorFly.class, "terrorfly", 91102, 4934475), customEntityEntry(EntityTentaclon.class, "tentaclon", 91102, 4934475), customEntityEntry(EntityGalacticTerror.class, "galacticterror", 91102, 4934475), customEntityEntry(EntityDeviantGuardian.class, "deviantguardian", 91102, 4934475), customEntityEntry(EntityForbiddenBrand.class, "forbiddenbrand", 91102, 4934475), customEntityEntry(EntityPickleMan.class, "pickleman", 91102, 4934475), customEntityEntry(EntityMortarCannon.class, "mortarcannon", 91102, 4934475), customEntityEntry(EntityClusterCannon.class, "clustercannon", 91102, 4934475), customEntityEntry(EntityDeviantOcelote.class, "deviantocelote", 91102, 4934475), customEntityEntry(EntityLivorax.class, "livorax", 91102, 4934475), customEntityEntry(EntityLurcher.class, "lurcher", 91102, 4934475), customEntityEntry(EntityNat.class, "nat", 91102, 4934475), customEntityEntry(EntitySentry.class, "sentry", 91102, 4934475), customEntityEntry(EntityCaveTerror.class, "caveterror", 91102, 4934475), customEntityEntry(EntityWhisper.class, "whisper", 91102, 4934475), customEntityEntry(EntityTorpedon.class, "torpedon", 91102, 4934475), customEntityEntry(EntityRift.class, "rift", 91102, 4934475), customEntityEntry(EntityOrbiter.class, "orbiter", 91102, 4934475), customEntityEntry(EntityTotemSplitter.class, "totemsplitter", 91102, 4934475), customEntityEntry(EntityTentacleTrap.class, "tentacletrap", 91102, 4934475), customEntityEntry(EntityScorpwing.class, "scorpwing", 91102, 4934475), customEntityEntry(EntityDoomsday.class, "doomsday", 91102, 4934475), customEntityEntry(EntitySkyre.class, "skyre", 91102, 4934475), customEntityEntry(EntityRockworm.class, "rockworm", 91102, 4934475), customEntityEntry(EntityKalikos.class, "kalikos", 91102, 4934475), customEntityEntry(EntityGhostCopy.class, "ghostcopy", 91102, 4934475), customEntityEntry(EntityLeer.class, "leer", 91102, 4934475), customEntityEntry(EntityDoublerang.class, "doublerang", 91102, 4934475), customEntityEntry(EntityLongfin.class, "longfin", 91102, 4934475), customEntityEntry(EntityOctobrella.class, "octobrella", 91102, 4934475), customEntityEntry(EntityRayfish.class, "rayfish", 91102, 4934475), customEntityEntry(EntityGlowfish.class, "glowfish", 91102, 4934475), customEntityEntry(EntityDeviantSquid.class, "deviantsquid", 91102, 4934475), customEntityEntry(EntityUnderfin.class, "underfin", 91102, 4934475), customEntityEntry(EntityEelShark.class, "eelshark", 91102, 4934475), customEntityEntry(EntityCrabulon.class, "crabulon", 91102, 4934475), customEntityEntry(EntityRibshark.class, "ribshark", 91102, 4934475), customEntityEntry(EntityScreamer.class, "screamer", 91102, 4934475), customEntityEntry(EntityNebulaGrunt.class, "nebula_grunt", 91102, 4934475), customEntityEntry(EntityNebulaWizard.class, "nebula_wizard", 91102, 4934475), customEntityEntry(EntityNebulaGiant.class, "nebula_giant", 91102, 4934475), customEntityEntry(EntityArcheologist.class, "archeologist", 91102, 4934475), customEntityEntry(EntityMultiverseGhost.class, "multiverseghost", 91102, 4934475), customEntityEntry(EntityRisingPhantom.class, "risingphantom", 91102, 4934475), customEntityEntry(EntityAbyssalCrabulon.class, "tentaclelantern", 91102, 4934475), customEntityEntry(EntityLeviathanController.class, "leviathan", 91102, 4934475), customEntityEntry(EntitySeaSerpentController.class, "sea_serpent", 91102, 4934475), customEntityEntry(EntityGalaxyDragon.class, "galaxy_dragon", 91102, 4934475), customEntityEntry(EntityXScreacher.class, "x_screacher", 91102, 4934475), customEntityEntry(EntityLostBlade.class, "lost_blade", 91102, 4934475), customEntityEntry(EntityNuclearExplosion.class, "nuclear_explosion", 91102, 4934475), customEntityEntry(EntityMushmerra.class, "mushmerra", 91102, 4934475), customEntityEntry(EntityMushmerraClone.class, "mushmerra_clone", 91102, 4934475), customEntityEntry(EntityShroomite.class, "shroomite", 91102, 4934475), customEntityEntry(EntityAuraOfAllegiance.class, "aura_of_allegiance", 91102, 4934475), customEntityEntry(EntitySupplyTrader.class, "supply_trader", 91102, 4934475), customEntityEntry(EntityJetMount.class, "jet_mount", 91102, 4934475), customEntityEntry(EntityDeviantWolf.class, "deviant_wolf", 91102, 4934475), customEntityEntry(EntityDeviantHusk.class, "deviant_husk", 91102, 4934475), doEntityEntry(EntityAndromedaController.class, "andromeda", 91102, 4934475, true, 512), customEntityEntry(EntityBombDrone.class, "bomb_drone", 91102, 4934475), customEntityEntry(EntityPlayerLimb.class, "player_limb", 91102, 4934475), customEntityEntry(EntityCthulhu.class, "cthulhu", 91102, 4934475), customEntityEntry(EntityCthulhuTurret.class, "cthulhu_turret", 91102, 4934475), customEntityEntry(EntityCthulhuCloud.class, "cthulhu_cloud", 91102, 4934475), customEntityEntry(EntityCthulhuTentacle.class, "cthulhu_tentacle", 91102, 4934475), customEntityEntry(EntityCthulhuTentaclePersist.class, "cthulhu_tentacle_persist", 91102, 4934475), customEntityEntry(EntityCthulhuBeam.class, "cthulhu_beam", 91102, 4934475), egglessEntry(EntityCthulhuBlackHole.class, "cthulhu_black_hole", 91102, 4934475), egglessEntry(EntityCthulhuRift.class, "cthulhu_rift", 91102, 4934475), egglessEntry(EntityCthulhuHealingOrb.class, "cthulhu_healing_orb", 91102, 4934475), customEntityEntry(EntityCelestialStatue.class, "celestial_statue", 91102, 4934475), egglessEntry(EntityCthulhuDeathFX.class, "cthulhu_death_fx", 91102, 4934475)};
    }
    public static EntityEntry[] projectileEntries() {
        return new EntityEntry[]{customProjectileEntry(EntityElaraShot.class, "elarashot"), customProjectileEntry(EntitySkullShot.class, "skullshot"), customProjectileEntry(EntityDoomShot.class, "doomshot"), customProjectileEntry(EntityRainDrop.class, "raindrop"), customProjectileEntry(EntityAcidRainDrop.class, "acidraindrop"), customProjectileEntry(EntityDroidBall.class, "droidball"), customProjectileEntry(EntityDroidZapper.class, "droidzapper"), customProjectileEntry(EntityDroidSucker.class, "droidsucker"), customProjectileEntry(EntityDeviantShulkerBullet.class, "deviantshulkerbullet"), customProjectileEntry(EntityLivoraxBullet.class, "livoraxbullet"), customProjectileEntry(EntityWizardBlast.class, "wizardblast"), customProjectileEntry(EntityVeloMagic.class, "velomagic"), customProjectileEntry(EntityFluxBall.class, "fluxball"), customProjectileEntry(EntityGalaxyBlast.class, "galaxyblast"), customProjectileEntry(EntityGalaxySpell.class, "galaxyspell"), customProjectileEntry(EntityGalaxyBomb.class, "galaxybomb"), customProjectileEntry(EntityGalaxyKnife.class, "galaxyknife"), customProjectileEntry(EntityDeviantSucker.class, "deviantsucker"), customProjectileEntry(EntityDeviantDeployer.class, "deviantdeployer"), customProjectileEntry(EntityWitchMagic.class, "witchmagic"), customProjectileEntry(EntityCrystalGellball.class, "crystalgellball"), customProjectileEntry(EntityCarrierProjectile.class, "carrierprojectile"), customProjectileEntry(EntityFallingStar.class, "fallingstar"), customProjectileEntry(EntityWandAttack.class, "wandattack"), customProjectileEntry(EntityRockshot.class, "rockshot"), customProjectileEntry(EntitySonicAttack.class, "sonicattack"), customProjectileEntry(EntityXSonicAttack.class, "x_sonicattack"), customProjectileEntry(EntityDeviantSnowball.class, "deviantsnowball"), customProjectileEntry(EntityCelestialFire.class, "celestialfire"), customProjectileEntry(EntityZenonShot.class, "zenonshot"), customProjectileEntry(EntityLaserGunBeam.class, "lasergunbeam"), customProjectileEntry(EntityLuminousGuardianLaser.class, "luminousguardianlaser"), customProjectileEntry(EntityStunAttack.class, "stunattack"), customProjectileEntry(EntityDarkSpell.class, "darkspell"), customProjectileEntry(EntityCrystalShard.class, "crystalshard"), customProjectileEntry(EntityExplosiveGoo.class, "explosivegoo"), customProjectileEntry(EntityDestabilizer.class, "destabilizer"), customProjectileEntry(EntityComet.class, "comet"), customProjectileEntry(EntityMobComet.class, "mobcomet"), customProjectileEntry(EntityBlightedComet.class, "blightedcomet"), customProjectileEntry(EntityTentacleSeed.class, "tentacleseed"), customProjectileEntry(EntityHomingBlight.class, "homingblight"), customProjectileEntry(EntityAtlasAttack.class, "atlasattack"), customProjectileEntry(EntityDeviantSpit.class, "deviantspit"), customProjectileEntry(EntityVoidLaser.class, "voidlaser"), customProjectileEntry(EntitySkyStrike.class, "skystrike"), customProjectileEntry(EntityVenomBlast.class, "venomblast"), customProjectileEntry(EntityProjectileKiller.class, "projectilekiller"), customProjectileEntry(EntityBloodhunterBlast.class, "bloodhunterblast"), customProjectileEntry(EntityPowerPulse.class, "powerpulse"), customProjectileEntry(EntityGravityWarper.class, "gravitywarp"), customProjectileEntry(EntityWitherBomb.class, "witherbomb"), customProjectileEntry(EntityDeviantEvokerFangs.class, "deviantfang"), customProjectileEntry(EntityDeviantEvokerShot.class, "deviantevokershot"), customProjectileEntry(EntityDeviantEvokerBomb.class, "deviantevokerbomb"), customProjectileEntry(EntityElementiumWater.class, "elementiumwater"), customProjectileEntry(EntityElementiumAir.class, "elementiumair"), customProjectileEntry(EntityElementiumFire.class, "elementiumfire"), customProjectileEntry(EntityElementiumEarth.class, "elementiumearth"), customProjectileEntry(EntityDroidLaser.class, "droidlaser"), customProjectileEntry(EntityGalaxyLaser.class, "galaxylaser"), customProjectileEntry(EntityDuskerQueenWeb.class, "duskerqueenweb"), customProjectileEntry(EntityPlagueBlast.class, "plagueblast"), customProjectileEntry(EntityGenericBomb.class, "genericbomb"), customProjectileEntry(EntityStickyProjectile.class, "stickyprojectile"), customProjectileEntry(EntityFractureBomb.class, "fracturebomb"), customProjectileEntry(EntityUltraCrystalGel.class, "ultracrystalgel"), customProjectileEntry(EntityRecursor.class, "recursor"), customProjectileEntry(EntityInkBomb.class, "ink_bomb"), customProjectileEntry(EntityInkShot.class, "ink_shot"), customProjectileEntry(EntityEidolonMist.class, "eidolonmist"), customProjectileEntry(EntityWormholeShot.class, "wormholeshot"), customProjectileEntry(EntityWormholePortal.class, "wormholeportal"), customProjectileEntry(EntityIonicChakram.class, "ionicchakram"), customProjectileEntry(EntityMiniChakram.class, "minichakram"), customProjectileEntry(EntityInfinityTrident.class, "trident"), customProjectileEntry(EntityInfinityTridentMK2.class, "tridentmk2"), customProjectileEntry(EntityTitanRing.class, "titanring"), customProjectileEntry(EntityChampionDodgeball.class, "dodgeball"), customProjectileEntry(EntityAstralShot.class, "astralshot"), customProjectileEntry(EntitySpiderBlast.class, "spiderblast"), customProjectileEntry(EntityBarulChain.class, "barulchain"), customProjectileEntry(EntityTormentorChain.class, "tormentorchain"), customProjectileEntry(EntityGloomSpell.class, "gloomspell"), customProjectileEntry(EntityEchoBlast.class, "echoblast"), customProjectileEntry(EntityTNTStrapper.class, "tntstrapper"), customProjectileEntry(EntityElementiumShadow.class, "elementiumshadow"), customProjectileEntry(EntityElementiumBlight.class, "elementiumblight"), customProjectileEntry(EntityElementiumPlague.class, "elementiumplague"), customProjectileEntry(EntityUnstableBalloon.class, "unstableballoon"), customProjectileEntry(EntitySkycrabAttack.class, "skycrabattack"), customProjectileEntry(EntityCellularRock.class, "cellularrock"), customProjectileEntry(EntitySunstoneRock.class, "sunstonerock"), customProjectileEntry(EntityBeeAttack.class, "beeattack"), customProjectileEntry(EntityPiercingShot.class, "piercingshot"), customProjectileEntry(EntityMortarShot.class, "mortarshot"), customProjectileEntry(EntitySpikeBall.class, "spikeball"), customProjectileEntry(EntityExothermite.class, "exothermite"), customProjectileEntry(EntityBallOfContainedQuarks.class, "ballofquarks"), customProjectileEntry(EntityBallOfContainedGluons.class, "ballofgluons"), customProjectileEntry(EntityAcidicConcoction.class, "acidicconcoction"), customProjectileEntry(EntityPoisonousBubble.class, "poisonousbubble"), customProjectileEntry(EntityLaserBlast.class, "laserblast"), customProjectileEntry(EntitySelectionLaser.class, "selectionlaser"), customProjectileEntry(EntityDryadsGripAttack.class, "dryadsgrip"), customProjectileEntry(EntityFirePellet.class, "firepellet"), customProjectileEntry(EntityFountainPellet.class, "fountainpellet"), customProjectileEntry(EntityTetherBall.class, "tetherball"), customProjectileEntry(EntityClusterBlast.class, "clusterblast"), customProjectileEntry(EntityChainOfVenomsAttack.class, "venomchain"), customProjectileEntry(EntityPlasmaSlicer.class, "plasmaslicer"), customProjectileEntry(EntityAvengerLightning.class, "avengerlightning"), customProjectileEntry(EntityVoltaicIonizerAttack.class, "voltaicionizer"), customProjectileEntry(EntitySelectorAttack.class, "selector"), customProjectileEntry(EntityDebtCollectorEffect.class, "debtcollector"), customProjectileEntry(EntityPortalEffect.class, "portaleffect"), customProjectileEntry(EntityScreamerPortalEffect.class, "screamerportaleffect"), customProjectileEntry(EntityBossPortalEffect.class, "bossportaleffect"), customProjectileEntry(EntityPicklePortal.class, "pickleportal"), customProjectileEntry(EntityEffigyShot.class, "effigyshot"), customProjectileEntry(EntityEffigyEffect.class, "effigyeffect"), customProjectileEntry(EntityCryoBeamEffect.class, "cryobeam"), customProjectileEntry(EntityCryoBolt.class, "cryobolt"), customProjectileEntry(EntityFearBomb.class, "fearbomb"), customProjectileEntry(EntityBlightPellet.class, "blightpellet"), customProjectileEntry(EntityEchoOfGravity.class, "gravityecho"), customProjectileEntry(EntityArcBlast.class, "arcblast"), customProjectileEntry(EntityTekBullet.class, "tekbullet"), customProjectileEntry(EntityLaunchedKnife.class, "launchedknife"), customProjectileEntry(EntityElementiumPrime.class, "elementiumprime"), customProjectileEntry(EntityStrappedFirework.class, "strappedfirework"), customProjectileEntry(EntityPlasmaBomb.class, "plasma_bomb"), customProjectileEntry(EntityDoomBlast.class, "doomblast"), customProjectileEntry(EntityUnstableRift.class, "unstablerift"), customProjectileEntry(EntityEnergyBurst.class, "energyburst"), customProjectileEntry(EntityBlightBomb.class, "blightbomb"), customProjectileEntry(EntityScreamerBlast.class, "screamerblast"), customProjectileEntry(EntityAsteroid.class, "asteroid"), customProjectileEntry(EntityNebulaSpell.class, "nebulaspell"), customProjectileEntry(EntityMeteor.class, "meteor"), customProjectileEntry(EntityStarBlast.class, "starblast"), customProjectileEntry(EntityMicroRocket.class, "micro_rocket"), customProjectileEntry(EntityAvenger.class, "avenger"), customProjectileEntry(EntitySoundwaveBullet.class, "soundwave_bullet"), customProjectileEntry(EntityPuzzleMasterArrow.class, "puzzle_arrow"), customProjectileEntry(EntityLeviathanTracer.class, "leviathan_tracer"), customProjectileEntry(EntityLeviathanTeslaOrb.class, "leviathan_tesla_orb"), customProjectileEntry(EntityLeviathanBreath.class, "leviathan_breath"), customProjectileEntry(EntityGalaxyDragonFireball.class, "cosmic_fireball"), customProjectileEntry(EntityWhirlpool.class, "whirlpool"), customProjectileEntry(EntityCrabulonProjectile.class, "crabulon_projectile"), customProjectileEntry(EntityDeathShot.class, "death_shot"), customProjectileEntry(EntityEmberShot.class, "ember_shot"), customProjectileEntry(EntityCreepingVineArrow.class, "creeping_vine_arrow"), customProjectileEntry(EntityCreepingVinePod.class, "creeping_vine_pod"), customProjectileEntry(EntityAndromedaChaser.class, "andromeda_chaser"), customProjectileEntry(EntityCthulhuTurretBullet.class, "cthulhu_turret_bullet"), customProjectileEntry(EntityCthulhuMissile.class, "cthulhu_missile"), customProjectileEntry(EntityCthulhuMeteor.class, "cthulhu_meteor"), customProjectileEntry(EntityCthulhuSpear.class, "cthulhu_spear")};
    }
    public static void tileEntityRegister() {
        GameRegistry.registerTileEntity(TileEntityGenerator.class, new ResourceLocation(Reference.MODID, "shockwavegen"));
        GameRegistry.registerTileEntity(TileEntityCompressionTable.class, new ResourceLocation(Reference.MODID, "compression_table"));
        GameRegistry.registerTileEntity(TileEntitySapEvaporator.class, new ResourceLocation(Reference.MODID, "sap_evaporator"));
        GameRegistry.registerTileEntity(TileEntityNicroniumInfuser.class, new ResourceLocation(Reference.MODID, "nicronium_infuser"));
        GameRegistry.registerTileEntity(TileEntityLightEmitter.class, new ResourceLocation(Reference.MODID, "light_emitter"));
        GameRegistry.registerTileEntity(TileEntityPortalNode.class, new ResourceLocation(Reference.MODID, "portal_node"));
        GameRegistry.registerTileEntity(TileEntityPortalNexus.class, new ResourceLocation(Reference.MODID, "portal_nexus"));
        GameRegistry.registerTileEntity(TileEntityChromaGame.class, new ResourceLocation(Reference.MODID, "chroma_game"));
        GameRegistry.registerTileEntity(TileEntityAlignmentDialGame.class, new ResourceLocation(Reference.MODID, "alignment_dial_game"));
        GameRegistry.registerTileEntity(TileEntityVoidVacuum.class, new ResourceLocation(Reference.MODID, "void_vacuum"));
        GameRegistry.registerTileEntity(TileEntityRemoteControl.class, new ResourceLocation(Reference.MODID, "remote_control"));
        GameRegistry.registerTileEntity(TileEntityAncientSymbolInterpreter.class, new ResourceLocation(Reference.MODID, "symbol_interpreter"));
        GameRegistry.registerTileEntity(TileEntityPowerConduit.class, new ResourceLocation(Reference.MODID, "crossing_game"));
        GameRegistry.registerTileEntity(TileEntityPowerCollider.class, new ResourceLocation(Reference.MODID, "power_collider"));
        GameRegistry.registerTileEntity(TileEntityRainfallGenerator.class, new ResourceLocation(Reference.MODID, "rain_generator"));
        GameRegistry.registerTileEntity(TileEntityWeldingChamber.class, new ResourceLocation(Reference.MODID, "welding_chamber"));
        GameRegistry.registerTileEntity(TileEntityFusionTable.class, new ResourceLocation(Reference.MODID, "fusion_table"));
        GameRegistry.registerTileEntity(TileEntityPolymerizationDevice.class, new ResourceLocation(Reference.MODID, "polymerization"));
        GameRegistry.registerTileEntity(TileEntityNebulousBeacon.class, new ResourceLocation(Reference.MODID, "nebulous_beacon"));
        GameRegistry.registerTileEntity(TileEntityMelodicSequencer.class, new ResourceLocation(Reference.MODID, "melodicsequencer"));
        GameRegistry.registerTileEntity(TileEntityCircuitCalibrator.class, new ResourceLocation(Reference.MODID, "circuitcalibrator"));
        GameRegistry.registerTileEntity(TileEntityNavigationDevice.class, new ResourceLocation(Reference.MODID, "navigationdevice"));
        GameRegistry.registerTileEntity(TileEntityChemistryTable.class, new ResourceLocation(Reference.MODID, "chemistry_table"));
        GameRegistry.registerTileEntity(TileEntityTeslaTower.class, new ResourceLocation(Reference.MODID, "tesla_tower"));
        GameRegistry.registerTileEntity(TileEntityEternalBeacon.class, new ResourceLocation(Reference.MODID, "eternal_beacon"));
        GameRegistry.registerTileEntity(TileEntityShipmentFiller.class, new ResourceLocation(Reference.MODID, "shipment_filler"));
        GameRegistry.registerTileEntity(TileEntityDrillConsole.class, new ResourceLocation(Reference.MODID, "drill_console"));
        GameRegistry.registerTileEntity(TileEntityCthulhuSpawner.class, new ResourceLocation(Reference.MODID, "cthulhu_spawner"));
        GameRegistry.registerTileEntity(TileEntityGearbox.class, new ResourceLocation(Reference.MODID, "gearbox"));
        GameRegistry.registerTileEntity(TileEntityCombustionEngine.class, new ResourceLocation(Reference.MODID, "combustion_engine"));
        GameRegistry.registerTileEntity(TileEntityGrinder.class, new ResourceLocation(Reference.MODID, "grinder"));
        GameRegistry.registerTileEntity(TileEntityKillerVine.class, new ResourceLocation(Reference.MODID, "killer_vine"));
    }
}
