package xol.lostinfinity.init;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.util.EnumParticleTypes;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.event.TextureStitchEvent;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import xol.lostinfinity.client.fx.ParticleAcid;
import xol.lostinfinity.client.fx.ParticleAcidYellow;
import xol.lostinfinity.client.fx.ParticleAncientSpell;
import xol.lostinfinity.client.fx.ParticleAttractField;
import xol.lostinfinity.client.fx.ParticleBadMagic;
import xol.lostinfinity.client.fx.ParticleBasicStarType1;
import xol.lostinfinity.client.fx.ParticleBasicStarType2;
import xol.lostinfinity.client.fx.ParticleBasicStarType3;
import xol.lostinfinity.client.fx.ParticleBasicStarType4;
import xol.lostinfinity.client.fx.ParticleBlightSpellGreen;
import xol.lostinfinity.client.fx.ParticleBlightSpellPink;
import xol.lostinfinity.client.fx.ParticleBloodDrop;
import xol.lostinfinity.client.fx.ParticleBlueSkull;
import xol.lostinfinity.client.fx.ParticleBomberExplosion;
import xol.lostinfinity.client.fx.ParticleClawMarks;
import xol.lostinfinity.client.fx.ParticleClayBlock;
import xol.lostinfinity.client.fx.ParticleClayBubble;
import xol.lostinfinity.client.fx.ParticleCloudGreen;
import xol.lostinfinity.client.fx.ParticleCloudPurple;
import xol.lostinfinity.client.fx.ParticleCometBlue;
import xol.lostinfinity.client.fx.ParticleCometWhite;
import xol.lostinfinity.client.fx.ParticleCorruptionMagic;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType1;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType2;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType3;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType4;
import xol.lostinfinity.client.fx.ParticleCrescentMoon;
import xol.lostinfinity.client.fx.ParticleCrystalMagic;
import xol.lostinfinity.client.fx.ParticleDarkFizzle;
import xol.lostinfinity.client.fx.ParticleDarkFlash;
import xol.lostinfinity.client.fx.ParticleDarkMagic;
import xol.lostinfinity.client.fx.ParticleDragonFire;
import xol.lostinfinity.client.fx.ParticleElectricExplosionBlue;
import xol.lostinfinity.client.fx.ParticleElectricExplosionYellow;
import xol.lostinfinity.client.fx.ParticleExplosion;
import xol.lostinfinity.client.fx.ParticleExplosionBlue;
import xol.lostinfinity.client.fx.ParticleExplosionFear;
import xol.lostinfinity.client.fx.ParticleExplosionLavender;
import xol.lostinfinity.client.fx.ParticleExplosionOrange;
import xol.lostinfinity.client.fx.ParticleExplosionRed;
import xol.lostinfinity.client.fx.ParticleExplosionRing;
import xol.lostinfinity.client.fx.ParticleExplosionRingDark;
import xol.lostinfinity.client.fx.ParticleExplosionTeal;
import xol.lostinfinity.client.fx.ParticleExplosionYellow;
import xol.lostinfinity.client.fx.ParticleFiregoo;
import xol.lostinfinity.client.fx.ParticleFlameLarge;
import xol.lostinfinity.client.fx.ParticleFlameMedium;
import xol.lostinfinity.client.fx.ParticleFlameSmall;
import xol.lostinfinity.client.fx.ParticleGalaxyBlue;
import xol.lostinfinity.client.fx.ParticleGalaxyGreen;
import xol.lostinfinity.client.fx.ParticleGalaxyPurple;
import xol.lostinfinity.client.fx.ParticleGalaxyYellow;
import xol.lostinfinity.client.fx.ParticleGenericDotAcid;
import xol.lostinfinity.client.fx.ParticleGenericDotAqua;
import xol.lostinfinity.client.fx.ParticleGenericDotBlack;
import xol.lostinfinity.client.fx.ParticleGenericDotBlue;
import xol.lostinfinity.client.fx.ParticleGenericDotGreen;
import xol.lostinfinity.client.fx.ParticleGenericDotOrange;
import xol.lostinfinity.client.fx.ParticleGenericDotPink;
import xol.lostinfinity.client.fx.ParticleGenericDotPurple;
import xol.lostinfinity.client.fx.ParticleGenericDotRed;
import xol.lostinfinity.client.fx.ParticleGenericDotTangerine;
import xol.lostinfinity.client.fx.ParticleGenericDotWhite;
import xol.lostinfinity.client.fx.ParticleGenericDotYellow;
import xol.lostinfinity.client.fx.ParticleGlomiteWarp;
import xol.lostinfinity.client.fx.ParticleGloomBurst;
import xol.lostinfinity.client.fx.ParticleGloomSpell;
import xol.lostinfinity.client.fx.ParticleGoldStar;
import xol.lostinfinity.client.fx.ParticleGoldenMagic;
import xol.lostinfinity.client.fx.ParticleGooRing;
import xol.lostinfinity.client.fx.ParticleGrasp;
import xol.lostinfinity.client.fx.ParticleGravityRing;
import xol.lostinfinity.client.fx.ParticleHoneyBubble;
import xol.lostinfinity.client.fx.ParticleIonBlast;
import xol.lostinfinity.client.fx.ParticleIonFuel;
import xol.lostinfinity.client.fx.ParticleLargeBubble;
import xol.lostinfinity.client.fx.ParticleLargeBubblePurple;
import xol.lostinfinity.client.fx.ParticleLaserFizzle;
import xol.lostinfinity.client.fx.ParticleLaserFizzleLarge;
import xol.lostinfinity.client.fx.ParticleLightFizzle;
import xol.lostinfinity.client.fx.ParticleLightFlash;
import xol.lostinfinity.client.fx.ParticleLightningIndicator;
import xol.lostinfinity.client.fx.ParticleMiasma;
import xol.lostinfinity.client.fx.ParticleMurk;
import xol.lostinfinity.client.fx.ParticleMurkyMist;
import xol.lostinfinity.client.fx.ParticleNatureDot;
import xol.lostinfinity.client.fx.ParticleNatureMagic;
import xol.lostinfinity.client.fx.ParticleNatureRing;
import xol.lostinfinity.client.fx.ParticleNightmareMagic;
import xol.lostinfinity.client.fx.ParticleNuclearBlast;
import xol.lostinfinity.client.fx.ParticlePlague;
import xol.lostinfinity.client.fx.ParticlePlasma;
import xol.lostinfinity.client.fx.ParticlePlasmaExplosion;
import xol.lostinfinity.client.fx.ParticlePlasmaRift;
import xol.lostinfinity.client.fx.ParticlePoisonBubble;
import xol.lostinfinity.client.fx.ParticlePoisonExplosion;
import xol.lostinfinity.client.fx.ParticlePoisonRings;
import xol.lostinfinity.client.fx.ParticlePowerField;
import xol.lostinfinity.client.fx.ParticlePowerLoss;
import xol.lostinfinity.client.fx.ParticlePowerPulse;
import xol.lostinfinity.client.fx.ParticlePrismaticExplosionType1;
import xol.lostinfinity.client.fx.ParticlePrismaticExplosionType2;
import xol.lostinfinity.client.fx.ParticlePrismaticExplosionType3;
import xol.lostinfinity.client.fx.ParticlePurpleSkull;
import xol.lostinfinity.client.fx.ParticleQuantumMark;
import xol.lostinfinity.client.fx.ParticleRedSkull;
import xol.lostinfinity.client.fx.ParticleRepelField;
import xol.lostinfinity.client.fx.ParticleShadowBlast;
import xol.lostinfinity.client.fx.ParticleSlam;
import xol.lostinfinity.client.fx.ParticleSmallSpark;
import xol.lostinfinity.client.fx.ParticleSnowBubble;
import xol.lostinfinity.client.fx.ParticleSpaceMagic;
import xol.lostinfinity.client.fx.ParticleSpectral;
import xol.lostinfinity.client.fx.ParticleStationaryBubble;
import xol.lostinfinity.client.fx.ParticleSupersonicBlue;
import xol.lostinfinity.client.fx.ParticleSupersonicRed;
import xol.lostinfinity.client.fx.ParticleTeslaRingBlue;
import xol.lostinfinity.client.fx.ParticleTeslaRingYellow;
import xol.lostinfinity.client.fx.ParticleVenom;
import xol.lostinfinity.client.fx.ParticleVenomChain;
import xol.lostinfinity.client.fx.ParticleVenomRing;
import xol.lostinfinity.client.fx.ParticleWarp;
import xol.lostinfinity.client.fx.ParticleWatchingEye;
import xol.lostinfinity.client.fx.ParticleWebMagic;
import xol.lostinfinity.client.fx.ParticleWitherRings;
import xol.lostinfinity.client.fx.ParticleZap;
import xol.lostinfinity.util.Reference;
public class ParticleInit {
    public static TextureAtlasSprite GALAXY_YELLOW_SPRITE;
    public static TextureAtlasSprite GALAXY_BLUE_SPRITE;
    public static TextureAtlasSprite GALAXY_GREEN_SPRITE;
    public static TextureAtlasSprite GALAXY_PURPLE_SPRITE;
    public static TextureAtlasSprite HONEY_BUBBLE_SPRITE;
    public static TextureAtlasSprite POWER_LOSS_SPRITE;
    public static TextureAtlasSprite ANCIENT_SPELL_SPRITE;
    public static TextureAtlasSprite CLAW_MARKS_SPRITE;
    public static TextureAtlasSprite ELECTRIC_EXPLOSION_YELLOW_SPRITE;
    public static TextureAtlasSprite ELECTRIC_EXPLOSION_BLUE_SPRITE;
    public static TextureAtlasSprite CORRUPTION_MAGIC_SPRITE;
    public static TextureAtlasSprite NATURE_RING_SPRITE;
    public static TextureAtlasSprite NATURE_MAGIC_SPRITE;
    public static TextureAtlasSprite CRYSTAL_MAGIC_SPRITE;
    public static TextureAtlasSprite SHADOW_BLAST_SPRITE;
    public static TextureAtlasSprite GOLD_STAR_SPRITE;
    public static TextureAtlasSprite DARK_FIZZLE_SPRITE;
    public static TextureAtlasSprite POISON_BUBBLE_SPRITE;
    public static TextureAtlasSprite PURPLE_SKULL_SPRITE;
    public static TextureAtlasSprite BLIGHT_SPELL_PINK_SPRITE;
    public static TextureAtlasSprite BLIGHT_SPELL_GREEN_SPRITE;
    public static TextureAtlasSprite SNOW_BUBBLE_SPRITE;
    public static TextureAtlasSprite BLUE_SKULL_SPRITE;
    public static TextureAtlasSprite MURK_SPRITE;
    public static TextureAtlasSprite NIGHTMARE_MAGIC_SPRITE;
    public static TextureAtlasSprite PLASMA_RIFT_SPRITE;
    public static TextureAtlasSprite PLASMA_SPRITE;
    public static TextureAtlasSprite SPECTRAL_SPRITE;
    public static TextureAtlasSprite PRISMATIC_EXPLOSION_TYPE1_SPRITE;
    public static TextureAtlasSprite PRISMATIC_EXPLOSION_TYPE2_SPRITE;
    public static TextureAtlasSprite PRISMATIC_EXPLOSION_TYPE3_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_YELLOW_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_ORANGE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_TANGERINE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_RED_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_PINK_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_PURPLE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_BLUE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_AQUA_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_GREEN_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_ACID_SPRITE;
    public static TextureAtlasSprite EXPLOSION_RING_DARK_SPRITE;
    public static TextureAtlasSprite EXPLOSION_BLUE_SPRITE;
    public static TextureAtlasSprite EXPLOSION_TEAL_SPRITE;
    public static TextureAtlasSprite EXPLOSION_LAVENDER_SPRITE;
    public static TextureAtlasSprite GOLDEN_MAGIC_SPRITE;
    public static TextureAtlasSprite BLOOD_DROP_SPRITE;
    public static TextureAtlasSprite NATURE_DOT_SPRITE;
    public static TextureAtlasSprite SMALL_SPARK_SPRITE;
    public static TextureAtlasSprite ACID_YELLOW_SPRITE;
    public static TextureAtlasSprite POISON_EXPLOSION_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE1_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE2_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE3_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE4_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE1_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE2_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE3_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE4_SPRITE;
    public static TextureAtlasSprite LARGE_BUBBLE_SPRITE;
    public static TextureAtlasSprite LARGE_BUBBLE_PURPLE_SPRITE;
    public static TextureAtlasSprite MIASMA_SPRITE;
    public static TextureAtlasSprite SUPERSONIC_BLUE_SPRITE;
    public static TextureAtlasSprite SUPERSONIC_RED_SPRITE;
    public static TextureAtlasSprite EXPLOSION_RED_SPRITE;
    public static TextureAtlasSprite EXPLOSION_ORANGE_SPRITE;
    public static TextureAtlasSprite GRASP_SPRITE;
    public static TextureAtlasSprite BAD_MAGIC_SPRITE;
    public static TextureAtlasSprite CLAY_BUBBLE_SPRITE;
    public static TextureAtlasSprite CLAY_BLOCK_SPRITE;
    public static TextureAtlasSprite WATCHING_EYE_SPRITE;
    public static TextureAtlasSprite TESLA_RING_YELLOW_SPRITE;
    public static TextureAtlasSprite TESLA_RING_BLUE_SPRITE;
    public static TextureAtlasSprite ION_FUEL_SPRITE;
    public static TextureAtlasSprite EXPLOSION_YELLOW_SPRITE;
    public static TextureAtlasSprite DRAGON_FIRE_SPRITE;
    public static TextureAtlasSprite EXPLOSION_FEAR_SPRITE;
    public static TextureAtlasSprite STATIONARY_BUBBLE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_WHITE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_BLACK_SPRITE;
    public static TextureAtlasSprite MURKY_MIST_SPRITE;
    public static TextureAtlasSprite LIGHT_FIZZLE_SPRITE;
    public static TextureAtlasSprite RED_SKULL_SPRITE;
    public static TextureAtlasSprite CLOUD_GREEN_SPRITE;
    public static TextureAtlasSprite CLOUD_PURPLE_SPRITE;
    public static TextureAtlasSprite LIGHTNING_INDICATOR_SPRITE;
    public static TextureAtlasSprite FIREGOO_SPRITE;
    public static TextureAtlasSprite ACID_SPRITE;
    public static TextureAtlasSprite BASIC_SPRITE;
    public static TextureAtlasSprite COMET_BLUE_SPRITE;
    public static TextureAtlasSprite COMET_WHITE_SPRITE;
    public static TextureAtlasSprite VENOM_CHAIN_SPRITE;
    public static TextureAtlasSprite VENOM_SPRITE;
    public static TextureAtlasSprite VENOM_RING_SPRITE;
    public static TextureAtlasSprite PLASMA_EXPLOSION_SPRITE;
    public static TextureAtlasSprite QUANTUM_MARK_SPRITE;
    public static TextureAtlasSprite GRAVITY_RING_SPRITE;
    public static TextureAtlasSprite POWER_PULSE_SPRITE;
    public static TextureAtlasSprite WITHER_RINGS_SPRITE;
    public static TextureAtlasSprite ATTRACT_FIELD_SPRITE;
    public static TextureAtlasSprite REPEL_FIELD_SPRITE;
    public static TextureAtlasSprite LASER_FIZZLE_SPRITE;
    public static TextureAtlasSprite SLAM_SPRITE;
    public static TextureAtlasSprite WARP_SPRITE;
    public static TextureAtlasSprite ION_BLAST_SPRITE;
    public static TextureAtlasSprite NUCLEAR_BLAST_SPRITE;
    public static TextureAtlasSprite GLOOM_SPELL_SPRITE;
    public static TextureAtlasSprite WEB_MAGIC_SPRITE;
    public static TextureAtlasSprite DARK_FLASH_SPRITE;
    public static TextureAtlasSprite LIGHT_FLASH_SPRITE;
    public static TextureAtlasSprite GLOOM_BURST_SPRITE;
    public static TextureAtlasSprite GOO_RING_SPRITE;
    public static TextureAtlasSprite CRESCENT_MOON_SPRITE;
    public static TextureAtlasSprite EXPLOSION_SPRITE;
    public static TextureAtlasSprite DARK_MAGIC_SPRITE;
    public static TextureAtlasSprite EXPLOSION_RING_SPRITE;
    public static TextureAtlasSprite ZAP_SPRITE;
    public static TextureAtlasSprite POISON_RINGS_SPRITE;
    public static TextureAtlasSprite PLAGUE_SPRITE;
    public static TextureAtlasSprite FLAME_SMALL_SPRITE;
    public static TextureAtlasSprite FLAME_MEDIUM_SPRITE;
    public static TextureAtlasSprite FLAME_LARGE_SPRITE;
    public static TextureAtlasSprite BOMBER_EXPLOSION_SPRITE;
    public static TextureAtlasSprite GLOMITE_WARP_SPRITE;
    public static TextureAtlasSprite LASER_FIZZLE_LARGE_SPRITE;
    public static TextureAtlasSprite SPACE_MAGIC_SPRITE;
    public static TextureAtlasSprite POWER_FIELD_SPRITE;
    public static final EnumParticleTypes GALAXY_YELLOW = particleRegistry("galaxy_yellow");
    public static final EnumParticleTypes GALAXY_BLUE = particleRegistry("galaxy_blue");
    public static final EnumParticleTypes GALAXY_GREEN = particleRegistry("galaxy_green");
    public static final EnumParticleTypes GALAXY_PURPLE = particleRegistry("galaxy_purple");
    public static final EnumParticleTypes HONEY_BUBBLE = particleRegistry("honey_bubble");
    public static final EnumParticleTypes POWER_LOSS = particleRegistry("power_loss");
    public static final EnumParticleTypes ANCIENT_SPELL = particleRegistry("ancient_spell");
    public static final EnumParticleTypes CLAW_MARKS = particleRegistry("claw_marks");
    public static final EnumParticleTypes ELECTRIC_EXPLOSION_YELLOW = particleRegistry("electric_explosion_yellow");
    public static final EnumParticleTypes ELECTRIC_EXPLOSION_BLUE = particleRegistry("electric_explosion_blue");
    public static final EnumParticleTypes CORRUPTION_MAGIC = particleRegistry("corruption_magic");
    public static final EnumParticleTypes NATURE_RING = particleRegistry("nature_ring");
    public static final EnumParticleTypes NATURE_MAGIC = particleRegistry("nature_magic");
    public static final EnumParticleTypes CRYSTAL_MAGIC = particleRegistry("crystal_magic");
    public static final EnumParticleTypes VENOM_CHAIN = particleRegistry("venom_chain");
    public static final EnumParticleTypes SHADOW_BLAST = particleRegistry("shadow_blast");
    public static final EnumParticleTypes GOLD_STAR = particleRegistry("gold_star");
    public static final EnumParticleTypes DARK_FIZZLE = particleRegistry("dark_fizzle");
    public static final EnumParticleTypes POISON_BUBBLE = particleRegistry("poison_bubble");
    public static final EnumParticleTypes PURPLE_SKULL = particleRegistry("purple_skull");
    public static final EnumParticleTypes BLIGHT_SPELL_PINK = particleRegistry("blight_spell_pink");
    public static final EnumParticleTypes BLIGHT_SPELL_GREEN = particleRegistry("blight_spell_green");
    public static final EnumParticleTypes SNOW_BUBBLE = particleRegistry("snow_bubble");
    public static final EnumParticleTypes BLUE_SKULL = particleRegistry("blue_skull");
    public static final EnumParticleTypes MURK = particleRegistry("murk");
    public static final EnumParticleTypes NIGHTMARE_MAGIC = particleRegistry("nightmare_magic");
    public static final EnumParticleTypes PLASMA_RIFT = particleRegistry("plasma_rift");
    public static final EnumParticleTypes PLASMA = particleRegistry("plasma");
    public static final EnumParticleTypes SPECTRAL = particleRegistry("spectral");
    public static final EnumParticleTypes PRISMATIC_EXPLOSION_TYPE1 = particleRegistry("prismatic_explosion_type1");
    public static final EnumParticleTypes PRISMATIC_EXPLOSION_TYPE2 = particleRegistry("prismatic_explosion_type2");
    public static final EnumParticleTypes PRISMATIC_EXPLOSION_TYPE3 = particleRegistry("prismatic_explosion_type3");
    public static final EnumParticleTypes GENERIC_DOT_YELLOW = particleRegistry("generic_dot_yellow");
    public static final EnumParticleTypes GENERIC_DOT_ORANGE = particleRegistry("generic_dot_orange");
    public static final EnumParticleTypes GENERIC_DOT_TANGERINE = particleRegistry("generic_dot_tangerine");
    public static final EnumParticleTypes GENERIC_DOT_RED = particleRegistry("generic_dot_red");
    public static final EnumParticleTypes GENERIC_DOT_PINK = particleRegistry("generic_dot_pink");
    public static final EnumParticleTypes GENERIC_DOT_PURPLE = particleRegistry("generic_dot_purple");
    public static final EnumParticleTypes GENERIC_DOT_BLUE = particleRegistry("generic_dot_blue");
    public static final EnumParticleTypes GENERIC_DOT_AQUA = particleRegistry("generic_dot_aqua");
    public static final EnumParticleTypes GENERIC_DOT_GREEN = particleRegistry("generic_dot_green");
    public static final EnumParticleTypes GENERIC_DOT_ACID = particleRegistry("generic_dot_acid");
    public static final EnumParticleTypes EXPLOSION_RING_DARK = particleRegistry("explosion_ring_dark");
    public static final EnumParticleTypes EXPLOSION_BLUE = particleRegistry("explosion_blue");
    public static final EnumParticleTypes EXPLOSION_TEAL = particleRegistry("explosion_teal");
    public static final EnumParticleTypes EXPLOSION_LAVENDER = particleRegistry("explosion_lavender");
    public static final EnumParticleTypes GOLDEN_MAGIC = particleRegistry("golden_magic");
    public static final EnumParticleTypes BLOOD_DROP = particleRegistry("blood_drop");
    public static final EnumParticleTypes NATURE_DOT = particleRegistry("nature_dot");
    public static final EnumParticleTypes SMALL_SPARK = particleRegistry("small_spark");
    public static final EnumParticleTypes ACID_YELLOW = particleRegistry("acid_yellow");
    public static final EnumParticleTypes POISON_EXPLOSION = particleRegistry("poison_explosion");
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE1 = particleRegistry("cosmic_explosion_type1");
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE2 = particleRegistry("cosmic_explosion_type2");
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE3 = particleRegistry("cosmic_explosion_type3");
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE4 = particleRegistry("cosmic_explosion_type4");
    public static final EnumParticleTypes BASIC_STAR_TYPE1 = particleRegistry("basic_star_type1");
    public static final EnumParticleTypes BASIC_STAR_TYPE2 = particleRegistry("basic_star_type2");
    public static final EnumParticleTypes BASIC_STAR_TYPE3 = particleRegistry("basic_star_type3");
    public static final EnumParticleTypes BASIC_STAR_TYPE4 = particleRegistry("basic_star_type4");
    public static final EnumParticleTypes LARGE_BUBBLE = particleRegistry("large_bubble");
    public static final EnumParticleTypes LARGE_BUBBLE_PURPLE = particleRegistry("large_bubble_purple");
    public static final EnumParticleTypes MIASMA = particleRegistry("miasma");
    public static final EnumParticleTypes SUPERSONIC_BLUE = particleRegistry("supersonic_blue");
    public static final EnumParticleTypes SUPERSONIC_RED = particleRegistry("supersonic_red");
    public static final EnumParticleTypes EXPLOSION_RED = particleRegistry("explosion_red");
    public static final EnumParticleTypes EXPLOSION_ORANGE = particleRegistry("explosion_orange");
    public static final EnumParticleTypes GRASP = particleRegistry("grasp");
    public static final EnumParticleTypes BAD_MAGIC = particleRegistry("bad_magic");
    public static final EnumParticleTypes CLAY_BUBBLE = particleRegistry("clay_bubble");
    public static final EnumParticleTypes CLAY_BLOCK = particleRegistry("clay_block");
    public static final EnumParticleTypes WATCHING_EYE = particleRegistry("watching_eye");
    public static final EnumParticleTypes TESLA_RING_YELLOW = particleRegistry("tesla_ring_yellow");
    public static final EnumParticleTypes TESLA_RING_BLUE = particleRegistry("tesla_ring_blue");
    public static final EnumParticleTypes ION_FUEL = particleRegistry("ion_fuel");
    public static final EnumParticleTypes EXPLOSION_YELLOW = particleRegistry("explosion_yellow");
    public static final EnumParticleTypes DRAGON_FIRE = particleRegistry("dragon_fire");
    public static final EnumParticleTypes EXPLOSION_FEAR = particleRegistry("explosion_fear");
    public static final EnumParticleTypes STATIONARY_BUBBLE = particleRegistry("stationary_bubble");
    public static final EnumParticleTypes GENERIC_DOT_WHITE = particleRegistry("generic_dot_white");
    public static final EnumParticleTypes GENERIC_DOT_BLACK = particleRegistry("generic_dot_black");
    public static final EnumParticleTypes MURKY_MIST = particleRegistry("murky_mist");
    public static final EnumParticleTypes LIGHT_FIZZLE = particleRegistry("light_fizzle");
    public static final EnumParticleTypes RED_SKULL = particleRegistry("red_skull");
    public static final EnumParticleTypes CLOUD_GREEN = particleRegistry("cloud_green");
    public static final EnumParticleTypes CLOUD_PURPLE = particleRegistry("cloud_purple");
    public static final EnumParticleTypes LIGHTNING_INDICATOR = particleRegistry("lightning_indicator");
    public static final EnumParticleTypes VENOM = particleRegistry("venom");
    public static final EnumParticleTypes VENOM_RING = particleRegistry("venom_ring");
    public static final EnumParticleTypes GRAVITY_RING = particleRegistry("gravity_ring");
    public static final EnumParticleTypes COMET_BLUE = particleRegistry("comet_blue");
    public static final EnumParticleTypes COMET_WHITE = particleRegistry("comet_white");
    public static final EnumParticleTypes FIREGOO = particleRegistry("firegoo");
    public static final EnumParticleTypes ACID = particleRegistry("acid");
    public static final EnumParticleTypes PLASMA_EXPLOSION = particleRegistry("plasma_explosion");
    public static final EnumParticleTypes QUANTUM_MARK = particleRegistry("quantum_mark");
    public static final EnumParticleTypes POWER_PULSE = particleRegistry("power_pulse");
    public static final EnumParticleTypes WITHER_RINGS = particleRegistry("wither_rings");
    public static final EnumParticleTypes ATTRACT_FIELD = particleRegistry("attract_field");
    public static final EnumParticleTypes REPEL_FIELD = particleRegistry("repel_field");
    public static final EnumParticleTypes LASER_FIZZLE = particleRegistry("laser_fizzle");
    public static final EnumParticleTypes SLAM = particleRegistry("slam");
    public static final EnumParticleTypes WARP = particleRegistry("warp");
    public static final EnumParticleTypes ION_BLAST = particleRegistry("ion_blast");
    public static final EnumParticleTypes NUCLEAR_BLAST = particleRegistry("nuclear_blast");
    public static final EnumParticleTypes GOO_RING = particleRegistry("goo_ring");
    public static final EnumParticleTypes CRESCENT_MOON = particleRegistry("crescent_moon");
    public static final EnumParticleTypes EXPLOSION = particleRegistry("explosion");
    public static final EnumParticleTypes DARK_MAGIC = particleRegistry("dark_magic");
    public static final EnumParticleTypes EXPLOSION_RING = particleRegistry("explosion_ring");
    public static final EnumParticleTypes ZAP = particleRegistry("zap");
    public static final EnumParticleTypes POISON_RINGS = particleRegistry("poison_rings");
    public static final EnumParticleTypes PLAGUE = particleRegistry("plague");
    public static final EnumParticleTypes GLOOM_SPELL = particleRegistry("gloom_spell");
    public static final EnumParticleTypes WEB_MAGIC = particleRegistry("web_magic");
    public static final EnumParticleTypes DARK_FLASH = particleRegistry("dark_flash");
    public static final EnumParticleTypes LIGHT_FLASH = particleRegistry("light_flash");
    public static final EnumParticleTypes GLOOM_BURST = particleRegistry("gloom_burst");
    public static final EnumParticleTypes FLAME_SMALL = particleRegistry("flame_small");
    public static final EnumParticleTypes FLAME_MEDIUM = particleRegistry("flame_medium");
    public static final EnumParticleTypes FLAME_LARGE = particleRegistry("flame_large");
    public static final EnumParticleTypes BOMBER_EXPLOSION = particleRegistry("bomber_explosion");
    public static final EnumParticleTypes GLOMITE_WARP = particleRegistry("glomite_warp");
    public static final EnumParticleTypes POWER_FIELD = particleRegistry("power_field");
    public static final EnumParticleTypes SPACE_MAGIC = particleRegistry("space_magic");
    public static final EnumParticleTypes LASER_FIZZLE_LARGE = particleRegistry("laze_fizzle_large");
    @SubscribeEvent
    @SideOnly(Side.CLIENT)
    public void stitchEvent(TextureStitchEvent.Pre ev) {
        GALAXY_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/galaxy_yellow"));
        GALAXY_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/galaxy_blue"));
        GALAXY_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/galaxy_green"));
        GALAXY_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/galaxy_purple"));
        HONEY_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/honey_bubble"));
        POWER_LOSS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/power_loss"));
        ANCIENT_SPELL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/ancient_spell"));
        CLAW_MARKS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/claw_marks"));
        ELECTRIC_EXPLOSION_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/electric_explosion_yellow"));
        ELECTRIC_EXPLOSION_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/electric_explosion_blue"));
        CORRUPTION_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/corruption_magic"));
        NATURE_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/nature_ring"));
        NATURE_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/nature_magic"));
        CRYSTAL_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/crystal_magic"));
        SHADOW_BLAST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/shadow_blast"));
        GOLD_STAR_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/gold_star"));
        DARK_FIZZLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/dark_fizzle"));
        POISON_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/poison_bubble"));
        PURPLE_SKULL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/purple_skull"));
        BLIGHT_SPELL_PINK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/blight_spell_pink"));
        BLIGHT_SPELL_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/blight_spell_green"));
        SNOW_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/snow_bubble"));
        BLUE_SKULL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/blue_skull"));
        MURK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/murk"));
        NIGHTMARE_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/nightmare_magic"));
        PLASMA_RIFT_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/plasma_rift"));
        PLASMA_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/plasma"));
        SPECTRAL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/spectral"));
        PRISMATIC_EXPLOSION_TYPE1_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/prismatic_explosion_type1"));
        PRISMATIC_EXPLOSION_TYPE2_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/prismatic_explosion_type2"));
        PRISMATIC_EXPLOSION_TYPE3_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/prismatic_explosion_type3"));
        GENERIC_DOT_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_yellow"));
        GENERIC_DOT_ORANGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_orange"));
        GENERIC_DOT_TANGERINE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_tangerine"));
        GENERIC_DOT_RED_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_red"));
        GENERIC_DOT_PINK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_pink"));
        GENERIC_DOT_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_purple"));
        GENERIC_DOT_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_blue"));
        GENERIC_DOT_AQUA_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_aqua"));
        GENERIC_DOT_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_green"));
        GENERIC_DOT_ACID_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_acid"));
        EXPLOSION_RING_DARK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_ring_dark"));
        EXPLOSION_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_blue"));
        EXPLOSION_TEAL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_teal"));
        EXPLOSION_LAVENDER_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_lavender"));
        GOLDEN_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/golden_magic"));
        BLOOD_DROP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/blood_drop"));
        NATURE_DOT_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/nature_dot"));
        SMALL_SPARK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/small_spark"));
        ACID_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/acid_yellow"));
        POISON_EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/poison_explosion"));
        COSMIC_EXPLOSION_TYPE1_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/cosmic_explosion_type1"));
        COSMIC_EXPLOSION_TYPE2_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/cosmic_explosion_type2"));
        COSMIC_EXPLOSION_TYPE3_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/cosmic_explosion_type3"));
        COSMIC_EXPLOSION_TYPE4_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/cosmic_explosion_type4"));
        BASIC_STAR_TYPE1_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/basic_star_type1"));
        BASIC_STAR_TYPE2_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/basic_star_type2"));
        BASIC_STAR_TYPE3_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/basic_star_type3"));
        BASIC_STAR_TYPE4_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/basic_star_type4"));
        LARGE_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/large_bubble"));
        LARGE_BUBBLE_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/large_bubble_purple"));
        MIASMA_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/miasma"));
        SUPERSONIC_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/supersonic_blue"));
        SUPERSONIC_RED_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/supersonic_red"));
        EXPLOSION_RED_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_red"));
        EXPLOSION_ORANGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_orange"));
        GRASP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/grasp"));
        BAD_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/bad_magic"));
        CLAY_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/clay_bubble"));
        CLAY_BLOCK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/clay_block"));
        WATCHING_EYE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/watching_eye"));
        TESLA_RING_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/tesla_ring_yellow"));
        TESLA_RING_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/tesla_ring_blue"));
        ION_FUEL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/ion_fuel"));
        EXPLOSION_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_yellow"));
        DRAGON_FIRE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/dragon_fire"));
        EXPLOSION_FEAR_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_fear"));
        STATIONARY_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/large_bubble"));
        GENERIC_DOT_WHITE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_white"));
        GENERIC_DOT_BLACK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/generic_dot_black"));
        MURKY_MIST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/murky_mist"));
        LIGHT_FIZZLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/light_fizzle"));
        RED_SKULL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/red_skull"));
        CLOUD_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/cloud_green"));
        CLOUD_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/cloud_purple"));
        LIGHTNING_INDICATOR_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/lightning_indicator"));
        FIREGOO_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/firegoo"));
        ACID_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/acid"));
        COMET_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/comet_blue"));
        COMET_WHITE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/comet_white"));
        VENOM_CHAIN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/venom_chain"));
        VENOM_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/venom"));
        VENOM_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/venom_ring"));
        GRAVITY_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/gravity_ring"));
        QUANTUM_MARK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/quantum_mark"));
        PLASMA_EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/plasma_explosion"));
        POWER_PULSE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/power_pulse"));
        WITHER_RINGS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/wither_rings"));
        ATTRACT_FIELD_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/attract_field"));
        REPEL_FIELD_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/repel_field"));
        LASER_FIZZLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/laser_fizzle"));
        SLAM_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/slam"));
        WARP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/warp"));
        ION_BLAST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/ion_blast"));
        NUCLEAR_BLAST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/nuclear_blast"));
        GOO_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/goo_ring"));
        CRESCENT_MOON_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/crescent_moon"));
        EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion"));
        DARK_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/dark_magic"));
        EXPLOSION_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/explosion_ring"));
        ZAP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/zap"));
        POISON_RINGS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/poison_rings"));
        PLAGUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/plague"));
        GLOOM_SPELL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/gloom_spell"));
        WEB_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/web_magic"));
        DARK_FLASH_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/dark_flash"));
        LIGHT_FLASH_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/light_flash"));
        GLOOM_BURST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/gloom_burst"));
        FLAME_SMALL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/flame_small"));
        FLAME_MEDIUM_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/flame_medium"));
        FLAME_LARGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/flame_large"));
        BOMBER_EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/bomber_explosion"));
        GLOMITE_WARP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/glomite_warp"));
        LASER_FIZZLE_LARGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/laser_fizzle_large"));
        SPACE_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/space_magic"));
        POWER_FIELD_SPRITE = ev.getMap().func_174942_a(new ResourceLocation(Reference.MODID, "particles/power_field"));
    }
    @SideOnly(Side.CLIENT)
    public static void init() {
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_YELLOW.func_179348_c(), new ParticleGalaxyYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_BLUE.func_179348_c(), new ParticleGalaxyBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_GREEN.func_179348_c(), new ParticleGalaxyGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_PURPLE.func_179348_c(), new ParticleGalaxyPurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(HONEY_BUBBLE.func_179348_c(), new ParticleHoneyBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POWER_LOSS.func_179348_c(), new ParticlePowerLoss.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ANCIENT_SPELL.func_179348_c(), new ParticleAncientSpell.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLAW_MARKS.func_179348_c(), new ParticleClawMarks.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ELECTRIC_EXPLOSION_YELLOW.func_179348_c(), new ParticleElectricExplosionYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ELECTRIC_EXPLOSION_BLUE.func_179348_c(), new ParticleElectricExplosionBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CORRUPTION_MAGIC.func_179348_c(), new ParticleCorruptionMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NATURE_RING.func_179348_c(), new ParticleNatureRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NATURE_MAGIC.func_179348_c(), new ParticleNatureMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CRYSTAL_MAGIC.func_179348_c(), new ParticleCrystalMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(VENOM_CHAIN.func_179348_c(), new ParticleVenomChain.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SHADOW_BLAST.func_179348_c(), new ParticleShadowBlast.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GOLD_STAR.func_179348_c(), new ParticleGoldStar.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DARK_FIZZLE.func_179348_c(), new ParticleDarkFizzle.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POISON_BUBBLE.func_179348_c(), new ParticlePoisonBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PURPLE_SKULL.func_179348_c(), new ParticlePurpleSkull.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLIGHT_SPELL_PINK.func_179348_c(), new ParticleBlightSpellPink.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLIGHT_SPELL_GREEN.func_179348_c(), new ParticleBlightSpellGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SNOW_BUBBLE.func_179348_c(), new ParticleSnowBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLUE_SKULL.func_179348_c(), new ParticleBlueSkull.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(MURK.func_179348_c(), new ParticleMurk.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NIGHTMARE_MAGIC.func_179348_c(), new ParticleNightmareMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLASMA_RIFT.func_179348_c(), new ParticlePlasmaRift.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLASMA.func_179348_c(), new ParticlePlasma.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SPECTRAL.func_179348_c(), new ParticleSpectral.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PRISMATIC_EXPLOSION_TYPE1.func_179348_c(), new ParticlePrismaticExplosionType1.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PRISMATIC_EXPLOSION_TYPE2.func_179348_c(), new ParticlePrismaticExplosionType2.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PRISMATIC_EXPLOSION_TYPE3.func_179348_c(), new ParticlePrismaticExplosionType3.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_YELLOW.func_179348_c(), new ParticleGenericDotYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_ORANGE.func_179348_c(), new ParticleGenericDotOrange.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_TANGERINE.func_179348_c(), new ParticleGenericDotTangerine.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_RED.func_179348_c(), new ParticleGenericDotRed.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_PINK.func_179348_c(), new ParticleGenericDotPink.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_PURPLE.func_179348_c(), new ParticleGenericDotPurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_BLUE.func_179348_c(), new ParticleGenericDotBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_AQUA.func_179348_c(), new ParticleGenericDotAqua.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_GREEN.func_179348_c(), new ParticleGenericDotGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_ACID.func_179348_c(), new ParticleGenericDotAcid.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_RING_DARK.func_179348_c(), new ParticleExplosionRingDark.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_BLUE.func_179348_c(), new ParticleExplosionBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_TEAL.func_179348_c(), new ParticleExplosionTeal.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_LAVENDER.func_179348_c(), new ParticleExplosionLavender.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GOLDEN_MAGIC.func_179348_c(), new ParticleGoldenMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLOOD_DROP.func_179348_c(), new ParticleBloodDrop.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NATURE_DOT.func_179348_c(), new ParticleNatureDot.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SMALL_SPARK.func_179348_c(), new ParticleSmallSpark.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ACID_YELLOW.func_179348_c(), new ParticleAcidYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POISON_EXPLOSION.func_179348_c(), new ParticlePoisonExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE1.func_179348_c(), new ParticleCosmicExplosionType1.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE2.func_179348_c(), new ParticleCosmicExplosionType2.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE3.func_179348_c(), new ParticleCosmicExplosionType3.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE4.func_179348_c(), new ParticleCosmicExplosionType4.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE1.func_179348_c(), new ParticleBasicStarType1.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE2.func_179348_c(), new ParticleBasicStarType2.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE3.func_179348_c(), new ParticleBasicStarType3.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE4.func_179348_c(), new ParticleBasicStarType4.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LARGE_BUBBLE.func_179348_c(), new ParticleLargeBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LARGE_BUBBLE_PURPLE.func_179348_c(), new ParticleLargeBubblePurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(MIASMA.func_179348_c(), new ParticleMiasma.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SUPERSONIC_BLUE.func_179348_c(), new ParticleSupersonicBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SUPERSONIC_RED.func_179348_c(), new ParticleSupersonicRed.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_RED.func_179348_c(), new ParticleExplosionRed.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_ORANGE.func_179348_c(), new ParticleExplosionOrange.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GRASP.func_179348_c(), new ParticleGrasp.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BAD_MAGIC.func_179348_c(), new ParticleBadMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLAY_BUBBLE.func_179348_c(), new ParticleClayBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLAY_BLOCK.func_179348_c(), new ParticleClayBlock.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WATCHING_EYE.func_179348_c(), new ParticleWatchingEye.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(TESLA_RING_YELLOW.func_179348_c(), new ParticleTeslaRingYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(TESLA_RING_BLUE.func_179348_c(), new ParticleTeslaRingBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ION_FUEL.func_179348_c(), new ParticleIonFuel.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_YELLOW.func_179348_c(), new ParticleExplosionYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DRAGON_FIRE.func_179348_c(), new ParticleDragonFire.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_FEAR.func_179348_c(), new ParticleExplosionFear.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(STATIONARY_BUBBLE.func_179348_c(), new ParticleStationaryBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_WHITE.func_179348_c(), new ParticleGenericDotWhite.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_BLACK.func_179348_c(), new ParticleGenericDotBlack.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(MURKY_MIST.func_179348_c(), new ParticleMurkyMist.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LIGHT_FIZZLE.func_179348_c(), new ParticleLightFizzle.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(RED_SKULL.func_179348_c(), new ParticleRedSkull.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLOUD_GREEN.func_179348_c(), new ParticleCloudGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLOUD_PURPLE.func_179348_c(), new ParticleCloudPurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LIGHTNING_INDICATOR.func_179348_c(), new ParticleLightningIndicator.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FIREGOO.func_179348_c(), new ParticleFiregoo.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ACID.func_179348_c(), new ParticleAcid.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COMET_WHITE.func_179348_c(), new ParticleCometWhite.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COMET_BLUE.func_179348_c(), new ParticleCometBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(VENOM.func_179348_c(), new ParticleVenom.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(VENOM_RING.func_179348_c(), new ParticleVenomRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GRAVITY_RING.func_179348_c(), new ParticleGravityRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POWER_PULSE.func_179348_c(), new ParticlePowerPulse.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLASMA_EXPLOSION.func_179348_c(), new ParticlePlasmaExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(QUANTUM_MARK.func_179348_c(), new ParticleQuantumMark.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WITHER_RINGS.func_179348_c(), new ParticleWitherRings.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ATTRACT_FIELD.func_179348_c(), new ParticleAttractField.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(REPEL_FIELD.func_179348_c(), new ParticleRepelField.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LASER_FIZZLE.func_179348_c(), new ParticleLaserFizzle.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SLAM.func_179348_c(), new ParticleSlam.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WARP.func_179348_c(), new ParticleWarp.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ION_BLAST.func_179348_c(), new ParticleIonBlast.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NUCLEAR_BLAST.func_179348_c(), new ParticleNuclearBlast.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GOO_RING.func_179348_c(), new ParticleGooRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CRESCENT_MOON.func_179348_c(), new ParticleCrescentMoon.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION.func_179348_c(), new ParticleExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DARK_MAGIC.func_179348_c(), new ParticleDarkMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_RING.func_179348_c(), new ParticleExplosionRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ZAP.func_179348_c(), new ParticleZap.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POISON_RINGS.func_179348_c(), new ParticlePoisonRings.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLAGUE.func_179348_c(), new ParticlePlague.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GLOOM_SPELL.func_179348_c(), new ParticleGloomSpell.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WEB_MAGIC.func_179348_c(), new ParticleWebMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DARK_FLASH.func_179348_c(), new ParticleDarkFlash.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LIGHT_FLASH.func_179348_c(), new ParticleLightFlash.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GLOOM_BURST.func_179348_c(), new ParticleGloomBurst.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FLAME_SMALL.func_179348_c(), new ParticleFlameSmall.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FLAME_MEDIUM.func_179348_c(), new ParticleFlameMedium.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FLAME_LARGE.func_179348_c(), new ParticleFlameLarge.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BOMBER_EXPLOSION.func_179348_c(), new ParticleBomberExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GLOMITE_WARP.func_179348_c(), new ParticleGlomiteWarp.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POWER_FIELD.func_179348_c(), new ParticlePowerField.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LASER_FIZZLE_LARGE.func_179348_c(), new ParticleLaserFizzleLarge.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SPACE_MAGIC.func_179348_c(), new ParticleSpaceMagic.Factory());
    }
    private static EnumParticleTypes particleRegistry(String name) {
        return particleRegistry(name, true, 0);
    }
    private static EnumParticleTypes particleRegistry(String name, boolean displayAnyRange) {
        return particleRegistry(name, displayAnyRange, 0);
    }
    private static EnumParticleTypes particleRegistry(String name, boolean displayAnyRange, int args) {
        return EnumHelper.addEnum(EnumParticleTypes.class, "LI_" + name.toUpperCase(), new Class[]{String.class, Integer.TYPE, Boolean.TYPE, Integer.TYPE}, new Object[]{"li_" + name, Integer.valueOf(EnumParticleTypes.values().length), Boolean.valueOf(displayAnyRange), Integer.valueOf(args)});
    }
}
